# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BandSpliterDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BandSpliterDialog(object):
    def setupUi(self, BandSpliterDialog):
        BandSpliterDialog.setObjectName("BandSpliterDialog")
        BandSpliterDialog.resize(751, 546)
        self.verticalLayout = QtWidgets.QVBoxLayout(BandSpliterDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.selectSaveDirPushButton = QtWidgets.QPushButton(BandSpliterDialog)
        self.selectSaveDirPushButton.setText("")
        self.selectSaveDirPushButton.setObjectName("selectSaveDirPushButton")
        self.gridLayout_3.addWidget(self.selectSaveDirPushButton, 9, 7, 1, 1)
        self.splitBandLabel = QtWidgets.QLabel(BandSpliterDialog)
        self.splitBandLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.splitBandLabel.setObjectName("splitBandLabel")
        self.gridLayout_3.addWidget(self.splitBandLabel, 5, 4, 1, 1)
        self.removeFilePushButton = QtWidgets.QPushButton(BandSpliterDialog)
        self.removeFilePushButton.setText("")
        self.removeFilePushButton.setObjectName("removeFilePushButton")
        self.gridLayout_3.addWidget(self.removeFilePushButton, 2, 7, 1, 1)
        self.selectSaveFormatComboBox = QtWidgets.QComboBox(BandSpliterDialog)
        self.selectSaveFormatComboBox.setObjectName("selectSaveFormatComboBox")
        self.selectSaveFormatComboBox.addItem("")
        self.gridLayout_3.addWidget(self.selectSaveFormatComboBox, 8, 5, 1, 1)
        self.selectSaveStyleLabel = QtWidgets.QLabel(BandSpliterDialog)
        self.selectSaveStyleLabel.setObjectName("selectSaveStyleLabel")
        self.gridLayout_3.addWidget(self.selectSaveStyleLabel, 8, 0, 1, 1)
        self.selecrFileListTableWidget = QtWidgets.QTableWidget(BandSpliterDialog)
        self.selecrFileListTableWidget.setObjectName("selecrFileListTableWidget")
        self.selecrFileListTableWidget.setColumnCount(0)
        self.selecrFileListTableWidget.setRowCount(0)
        self.gridLayout_3.addWidget(self.selecrFileListTableWidget, 1, 0, 4, 7)
        self.selectSaveStyleComboBox = QtWidgets.QComboBox(BandSpliterDialog)
        self.selectSaveStyleComboBox.setObjectName("selectSaveStyleComboBox")
        self.selectSaveStyleComboBox.addItem("")
        self.selectSaveStyleComboBox.addItem("")
        self.gridLayout_3.addWidget(self.selectSaveStyleComboBox, 8, 1, 1, 1)
        self.validBandListWidget = QtWidgets.QListWidget(BandSpliterDialog)
        self.validBandListWidget.setObjectName("validBandListWidget")
        self.gridLayout_3.addWidget(self.validBandListWidget, 6, 0, 2, 3)
        self.selectSaveFormatLabel = QtWidgets.QLabel(BandSpliterDialog)
        self.selectSaveFormatLabel.setObjectName("selectSaveFormatLabel")
        self.gridLayout_3.addWidget(self.selectSaveFormatLabel, 8, 4, 1, 1)
        self.selectFilePushButton = QtWidgets.QPushButton(BandSpliterDialog)
        self.selectFilePushButton.setMaximumSize(QtCore.QSize(35, 16777215))
        self.selectFilePushButton.setText("")
        self.selectFilePushButton.setObjectName("selectFilePushButton")
        self.gridLayout_3.addWidget(self.selectFilePushButton, 1, 7, 1, 1)
        self.clearFilePushButton = QtWidgets.QPushButton(BandSpliterDialog)
        self.clearFilePushButton.setText("")
        self.clearFilePushButton.setObjectName("clearFilePushButton")
        self.gridLayout_3.addWidget(self.clearFilePushButton, 3, 7, 1, 1)
        self.selectSaveDirLineEdit = QtWidgets.QLineEdit(BandSpliterDialog)
        self.selectSaveDirLineEdit.setObjectName("selectSaveDirLineEdit")
        self.gridLayout_3.addWidget(self.selectSaveDirLineEdit, 9, 1, 1, 6)
        self.selectSaveDirLabel = QtWidgets.QLabel(BandSpliterDialog)
        self.selectSaveDirLabel.setObjectName("selectSaveDirLabel")
        self.gridLayout_3.addWidget(self.selectSaveDirLabel, 9, 0, 1, 1)
        self.addSplitBandToolButton = QtWidgets.QToolButton(BandSpliterDialog)
        self.addSplitBandToolButton.setObjectName("addSplitBandToolButton")
        self.gridLayout_3.addWidget(self.addSplitBandToolButton, 6, 3, 1, 1)
        self.selectFileListLabel = QtWidgets.QLabel(BandSpliterDialog)
        self.selectFileListLabel.setObjectName("selectFileListLabel")
        self.gridLayout_3.addWidget(self.selectFileListLabel, 0, 0, 1, 1)
        self.splitBandListWidget = QtWidgets.QListWidget(BandSpliterDialog)
        self.splitBandListWidget.setObjectName("splitBandListWidget")
        self.gridLayout_3.addWidget(self.splitBandListWidget, 6, 4, 2, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 7, 1, 1)
        self.selectSaveFileNameLineEdit = QtWidgets.QLineEdit(BandSpliterDialog)
        self.selectSaveFileNameLineEdit.setObjectName("selectSaveFileNameLineEdit")
        self.gridLayout_3.addWidget(self.selectSaveFileNameLineEdit, 10, 1, 1, 6)
        self.selectSaveFileNameLabel = QtWidgets.QLabel(BandSpliterDialog)
        self.selectSaveFileNameLabel.setObjectName("selectSaveFileNameLabel")
        self.gridLayout_3.addWidget(self.selectSaveFileNameLabel, 10, 0, 1, 1)
        self.selectSaveFileNamePushButton = QtWidgets.QPushButton(BandSpliterDialog)
        self.selectSaveFileNamePushButton.setText("")
        self.selectSaveFileNamePushButton.setObjectName("selectSaveFileNamePushButton")
        self.gridLayout_3.addWidget(self.selectSaveFileNamePushButton, 10, 7, 1, 1)
        self.validBandLabel = QtWidgets.QLabel(BandSpliterDialog)
        self.validBandLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.validBandLabel.setObjectName("validBandLabel")
        self.gridLayout_3.addWidget(self.validBandLabel, 5, 0, 1, 1)
        self.removeSplitBandToolButton = QtWidgets.QToolButton(BandSpliterDialog)
        self.removeSplitBandToolButton.setObjectName("removeSplitBandToolButton")
        self.gridLayout_3.addWidget(self.removeSplitBandToolButton, 7, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.line = QtWidgets.QFrame(BandSpliterDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.okPushButton = QtWidgets.QPushButton(BandSpliterDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(BandSpliterDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(BandSpliterDialog)
        QtCore.QMetaObject.connectSlotsByName(BandSpliterDialog)

    def retranslateUi(self, BandSpliterDialog):
        _translate = QtCore.QCoreApplication.translate
        BandSpliterDialog.setWindowTitle(_translate("BandSpliterDialog", "波段分离"))
        self.splitBandLabel.setText(_translate("BandSpliterDialog", "分离波段："))
        self.selectSaveFormatComboBox.setItemText(0, _translate("BandSpliterDialog", "GeoTiff(*.tif)"))
        self.selectSaveStyleLabel.setText(_translate("BandSpliterDialog", "保存方式："))
        self.selectSaveStyleComboBox.setItemText(0, _translate("BandSpliterDialog", "多波段文件"))
        self.selectSaveStyleComboBox.setItemText(1, _translate("BandSpliterDialog", "单波段文件"))
        self.selectSaveFormatLabel.setText(_translate("BandSpliterDialog", "保存格式："))
        self.selectSaveDirLabel.setText(_translate("BandSpliterDialog", "保存位置："))
        self.addSplitBandToolButton.setText(_translate("BandSpliterDialog", ">"))
        self.selectFileListLabel.setText(_translate("BandSpliterDialog", "文件列表："))
        self.selectSaveFileNameLabel.setText(_translate("BandSpliterDialog", "保存文件："))
        self.validBandLabel.setText(_translate("BandSpliterDialog", "有效波段："))
        self.removeSplitBandToolButton.setText(_translate("BandSpliterDialog", "<"))
        self.okPushButton.setText(_translate("BandSpliterDialog", "确定"))
        self.cancelPushButton.setText(_translate("BandSpliterDialog", "取消"))

