# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormulaApplicationDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormulaApplicationDialog(object):
    def setupUi(self, FormulaApplicationDialog):
        FormulaApplicationDialog.setObjectName("FormulaApplicationDialog")
        FormulaApplicationDialog.resize(828, 526)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormulaApplicationDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileListGridLayout = QtWidgets.QGridLayout()
        self.fileListGridLayout.setContentsMargins(5, 10, 5, 10)
        self.fileListGridLayout.setSpacing(10)
        self.fileListGridLayout.setObjectName("fileListGridLayout")
        self.inputFileTypeComboBox = QtWidgets.QComboBox(FormulaApplicationDialog)
        self.inputFileTypeComboBox.setObjectName("inputFileTypeComboBox")
        self.inputFileTypeComboBox.addItem("")
        self.inputFileTypeComboBox.addItem("")
        self.fileListGridLayout.addWidget(self.inputFileTypeComboBox, 0, 1, 1, 1)
        self.inputFileTypeLabel = QtWidgets.QLabel(FormulaApplicationDialog)
        self.inputFileTypeLabel.setObjectName("inputFileTypeLabel")
        self.fileListGridLayout.addWidget(self.inputFileTypeLabel, 0, 0, 1, 1)
        self.clearDataFilePushButton = QtWidgets.QPushButton(FormulaApplicationDialog)
        self.clearDataFilePushButton.setText("")
        self.clearDataFilePushButton.setObjectName("clearDataFilePushButton")
        self.fileListGridLayout.addWidget(self.clearDataFilePushButton, 3, 7, 1, 1)
        self.delDataFilePushButton = QtWidgets.QPushButton(FormulaApplicationDialog)
        self.delDataFilePushButton.setText("")
        self.delDataFilePushButton.setObjectName("delDataFilePushButton")
        self.fileListGridLayout.addWidget(self.delDataFilePushButton, 2, 7, 1, 1)
        self.fileListTableWidget = QtWidgets.QTableWidget(FormulaApplicationDialog)
        self.fileListTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.fileListTableWidget.setRowCount(20)
        self.fileListTableWidget.setColumnCount(2)
        self.fileListTableWidget.setObjectName("fileListTableWidget")
        self.fileListGridLayout.addWidget(self.fileListTableWidget, 1, 0, 4, 7)
        self.outputFileTypeComboBox = QtWidgets.QComboBox(FormulaApplicationDialog)
        self.outputFileTypeComboBox.setObjectName("outputFileTypeComboBox")
        self.outputFileTypeComboBox.addItem("")
        self.outputFileTypeComboBox.addItem("")
        self.fileListGridLayout.addWidget(self.outputFileTypeComboBox, 0, 4, 1, 1)
        self.outputFileTypeLabel = QtWidgets.QLabel(FormulaApplicationDialog)
        self.outputFileTypeLabel.setObjectName("outputFileTypeLabel")
        self.fileListGridLayout.addWidget(self.outputFileTypeLabel, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.fileListGridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.selectDataFilePushButton = QtWidgets.QPushButton(FormulaApplicationDialog)
        self.selectDataFilePushButton.setText("")
        self.selectDataFilePushButton.setObjectName("selectDataFilePushButton")
        self.fileListGridLayout.addWidget(self.selectDataFilePushButton, 1, 7, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.fileListGridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.verticalLayout.addLayout(self.fileListGridLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, 5, 5, 10)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.inputFormulaLineEdit = QtWidgets.QLineEdit(FormulaApplicationDialog)
        self.inputFormulaLineEdit.setObjectName("inputFormulaLineEdit")
        self.gridLayout.addWidget(self.inputFormulaLineEdit, 0, 1, 1, 1)
        self.inputFormulaLabel = QtWidgets.QLabel(FormulaApplicationDialog)
        self.inputFormulaLabel.setObjectName("inputFormulaLabel")
        self.gridLayout.addWidget(self.inputFormulaLabel, 0, 0, 1, 1)
        self.checkFormulaPushButton = QtWidgets.QPushButton(FormulaApplicationDialog)
        self.checkFormulaPushButton.setText("")
        self.checkFormulaPushButton.setObjectName("checkFormulaPushButton")
        self.gridLayout.addWidget(self.checkFormulaPushButton, 0, 2, 1, 1)
        self.variableSettingLabel = QtWidgets.QLabel(FormulaApplicationDialog)
        self.variableSettingLabel.setObjectName("variableSettingLabel")
        self.gridLayout.addWidget(self.variableSettingLabel, 1, 0, 1, 1)
        self.clearVarPushButton = QtWidgets.QPushButton(FormulaApplicationDialog)
        self.clearVarPushButton.setText("")
        self.clearVarPushButton.setObjectName("clearVarPushButton")
        self.gridLayout.addWidget(self.clearVarPushButton, 3, 2, 1, 1)
        self.delVarPushButton = QtWidgets.QPushButton(FormulaApplicationDialog)
        self.delVarPushButton.setText("")
        self.delVarPushButton.setObjectName("delVarPushButton")
        self.gridLayout.addWidget(self.delVarPushButton, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 2, 1, 1)
        self.variableSettingTableWidget = QtWidgets.QTableWidget(FormulaApplicationDialog)
        self.variableSettingTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.variableSettingTableWidget.setRowCount(20)
        self.variableSettingTableWidget.setColumnCount(2)
        self.variableSettingTableWidget.setObjectName("variableSettingTableWidget")
        self.gridLayout.addWidget(self.variableSettingTableWidget, 2, 0, 3, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(FormulaApplicationDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statusProgressBar = QtWidgets.QProgressBar(FormulaApplicationDialog)
        self.statusProgressBar.setStyleSheet("text-align: Center;color: rgb(0, 0, 0);font-weight: bold")
        self.statusProgressBar.setProperty("value", 0)
        self.statusProgressBar.setObjectName("statusProgressBar")
        self.horizontalLayout.addWidget(self.statusProgressBar)
        self.statusTipLabel = QtWidgets.QLabel(FormulaApplicationDialog)
        self.statusTipLabel.setText("")
        self.statusTipLabel.setObjectName("statusTipLabel")
        self.horizontalLayout.addWidget(self.statusTipLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.okPushButton = QtWidgets.QPushButton(FormulaApplicationDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(FormulaApplicationDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(FormulaApplicationDialog)
        QtCore.QMetaObject.connectSlotsByName(FormulaApplicationDialog)

    def retranslateUi(self, FormulaApplicationDialog):
        _translate = QtCore.QCoreApplication.translate
        FormulaApplicationDialog.setWindowTitle(_translate("FormulaApplicationDialog", "应用方程"))
        self.inputFileTypeComboBox.setItemText(0, _translate("FormulaApplicationDialog", "GeoTiff影像"))
        self.inputFileTypeComboBox.setItemText(1, _translate("FormulaApplicationDialog", "Excel表格数据"))
        self.inputFileTypeLabel.setText(_translate("FormulaApplicationDialog", "输入类型："))
        self.outputFileTypeComboBox.setItemText(0, _translate("FormulaApplicationDialog", "GeoTiff影像"))
        self.outputFileTypeComboBox.setItemText(1, _translate("FormulaApplicationDialog", "Excel表格数据"))
        self.outputFileTypeLabel.setText(_translate("FormulaApplicationDialog", "输出类型："))
        self.inputFormulaLabel.setText(_translate("FormulaApplicationDialog", "计算方程："))
        self.variableSettingLabel.setText(_translate("FormulaApplicationDialog", "变量设置："))
        self.okPushButton.setText(_translate("FormulaApplicationDialog", "确定"))
        self.cancelPushButton.setText(_translate("FormulaApplicationDialog", "取消"))

