# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PixelValueExtractorDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PixelValueExtractorDialog(object):
    def setupUi(self, PixelValueExtractorDialog):
        PixelValueExtractorDialog.setObjectName("PixelValueExtractorDialog")
        PixelValueExtractorDialog.resize(938, 584)
        self.verticalLayout = QtWidgets.QVBoxLayout(PixelValueExtractorDialog)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topGroupBox = QtWidgets.QGroupBox(PixelValueExtractorDialog)
        self.topGroupBox.setTitle("")
        self.topGroupBox.setObjectName("topGroupBox")
        self.topGroupBoxGridLayout = QtWidgets.QGridLayout(self.topGroupBox)
        self.topGroupBoxGridLayout.setContentsMargins(5, 5, 5, 5)
        self.topGroupBoxGridLayout.setHorizontalSpacing(10)
        self.topGroupBoxGridLayout.setVerticalSpacing(20)
        self.topGroupBoxGridLayout.setObjectName("topGroupBoxGridLayout")
        self.coordinateTypeComboBox = QtWidgets.QComboBox(self.topGroupBox)
        self.coordinateTypeComboBox.setObjectName("coordinateTypeComboBox")
        self.coordinateTypeComboBox.addItem("")
        self.coordinateTypeComboBox.addItem("")
        self.coordinateTypeComboBox.addItem("")
        self.topGroupBoxGridLayout.addWidget(self.coordinateTypeComboBox, 6, 1, 1, 1)
        self.fileListTableWidget = QtWidgets.QTableWidget(self.topGroupBox)
        self.fileListTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.fileListTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.fileListTableWidget.setRowCount(100)
        self.fileListTableWidget.setColumnCount(2)
        self.fileListTableWidget.setObjectName("fileListTableWidget")
        self.topGroupBoxGridLayout.addWidget(self.fileListTableWidget, 0, 0, 5, 11)
        self.yFieldLabel = QtWidgets.QLabel(self.topGroupBox)
        self.yFieldLabel.setObjectName("yFieldLabel")
        self.topGroupBoxGridLayout.addWidget(self.yFieldLabel, 6, 9, 1, 1)
        self.scaleFactorLineEdit = QtWidgets.QLineEdit(self.topGroupBox)
        self.scaleFactorLineEdit.setEnabled(False)
        self.scaleFactorLineEdit.setObjectName("scaleFactorLineEdit")
        self.topGroupBoxGridLayout.addWidget(self.scaleFactorLineEdit, 7, 4, 1, 1)
        self.selectSaveDirLabel = QtWidgets.QLabel(self.topGroupBox)
        self.selectSaveDirLabel.setObjectName("selectSaveDirLabel")
        self.topGroupBoxGridLayout.addWidget(self.selectSaveDirLabel, 8, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topGroupBoxGridLayout.addItem(spacerItem, 6, 5, 1, 1)
        self.pixelRadiusLabel = QtWidgets.QLabel(self.topGroupBox)
        self.pixelRadiusLabel.setObjectName("pixelRadiusLabel")
        self.topGroupBoxGridLayout.addWidget(self.pixelRadiusLabel, 7, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.topGroupBoxGridLayout.addItem(spacerItem1, 4, 11, 1, 1)
        self.invalidPixelLineEdit = QtWidgets.QLineEdit(self.topGroupBox)
        self.invalidPixelLineEdit.setEnabled(False)
        self.invalidPixelLineEdit.setObjectName("invalidPixelLineEdit")
        self.topGroupBoxGridLayout.addWidget(self.invalidPixelLineEdit, 7, 10, 1, 1)
        self.selectCoordinateFilePushButton = QtWidgets.QPushButton(self.topGroupBox)
        self.selectCoordinateFilePushButton.setText("")
        self.selectCoordinateFilePushButton.setObjectName("selectCoordinateFilePushButton")
        self.topGroupBoxGridLayout.addWidget(self.selectCoordinateFilePushButton, 5, 11, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topGroupBoxGridLayout.addItem(spacerItem2, 6, 2, 1, 1)
        self.noDataLineEdit = QtWidgets.QLineEdit(self.topGroupBox)
        self.noDataLineEdit.setEnabled(False)
        self.noDataLineEdit.setObjectName("noDataLineEdit")
        self.topGroupBoxGridLayout.addWidget(self.noDataLineEdit, 7, 7, 1, 1)
        self.delImageFilePushButton = QtWidgets.QPushButton(self.topGroupBox)
        self.delImageFilePushButton.setText("")
        self.delImageFilePushButton.setObjectName("delImageFilePushButton")
        self.topGroupBoxGridLayout.addWidget(self.delImageFilePushButton, 2, 11, 1, 1)
        self.yFieldComboBox = QtWidgets.QComboBox(self.topGroupBox)
        self.yFieldComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.yFieldComboBox.setObjectName("yFieldComboBox")
        self.yFieldComboBox.addItem("")
        self.topGroupBoxGridLayout.addWidget(self.yFieldComboBox, 6, 10, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topGroupBoxGridLayout.addItem(spacerItem3, 7, 5, 1, 1)
        self.selectCoordinateFileLabel = QtWidgets.QLabel(self.topGroupBox)
        self.selectCoordinateFileLabel.setObjectName("selectCoordinateFileLabel")
        self.topGroupBoxGridLayout.addWidget(self.selectCoordinateFileLabel, 5, 0, 1, 1)
        self.xFieldComboBox = QtWidgets.QComboBox(self.topGroupBox)
        self.xFieldComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.xFieldComboBox.setObjectName("xFieldComboBox")
        self.xFieldComboBox.addItem("")
        self.topGroupBoxGridLayout.addWidget(self.xFieldComboBox, 6, 7, 1, 1)
        self.scaleFactorLabel = QtWidgets.QLabel(self.topGroupBox)
        self.scaleFactorLabel.setObjectName("scaleFactorLabel")
        self.topGroupBoxGridLayout.addWidget(self.scaleFactorLabel, 7, 3, 1, 1)
        self.noDataLabel = QtWidgets.QLabel(self.topGroupBox)
        self.noDataLabel.setObjectName("noDataLabel")
        self.topGroupBoxGridLayout.addWidget(self.noDataLabel, 7, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topGroupBoxGridLayout.addItem(spacerItem4, 6, 8, 1, 1)
        self.pixelRadiusSpinBox = QtWidgets.QSpinBox(self.topGroupBox)
        self.pixelRadiusSpinBox.setObjectName("pixelRadiusSpinBox")
        self.topGroupBoxGridLayout.addWidget(self.pixelRadiusSpinBox, 7, 1, 1, 1)
        self.invalidPixelLabel = QtWidgets.QLabel(self.topGroupBox)
        self.invalidPixelLabel.setObjectName("invalidPixelLabel")
        self.topGroupBoxGridLayout.addWidget(self.invalidPixelLabel, 7, 9, 1, 1)
        self.xFieldLabel = QtWidgets.QLabel(self.topGroupBox)
        self.xFieldLabel.setObjectName("xFieldLabel")
        self.topGroupBoxGridLayout.addWidget(self.xFieldLabel, 6, 6, 1, 1)
        self.selectSaveDirPushButton = QtWidgets.QPushButton(self.topGroupBox)
        self.selectSaveDirPushButton.setText("")
        self.selectSaveDirPushButton.setObjectName("selectSaveDirPushButton")
        self.topGroupBoxGridLayout.addWidget(self.selectSaveDirPushButton, 8, 11, 1, 1)
        self.selectSaveDirLineEdit = QtWidgets.QLineEdit(self.topGroupBox)
        self.selectSaveDirLineEdit.setObjectName("selectSaveDirLineEdit")
        self.topGroupBoxGridLayout.addWidget(self.selectSaveDirLineEdit, 8, 1, 1, 10)
        self.coordinateTypeLabel = QtWidgets.QLabel(self.topGroupBox)
        self.coordinateTypeLabel.setObjectName("coordinateTypeLabel")
        self.topGroupBoxGridLayout.addWidget(self.coordinateTypeLabel, 6, 0, 1, 1)
        self.workSheetNameLabel = QtWidgets.QLabel(self.topGroupBox)
        self.workSheetNameLabel.setEnabled(True)
        self.workSheetNameLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.workSheetNameLabel.setObjectName("workSheetNameLabel")
        self.topGroupBoxGridLayout.addWidget(self.workSheetNameLabel, 6, 3, 1, 1)
        self.clearImageFilePushButton = QtWidgets.QPushButton(self.topGroupBox)
        self.clearImageFilePushButton.setText("")
        self.clearImageFilePushButton.setObjectName("clearImageFilePushButton")
        self.topGroupBoxGridLayout.addWidget(self.clearImageFilePushButton, 3, 11, 1, 1)
        self.workSheetComboBox = QtWidgets.QComboBox(self.topGroupBox)
        self.workSheetComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.workSheetComboBox.setObjectName("workSheetComboBox")
        self.workSheetComboBox.addItem("")
        self.topGroupBoxGridLayout.addWidget(self.workSheetComboBox, 6, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topGroupBoxGridLayout.addItem(spacerItem5, 7, 2, 1, 1)
        self.selectCoordinateFileLineEdit = QtWidgets.QLineEdit(self.topGroupBox)
        self.selectCoordinateFileLineEdit.setObjectName("selectCoordinateFileLineEdit")
        self.topGroupBoxGridLayout.addWidget(self.selectCoordinateFileLineEdit, 5, 1, 1, 10)
        self.selectImageFilePushButton = QtWidgets.QPushButton(self.topGroupBox)
        self.selectImageFilePushButton.setText("")
        self.selectImageFilePushButton.setObjectName("selectImageFilePushButton")
        self.topGroupBoxGridLayout.addWidget(self.selectImageFilePushButton, 1, 11, 1, 1)
        self.verticalLayout.addWidget(self.topGroupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 10, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressTipLabel = QtWidgets.QLabel(PixelValueExtractorDialog)
        self.progressTipLabel.setObjectName("progressTipLabel")
        self.horizontalLayout.addWidget(self.progressTipLabel)
        self.progressTipProgressBar = QtWidgets.QProgressBar(PixelValueExtractorDialog)
        self.progressTipProgressBar.setStyleSheet("text-align: Center;color: rgb(0, 0, 0);font-weight: bold")
        self.progressTipProgressBar.setProperty("value", 0)
        self.progressTipProgressBar.setObjectName("progressTipProgressBar")
        self.horizontalLayout.addWidget(self.progressTipProgressBar)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.okPushButton = QtWidgets.QPushButton(PixelValueExtractorDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(PixelValueExtractorDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PixelValueExtractorDialog)
        QtCore.QMetaObject.connectSlotsByName(PixelValueExtractorDialog)

    def retranslateUi(self, PixelValueExtractorDialog):
        _translate = QtCore.QCoreApplication.translate
        PixelValueExtractorDialog.setWindowTitle(_translate("PixelValueExtractorDialog", "像元值提取"))
        self.coordinateTypeComboBox.setItemText(0, _translate("PixelValueExtractorDialog", "地理坐标（lon，lat）"))
        self.coordinateTypeComboBox.setItemText(1, _translate("PixelValueExtractorDialog", "投影坐标（x，y）"))
        self.coordinateTypeComboBox.setItemText(2, _translate("PixelValueExtractorDialog", "图像坐标（row，col）"))
        self.yFieldLabel.setText(_translate("PixelValueExtractorDialog", "Y坐标字段："))
        self.scaleFactorLineEdit.setText(_translate("PixelValueExtractorDialog", "1"))
        self.selectSaveDirLabel.setText(_translate("PixelValueExtractorDialog", "保存路径："))
        self.pixelRadiusLabel.setText(_translate("PixelValueExtractorDialog", "像元半径："))
        self.invalidPixelLineEdit.setText(_translate("PixelValueExtractorDialog", "65536"))
        self.noDataLineEdit.setText(_translate("PixelValueExtractorDialog", "65536"))
        self.yFieldComboBox.setItemText(0, _translate("PixelValueExtractorDialog", "空"))
        self.selectCoordinateFileLabel.setText(_translate("PixelValueExtractorDialog", "坐标文件："))
        self.xFieldComboBox.setItemText(0, _translate("PixelValueExtractorDialog", "空"))
        self.scaleFactorLabel.setText(_translate("PixelValueExtractorDialog", "缩放因子："))
        self.noDataLabel.setText(_translate("PixelValueExtractorDialog", "NoData值："))
        self.invalidPixelLabel.setText(_translate("PixelValueExtractorDialog", "无效像元值："))
        self.xFieldLabel.setText(_translate("PixelValueExtractorDialog", "X坐标字段："))
        self.coordinateTypeLabel.setText(_translate("PixelValueExtractorDialog", "坐标类型："))
        self.workSheetNameLabel.setText(_translate("PixelValueExtractorDialog", "工作表名："))
        self.workSheetComboBox.setItemText(0, _translate("PixelValueExtractorDialog", "空"))
        self.progressTipLabel.setText(_translate("PixelValueExtractorDialog", "程序工作进度："))
        self.okPushButton.setText(_translate("PixelValueExtractorDialog", "确定"))
        self.cancelPushButton.setText(_translate("PixelValueExtractorDialog", "取消"))
