# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EmpiricalStatisticalModelDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EmpiricalStatisticalModelDialog(object):
    def setupUi(self, EmpiricalStatisticalModelDialog):
        EmpiricalStatisticalModelDialog.setObjectName("EmpiricalStatisticalModelDialog")
        EmpiricalStatisticalModelDialog.resize(796, 353)
        self.verticalLayout = QtWidgets.QVBoxLayout(EmpiricalStatisticalModelDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inSamplesGroupBox = QtWidgets.QGroupBox(EmpiricalStatisticalModelDialog)
        self.inSamplesGroupBox.setObjectName("inSamplesGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.inSamplesGroupBox)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.selectTrainingSamplesLabel = QtWidgets.QLabel(self.inSamplesGroupBox)
        self.selectTrainingSamplesLabel.setObjectName("selectTrainingSamplesLabel")
        self.gridLayout_2.addWidget(self.selectTrainingSamplesLabel, 2, 0, 1, 1)
        self.selectTrainingSamplesPushButton = QtWidgets.QPushButton(self.inSamplesGroupBox)
        self.selectTrainingSamplesPushButton.setText("")
        self.selectTrainingSamplesPushButton.setObjectName("selectTrainingSamplesPushButton")
        self.gridLayout_2.addWidget(self.selectTrainingSamplesPushButton, 2, 10, 1, 1)
        self.selectTestSamplesLabel = QtWidgets.QLabel(self.inSamplesGroupBox)
        self.selectTestSamplesLabel.setObjectName("selectTestSamplesLabel")
        self.gridLayout_2.addWidget(self.selectTestSamplesLabel, 3, 0, 1, 1)
        self.selectTestSamplesPushButton = QtWidgets.QPushButton(self.inSamplesGroupBox)
        self.selectTestSamplesPushButton.setText("")
        self.selectTestSamplesPushButton.setObjectName("selectTestSamplesPushButton")
        self.gridLayout_2.addWidget(self.selectTestSamplesPushButton, 3, 10, 1, 1)
        self.selectTrainingSamplesLineEdit = QtWidgets.QLineEdit(self.inSamplesGroupBox)
        self.selectTrainingSamplesLineEdit.setObjectName("selectTrainingSamplesLineEdit")
        self.gridLayout_2.addWidget(self.selectTrainingSamplesLineEdit, 2, 2, 1, 7)
        self.selectTestSamplesLineEdit = QtWidgets.QLineEdit(self.inSamplesGroupBox)
        self.selectTestSamplesLineEdit.setObjectName("selectTestSamplesLineEdit")
        self.gridLayout_2.addWidget(self.selectTestSamplesLineEdit, 3, 2, 1, 7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.sampleTypeLabel = QtWidgets.QLabel(self.inSamplesGroupBox)
        self.sampleTypeLabel.setObjectName("sampleTypeLabel")
        self.gridLayout_2.addWidget(self.sampleTypeLabel, 0, 0, 1, 1)
        self.isIncludeRowTitleCheckBox = QtWidgets.QCheckBox(self.inSamplesGroupBox)
        self.isIncludeRowTitleCheckBox.setChecked(True)
        self.isIncludeRowTitleCheckBox.setObjectName("isIncludeRowTitleCheckBox")
        self.gridLayout_2.addWidget(self.isIncludeRowTitleCheckBox, 0, 2, 1, 1)
        self.isIncludeColTitleCheckBox = QtWidgets.QCheckBox(self.inSamplesGroupBox)
        self.isIncludeColTitleCheckBox.setChecked(True)
        self.isIncludeColTitleCheckBox.setObjectName("isIncludeColTitleCheckBox")
        self.gridLayout_2.addWidget(self.isIncludeColTitleCheckBox, 0, 4, 1, 1)
        self.isRowMajorRadioButton = QtWidgets.QRadioButton(self.inSamplesGroupBox)
        self.isRowMajorRadioButton.setChecked(True)
        self.isRowMajorRadioButton.setObjectName("isRowMajorRadioButton")
        self.gridLayout_2.addWidget(self.isRowMajorRadioButton, 0, 6, 1, 1)
        self.isColMajorRadioButton = QtWidgets.QRadioButton(self.inSamplesGroupBox)
        self.isColMajorRadioButton.setObjectName("isColMajorRadioButton")
        self.gridLayout_2.addWidget(self.isColMajorRadioButton, 0, 8, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 7, 1, 1)
        self.verticalLayout.addWidget(self.inSamplesGroupBox)
        self.paramsSettingGroupBox = QtWidgets.QGroupBox(EmpiricalStatisticalModelDialog)
        self.paramsSettingGroupBox.setObjectName("paramsSettingGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.paramsSettingGroupBox)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.unfittedEquationListWidget = QtWidgets.QListWidget(self.paramsSettingGroupBox)
        self.unfittedEquationListWidget.setObjectName("unfittedEquationListWidget")
        item = QtWidgets.QListWidgetItem()
        self.unfittedEquationListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.unfittedEquationListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.unfittedEquationListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.unfittedEquationListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.unfittedEquationListWidget.addItem(item)
        self.gridLayout.addWidget(self.unfittedEquationListWidget, 1, 0, 4, 2)
        self.customEquationLabel = QtWidgets.QLabel(self.paramsSettingGroupBox)
        self.customEquationLabel.setObjectName("customEquationLabel")
        self.gridLayout.addWidget(self.customEquationLabel, 5, 0, 1, 1)
        self.customEquationLineEdit = QtWidgets.QLineEdit(self.paramsSettingGroupBox)
        self.customEquationLineEdit.setObjectName("customEquationLineEdit")
        self.gridLayout.addWidget(self.customEquationLineEdit, 5, 1, 1, 1)
        self.unfittedEquationLabel = QtWidgets.QLabel(self.paramsSettingGroupBox)
        self.unfittedEquationLabel.setObjectName("unfittedEquationLabel")
        self.gridLayout.addWidget(self.unfittedEquationLabel, 0, 0, 1, 2)
        self.addEquationPushButton = QtWidgets.QPushButton(self.paramsSettingGroupBox)
        self.addEquationPushButton.setMaximumSize(QtCore.QSize(35, 25))
        self.addEquationPushButton.setObjectName("addEquationPushButton")
        self.gridLayout.addWidget(self.addEquationPushButton, 2, 2, 1, 1)
        self.delEquationPushButton = QtWidgets.QPushButton(self.paramsSettingGroupBox)
        self.delEquationPushButton.setMaximumSize(QtCore.QSize(35, 25))
        self.delEquationPushButton.setObjectName("delEquationPushButton")
        self.gridLayout.addWidget(self.delEquationPushButton, 3, 2, 1, 1)
        self.fittedEquationTableWidget = QtWidgets.QTableWidget(self.paramsSettingGroupBox)
        self.fittedEquationTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.fittedEquationTableWidget.setRowCount(10)
        self.fittedEquationTableWidget.setObjectName("fittedEquationTableWidget")
        self.fittedEquationTableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.fittedEquationTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fittedEquationTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fittedEquationTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fittedEquationTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fittedEquationTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fittedEquationTableWidget.setItem(1, 1, item)
        self.gridLayout.addWidget(self.fittedEquationTableWidget, 1, 3, 5, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.verticalLayout.addWidget(self.paramsSettingGroupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.trainingTestPushButton = QtWidgets.QPushButton(EmpiricalStatisticalModelDialog)
        self.trainingTestPushButton.setObjectName("trainingTestPushButton")
        self.horizontalLayout.addWidget(self.trainingTestPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(EmpiricalStatisticalModelDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(EmpiricalStatisticalModelDialog)
        QtCore.QMetaObject.connectSlotsByName(EmpiricalStatisticalModelDialog)

    def retranslateUi(self, EmpiricalStatisticalModelDialog):
        _translate = QtCore.QCoreApplication.translate
        EmpiricalStatisticalModelDialog.setWindowTitle(_translate("EmpiricalStatisticalModelDialog", "经验统计模型"))
        self.inSamplesGroupBox.setTitle(_translate("EmpiricalStatisticalModelDialog", "输入样本"))
        self.selectTrainingSamplesLabel.setText(_translate("EmpiricalStatisticalModelDialog", "训练样本："))
        self.selectTestSamplesLabel.setText(_translate("EmpiricalStatisticalModelDialog", "测试样本（可选）："))
        self.sampleTypeLabel.setText(_translate("EmpiricalStatisticalModelDialog", "样本文件类型："))
        self.isIncludeRowTitleCheckBox.setText(_translate("EmpiricalStatisticalModelDialog", "包含行标题"))
        self.isIncludeColTitleCheckBox.setText(_translate("EmpiricalStatisticalModelDialog", "包含列标题"))
        self.isRowMajorRadioButton.setText(_translate("EmpiricalStatisticalModelDialog", "行优先"))
        self.isColMajorRadioButton.setText(_translate("EmpiricalStatisticalModelDialog", "列优先"))
        self.paramsSettingGroupBox.setTitle(_translate("EmpiricalStatisticalModelDialog", "参数设置"))
        __sortingEnabled = self.unfittedEquationListWidget.isSortingEnabled()
        self.unfittedEquationListWidget.setSortingEnabled(False)
        item = self.unfittedEquationListWidget.item(0)
        item.setText(_translate("EmpiricalStatisticalModelDialog", "y = α * x + β"))
        item = self.unfittedEquationListWidget.item(1)
        item.setText(_translate("EmpiricalStatisticalModelDialog", "y = α * x ** 2 + β * x + γ"))
        item = self.unfittedEquationListWidget.item(2)
        item.setText(_translate("EmpiricalStatisticalModelDialog", "y = α * exp (β * x)"))
        item = self.unfittedEquationListWidget.item(3)
        item.setText(_translate("EmpiricalStatisticalModelDialog", "y = α + β *  log(x )"))
        self.unfittedEquationListWidget.setSortingEnabled(__sortingEnabled)
        self.customEquationLabel.setText(_translate("EmpiricalStatisticalModelDialog", "自定义方程："))
        self.unfittedEquationLabel.setText(_translate("EmpiricalStatisticalModelDialog", "未拟合方程："))
        self.addEquationPushButton.setText(_translate("EmpiricalStatisticalModelDialog", ">"))
        self.delEquationPushButton.setText(_translate("EmpiricalStatisticalModelDialog", "<"))
        item = self.fittedEquationTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("EmpiricalStatisticalModelDialog", "待拟合方程"))
        item = self.fittedEquationTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("EmpiricalStatisticalModelDialog", "初始化参数"))
        __sortingEnabled = self.fittedEquationTableWidget.isSortingEnabled()
        self.fittedEquationTableWidget.setSortingEnabled(False)
        item = self.fittedEquationTableWidget.item(0, 0)
        item.setText(_translate("EmpiricalStatisticalModelDialog", "y = α * x + β"))
        item = self.fittedEquationTableWidget.item(0, 1)
        item.setText(_translate("EmpiricalStatisticalModelDialog", "10,10"))
        self.fittedEquationTableWidget.setSortingEnabled(__sortingEnabled)
        self.trainingTestPushButton.setText(_translate("EmpiricalStatisticalModelDialog", "训练/测试"))
        self.cancelPushButton.setText(_translate("EmpiricalStatisticalModelDialog", "取消"))

