# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FeatureSelectorDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from utils.icons import get_icon

class Ui_FeatureSelectorDialog(object):
    def setupUi(self, FeatureSelectorDialog):
        FeatureSelectorDialog.setObjectName("FeatureSelectorDialog")
        FeatureSelectorDialog.resize(850, 550)
        self.verticalLayout = QtWidgets.QVBoxLayout(FeatureSelectorDialog)
        self.verticalLayout.setContentsMargins(10, 10, 10, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.dataFormatLabel = QtWidgets.QLabel(FeatureSelectorDialog)
        self.dataFormatLabel.setObjectName("dataFormatLabel")
        self.gridLayout.addWidget(self.dataFormatLabel, 0, 0, 1, 1)
        self.isIncludeRowTitleCheckBox = QtWidgets.QCheckBox(FeatureSelectorDialog)
        self.isIncludeRowTitleCheckBox.setChecked(True)
        self.isIncludeRowTitleCheckBox.setObjectName("isIncludeRowTitleCheckBox")
        self.gridLayout.addWidget(self.isIncludeRowTitleCheckBox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.isIncludeColTitleCheckBox = QtWidgets.QCheckBox(FeatureSelectorDialog)
        self.isIncludeColTitleCheckBox.setChecked(True)
        self.isIncludeColTitleCheckBox.setObjectName("isIncludeColTitleCheckBox")
        self.gridLayout.addWidget(self.isIncludeColTitleCheckBox, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.isRowMajorRadioButton = QtWidgets.QRadioButton(FeatureSelectorDialog)
        self.isRowMajorRadioButton.setObjectName("isRowMajorRadioButton")
        self.gridLayout.addWidget(self.isRowMajorRadioButton, 0, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 6, 1, 1)
        self.isColMajorRadioButton = QtWidgets.QRadioButton(FeatureSelectorDialog)
        self.isColMajorRadioButton.setChecked(True)
        self.isColMajorRadioButton.setObjectName("isColMajorRadioButton")
        self.gridLayout.addWidget(self.isColMajorRadioButton, 0, 7, 1, 1)
        self.significanceStandardLabel = QtWidgets.QLabel(FeatureSelectorDialog)
        self.significanceStandardLabel.setObjectName("significanceStandardLabel")
        self.gridLayout.addWidget(self.significanceStandardLabel, 1, 0, 1, 1)
        self.isCalculateVarianceCheckBox = QtWidgets.QCheckBox(FeatureSelectorDialog)
        self.isCalculateVarianceCheckBox.setChecked(True)
        self.isCalculateVarianceCheckBox.setObjectName("isCalculateVarianceCheckBox")
        self.gridLayout.addWidget(self.isCalculateVarianceCheckBox, 1, 1, 1, 1)
        self.isCalculatePearsonCorrCoefCheckBox = QtWidgets.QCheckBox(FeatureSelectorDialog)
        self.isCalculatePearsonCorrCoefCheckBox.setChecked(True)
        self.isCalculatePearsonCorrCoefCheckBox.setObjectName("isCalculatePearsonCorrCoefCheckBox")
        self.gridLayout.addWidget(self.isCalculatePearsonCorrCoefCheckBox, 1, 3, 1, 1)
        self.isCalculateDistanceCorrCoefCheckBox = QtWidgets.QCheckBox(FeatureSelectorDialog)
        self.isCalculateDistanceCorrCoefCheckBox.setChecked(True)
        self.isCalculateDistanceCorrCoefCheckBox.setObjectName("isCalculateDistanceCorrCoefCheckBox")
        self.gridLayout.addWidget(self.isCalculateDistanceCorrCoefCheckBox, 1, 5, 1, 1)
        self.selectOpenDataFileLabel = QtWidgets.QLabel(FeatureSelectorDialog)
        self.selectOpenDataFileLabel.setObjectName("selectOpenDataFileLabel")
        self.gridLayout.addWidget(self.selectOpenDataFileLabel, 2, 0, 1, 1)
        self.selectOpenDataFilePushButton = QtWidgets.QPushButton(FeatureSelectorDialog)
        self.selectOpenDataFilePushButton.setText("")
        self.selectOpenDataFilePushButton.setIcon(get_icon("open_file"))
        self.selectOpenDataFilePushButton.setObjectName("selectOpenDataFilePushButton")
        self.gridLayout.addWidget(self.selectOpenDataFilePushButton, 2, 8, 1, 1)
        self.selectOpenDataFileLineEdit = QtWidgets.QLineEdit(FeatureSelectorDialog)
        self.selectOpenDataFileLineEdit.setObjectName("selectOpenDataFileLineEdit")
        self.gridLayout.addWidget(self.selectOpenDataFileLineEdit, 2, 1, 1, 7)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line = QtWidgets.QFrame(FeatureSelectorDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.selectSaveSalientFeatureLabel = QtWidgets.QLabel(FeatureSelectorDialog)
        self.selectSaveSalientFeatureLabel.setObjectName("selectSaveSalientFeatureLabel")
        self.gridLayout_2.addWidget(self.selectSaveSalientFeatureLabel, 1, 0, 1, 1)
        self.selectSaveSignificanceChartLabel = QtWidgets.QLabel(FeatureSelectorDialog)
        self.selectSaveSignificanceChartLabel.setObjectName("selectSaveSignificanceChartLabel")
        self.gridLayout_2.addWidget(self.selectSaveSignificanceChartLabel, 2, 0, 1, 1)
        self.selectSaveSignificanceChartPushButton = QtWidgets.QPushButton(FeatureSelectorDialog)
        self.selectSaveSignificanceChartPushButton.setEnabled(False)
        self.selectSaveSignificanceChartPushButton.setText("")
        self.selectSaveSignificanceChartPushButton.setIcon(get_icon("save_file"))
        self.selectSaveSignificanceChartPushButton.setObjectName("selectSaveSignificanceChartPushButton")
        self.gridLayout_2.addWidget(self.selectSaveSignificanceChartPushButton, 2, 9, 1, 1)
        self.selectSalientFeatureLabel = QtWidgets.QLabel(FeatureSelectorDialog)
        self.selectSalientFeatureLabel.setObjectName("selectSalientFeatureLabel")
        self.gridLayout_2.addWidget(self.selectSalientFeatureLabel, 0, 0, 1, 1)
        self.selectSalientFeatureComboBox = QtWidgets.QComboBox(FeatureSelectorDialog)
        self.selectSalientFeatureComboBox.setObjectName("selectSalientFeatureComboBox")
        self.gridLayout_2.addWidget(self.selectSalientFeatureComboBox, 0, 1, 1, 2)
        self.selectSaveSalientFeaturePushButton = QtWidgets.QPushButton(FeatureSelectorDialog)
        self.selectSaveSalientFeaturePushButton.setText("")
        self.selectSaveSalientFeaturePushButton.setIcon(get_icon("save_file"))
        self.selectSaveSalientFeaturePushButton.setObjectName("selectSaveSalientFeaturePushButton")
        self.gridLayout_2.addWidget(self.selectSaveSalientFeaturePushButton, 1, 9, 1, 1)
        self.selectSaveSalientFeatureLineEdit = QtWidgets.QLineEdit(FeatureSelectorDialog)
        self.selectSaveSalientFeatureLineEdit.setObjectName("selectSaveSalientFeatureLineEdit")
        self.gridLayout_2.addWidget(self.selectSaveSalientFeatureLineEdit, 1, 1, 1, 8)
        self.selectSaveSignificanceChartLineEdit = QtWidgets.QLineEdit(FeatureSelectorDialog)
        self.selectSaveSignificanceChartLineEdit.setEnabled(False)
        self.selectSaveSignificanceChartLineEdit.setObjectName("selectSaveSignificanceChartLineEdit")
        self.gridLayout_2.addWidget(self.selectSaveSignificanceChartLineEdit, 2, 1, 1, 8)
        self.isSaveSignificanceInfoCheckBox = QtWidgets.QCheckBox(FeatureSelectorDialog)
        self.isSaveSignificanceInfoCheckBox.setChecked(True)
        self.isSaveSignificanceInfoCheckBox.setObjectName("isSaveSignificanceInfoCheckBox")
        self.gridLayout_2.addWidget(self.isSaveSignificanceInfoCheckBox, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 7, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.groupBox = QtWidgets.QGroupBox(FeatureSelectorDialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.significanceCharHorizontalLayout = QtWidgets.QHBoxLayout()
        self.significanceCharHorizontalLayout.setSpacing(5)
        self.significanceCharHorizontalLayout.setObjectName("significanceCharHorizontalLayout")
        self.horizontalLayout_3.addLayout(self.significanceCharHorizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout.setStretch(3, 1)

        self.retranslateUi(FeatureSelectorDialog)
        QtCore.QMetaObject.connectSlotsByName(FeatureSelectorDialog)

    def retranslateUi(self, FeatureSelectorDialog):
        _translate = QtCore.QCoreApplication.translate
        FeatureSelectorDialog.setWindowTitle(_translate("FeatureSelectorDialog", "特征选择"))
        self.dataFormatLabel.setText(_translate("FeatureSelectorDialog", "数据格式："))
        self.isIncludeRowTitleCheckBox.setText(_translate("FeatureSelectorDialog", "包含行标题"))
        self.isIncludeColTitleCheckBox.setText(_translate("FeatureSelectorDialog", "包含列标题"))
        self.isRowMajorRadioButton.setText(_translate("FeatureSelectorDialog", "行优先"))
        self.isColMajorRadioButton.setText(_translate("FeatureSelectorDialog", "列优先"))
        self.significanceStandardLabel.setText(_translate("FeatureSelectorDialog", "显著性标准："))
        self.isCalculateVarianceCheckBox.setText(_translate("FeatureSelectorDialog", "特征方差"))
        self.isCalculatePearsonCorrCoefCheckBox.setText(_translate("FeatureSelectorDialog", "皮尔逊相关系数"))
        self.isCalculateDistanceCorrCoefCheckBox.setText(_translate("FeatureSelectorDialog", "距离相关系数"))
        self.selectOpenDataFileLabel.setText(_translate("FeatureSelectorDialog", "数据文件："))
        self.selectSaveSalientFeatureLabel.setText(_translate("FeatureSelectorDialog", "保存显著特征："))
        self.selectSaveSignificanceChartLabel.setText(_translate("FeatureSelectorDialog", "显著性图表："))
        self.selectSalientFeatureLabel.setText(_translate("FeatureSelectorDialog", "显著特征："))
        self.isSaveSignificanceInfoCheckBox.setText(_translate("FeatureSelectorDialog", "保留显著性信息"))

