# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FeatureCreatorDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from InitResource import get_icon

class Ui_FeatureCreatorDialog(object):
    def setupUi(self, FeatureCreatorDialog):
        FeatureCreatorDialog.setObjectName("FeatureCreatorDialog")
        FeatureCreatorDialog.resize(791, 488)
        self.verticalLayout = QtWidgets.QVBoxLayout(FeatureCreatorDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 10, 10, 15)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.isCalculateOneFeatureRatioQCheckBox = QtWidgets.QCheckBox(FeatureCreatorDialog)
        self.isCalculateOneFeatureRatioQCheckBox.setChecked(True)
        self.isCalculateOneFeatureRatioQCheckBox.setObjectName("isCalculateOneFeatureRatioQCheckBox")
        self.gridLayout.addWidget(self.isCalculateOneFeatureRatioQCheckBox, 4, 1, 1, 1)
        self.isMergeInitNewFeatureCheckBox = QtWidgets.QCheckBox(FeatureCreatorDialog)
        self.isMergeInitNewFeatureCheckBox.setChecked(True)
        self.isMergeInitNewFeatureCheckBox.setObjectName("isMergeInitNewFeatureCheckBox")
        self.gridLayout.addWidget(self.isMergeInitNewFeatureCheckBox, 4, 5, 1, 3)
        self.isRowMajorRadioButton = QtWidgets.QRadioButton(FeatureCreatorDialog)
        self.isRowMajorRadioButton.setChecked(False)
        self.isRowMajorRadioButton.setObjectName("isRowMajorRadioButton")
        self.gridLayout.addWidget(self.isRowMajorRadioButton, 0, 5, 1, 1)
        self.sensitiveFeatureLineEdit = QtWidgets.QLineEdit(FeatureCreatorDialog)
        self.sensitiveFeatureLineEdit.setObjectName("sensitiveFeatureLineEdit")
        self.gridLayout.addWidget(self.sensitiveFeatureLineEdit, 6, 1, 1, 8)
        self.customFeatureLabel = QtWidgets.QLabel(FeatureCreatorDialog)
        self.customFeatureLabel.setObjectName("customFeatureLabel")
        self.gridLayout.addWidget(self.customFeatureLabel, 7, 5, 1, 1)
        self.applySensitiveFeaturePushButton = QtWidgets.QPushButton(FeatureCreatorDialog)
        self.applySensitiveFeaturePushButton.setMaximumSize(QtCore.QSize(40, 35))
        self.applySensitiveFeaturePushButton.setObjectName("applySensitiveFeaturePushButton")
        self.gridLayout.addWidget(self.applySensitiveFeaturePushButton, 5, 9, 2, 1)
        self.selectSaveFeatureLabel = QtWidgets.QLabel(FeatureCreatorDialog)
        self.selectSaveFeatureLabel.setObjectName("selectSaveFeatureLabel")
        self.gridLayout.addWidget(self.selectSaveFeatureLabel, 9, 0, 1, 1)
        self.isColMajorRadioButton = QtWidgets.QRadioButton(FeatureCreatorDialog)
        self.isColMajorRadioButton.setChecked(True)
        self.isColMajorRadioButton.setObjectName("isColMajorRadioButton")
        self.gridLayout.addWidget(self.isColMajorRadioButton, 0, 7, 1, 1)
        self.selectSaveFeatureLineEdit = QtWidgets.QLineEdit(FeatureCreatorDialog)
        self.selectSaveFeatureLineEdit.setObjectName("selectSaveFeatureLineEdit")
        self.gridLayout.addWidget(self.selectSaveFeatureLineEdit, 9, 1, 1, 8)
        self.initializationFeatureLineEdit = QtWidgets.QLineEdit(FeatureCreatorDialog)
        self.initializationFeatureLineEdit.setObjectName("initializationFeatureLineEdit")
        self.gridLayout.addWidget(self.initializationFeatureLineEdit, 5, 1, 1, 8)
        self.isIncludeColTitleCheckBox = QtWidgets.QCheckBox(FeatureCreatorDialog)
        self.isIncludeColTitleCheckBox.setChecked(True)
        self.isIncludeColTitleCheckBox.setObjectName("isIncludeColTitleCheckBox")
        self.gridLayout.addWidget(self.isIncludeColTitleCheckBox, 0, 3, 1, 1)
        self.sensitiveFeatureLabel = QtWidgets.QLabel(FeatureCreatorDialog)
        self.sensitiveFeatureLabel.setObjectName("sensitiveFeatureLabel")
        self.gridLayout.addWidget(self.sensitiveFeatureLabel, 6, 0, 1, 1)
        self.selectOpenAllSamplesLineEdit = QtWidgets.QLineEdit(FeatureCreatorDialog)
        self.selectOpenAllSamplesLineEdit.setObjectName("selectOpenAllSamplesLineEdit")
        self.gridLayout.addWidget(self.selectOpenAllSamplesLineEdit, 1, 1, 1, 8)
        self.isCalculateTwoFeatureSumDifferenceRatioQCheckBox = QtWidgets.QCheckBox(FeatureCreatorDialog)
        self.isCalculateTwoFeatureSumDifferenceRatioQCheckBox.setChecked(True)
        self.isCalculateTwoFeatureSumDifferenceRatioQCheckBox.setObjectName("isCalculateTwoFeatureSumDifferenceRatioQCheckBox")
        self.gridLayout.addWidget(self.isCalculateTwoFeatureSumDifferenceRatioQCheckBox, 4, 3, 1, 1)
        self.selectSaveFeaturePushButton = QtWidgets.QPushButton(FeatureCreatorDialog)
        self.selectSaveFeaturePushButton.setText("")
        self.selectSaveFeaturePushButton.setIcon(get_icon("save_file"))
        self.selectSaveFeaturePushButton.setObjectName("selectSaveFeaturePushButton")
        self.gridLayout.addWidget(self.selectSaveFeaturePushButton, 9, 9, 1, 1)
        self.generationFeatureListWidget = QtWidgets.QListWidget(FeatureCreatorDialog)
        self.generationFeatureListWidget.setObjectName("generationFeatureTableWidget")
        self.gridLayout.addWidget(self.generationFeatureListWidget, 8, 0, 1, 5)
        self.isIncludeRowTitleCheckBox = QtWidgets.QCheckBox(FeatureCreatorDialog)
        self.isIncludeRowTitleCheckBox.setChecked(True)
        self.isIncludeRowTitleCheckBox.setObjectName("isIncludeRowTitleCheckBox")
        self.gridLayout.addWidget(self.isIncludeRowTitleCheckBox, 0, 1, 1, 1)
        self.initializationFeatureLabel = QtWidgets.QLabel(FeatureCreatorDialog)
        self.initializationFeatureLabel.setMaximumSize(QtCore.QSize(60, 50))
        self.initializationFeatureLabel.setObjectName("initializationFeatureLabel")
        self.gridLayout.addWidget(self.initializationFeatureLabel, 5, 0, 1, 1)
        self.selectOpenAllSamplesLabel = QtWidgets.QLabel(FeatureCreatorDialog)
        self.selectOpenAllSamplesLabel.setObjectName("selectOpenAllSamplesLabel")
        self.gridLayout.addWidget(self.selectOpenAllSamplesLabel, 1, 0, 1, 1)
        self.generationFeatureLabel = QtWidgets.QLabel(FeatureCreatorDialog)
        self.generationFeatureLabel.setObjectName("generationFeatureLabel")
        self.gridLayout.addWidget(self.generationFeatureLabel, 7, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 8, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 6, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_2 = QtWidgets.QFrame(FeatureCreatorDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 10)
        self.selectOpenAllSamplesPushButton = QtWidgets.QPushButton(FeatureCreatorDialog)
        self.selectOpenAllSamplesPushButton.setText("")
        self.selectOpenAllSamplesPushButton.setIcon(get_icon("open_file"))
        self.selectOpenAllSamplesPushButton.setObjectName("selectOpenAllSamplesPushButton")
        self.gridLayout.addWidget(self.selectOpenAllSamplesPushButton, 1, 9, 1, 1)
        self.customFeaturePlainTextEdit = QtWidgets.QPlainTextEdit(FeatureCreatorDialog)
        self.customFeaturePlainTextEdit.setObjectName("customFeaturePlainTextEdit")
        self.gridLayout.addWidget(self.customFeaturePlainTextEdit, 8, 5, 1, 5)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(FeatureCreatorDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.okPushButton = QtWidgets.QPushButton(FeatureCreatorDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(FeatureCreatorDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(FeatureCreatorDialog)
        QtCore.QMetaObject.connectSlotsByName(FeatureCreatorDialog)

    def retranslateUi(self, FeatureCreatorDialog):
        _translate = QtCore.QCoreApplication.translate
        FeatureCreatorDialog.setWindowTitle(_translate("FeatureCreatorDialog", "特征构建"))
        self.isCalculateOneFeatureRatioQCheckBox.setText(_translate("FeatureCreatorDialog", "单特征比值"))
        self.isMergeInitNewFeatureCheckBox.setText(_translate("FeatureCreatorDialog", "合并原始特征和生成特征"))
        self.isRowMajorRadioButton.setText(_translate("FeatureCreatorDialog", "行优先"))
        self.customFeatureLabel.setText(_translate("FeatureCreatorDialog", "自定义特征："))
        self.applySensitiveFeaturePushButton.setText(_translate("FeatureCreatorDialog", "应用"))
        self.selectSaveFeatureLabel.setText(_translate("FeatureCreatorDialog", "保存特征："))
        self.isColMajorRadioButton.setText(_translate("FeatureCreatorDialog", "列优先"))
        self.isIncludeColTitleCheckBox.setText(_translate("FeatureCreatorDialog", "包含列标题"))
        self.sensitiveFeatureLabel.setText(_translate("FeatureCreatorDialog", "敏感特征："))
        self.isCalculateTwoFeatureSumDifferenceRatioQCheckBox.setText(_translate("FeatureCreatorDialog", "双特征和差比值"))
        self.isIncludeRowTitleCheckBox.setText(_translate("FeatureCreatorDialog", "包含行标题"))
        self.initializationFeatureLabel.setText(_translate("FeatureCreatorDialog", "原始特征："))
        self.selectOpenAllSamplesLabel.setText(_translate("FeatureCreatorDialog", "样本总体："))
        self.generationFeatureLabel.setText(_translate("FeatureCreatorDialog", "生成特征："))
        self.okPushButton.setText(_translate("FeatureCreatorDialog", "确定"))
        self.cancelPushButton.setText(_translate("FeatureCreatorDialog", "取消"))

