# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GeoserverWMSPublisherDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GeoserverWMSPublisherDialog(object):
    def setupUi(self, GeoserverWMSPublisherDialog):
        GeoserverWMSPublisherDialog.setObjectName("GeoserverWMSPublisherDialog")
        GeoserverWMSPublisherDialog.resize(872, 392)
        self.verticalLayout = QtWidgets.QVBoxLayout(GeoserverWMSPublisherDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.userInfoGroupBox = QtWidgets.QGroupBox(GeoserverWMSPublisherDialog)
        self.userInfoGroupBox.setObjectName("userInfoGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.userInfoGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.userInfoGroupBox)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout_2.addWidget(self.usernameLineEdit, 0, 1, 1, 3)
        self.portLineEdit = QtWidgets.QLineEdit(self.userInfoGroupBox)
        self.portLineEdit.setObjectName("portLineEdit")
        self.gridLayout_2.addWidget(self.portLineEdit, 2, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.userInfoGroupBox)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout_2.addWidget(self.passwordLineEdit, 1, 1, 1, 3)
        self.loginPushButton = QtWidgets.QPushButton(self.userInfoGroupBox)
        self.loginPushButton.setObjectName("loginPushButton")
        self.gridLayout_2.addWidget(self.loginPushButton, 3, 2, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(self.userInfoGroupBox)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout_2.addWidget(self.passwordLabel, 1, 0, 1, 1)
        self.logoutPushButton = QtWidgets.QPushButton(self.userInfoGroupBox)
        self.logoutPushButton.setEnabled(False)
        self.logoutPushButton.setObjectName("logoutPushButton")
        self.gridLayout_2.addWidget(self.logoutPushButton, 3, 3, 1, 1)
        self.usernameLabel = QtWidgets.QLabel(self.userInfoGroupBox)
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout_2.addWidget(self.usernameLabel, 0, 0, 1, 1)
        self.portLabel = QtWidgets.QLabel(self.userInfoGroupBox)
        self.portLabel.setObjectName("portLabel")
        self.gridLayout_2.addWidget(self.portLabel, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.userInfoGroupBox)
        self.paramsSettingGroupBox = QtWidgets.QGroupBox(GeoserverWMSPublisherDialog)
        self.paramsSettingGroupBox.setObjectName("paramsSettingGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.paramsSettingGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.isCreateNewDataStoreCheckBox = QtWidgets.QCheckBox(self.paramsSettingGroupBox)
        self.isCreateNewDataStoreCheckBox.setEnabled(False)
        self.isCreateNewDataStoreCheckBox.setObjectName("isCreateNewDataStoreCheckBox")
        self.gridLayout.addWidget(self.isCreateNewDataStoreCheckBox, 3, 0, 1, 1)
        self.dataTypeLabel = QtWidgets.QLabel(self.paramsSettingGroupBox)
        self.dataTypeLabel.setObjectName("dataTypeLabel")
        self.gridLayout.addWidget(self.dataTypeLabel, 0, 0, 1, 1)
        self.rasterFileRadioButton = QtWidgets.QRadioButton(self.paramsSettingGroupBox)
        self.rasterFileRadioButton.setChecked(True)
        self.rasterFileRadioButton.setObjectName("rasterFileRadioButton")
        self.gridLayout.addWidget(self.rasterFileRadioButton, 0, 1, 1, 1)
        self.layerNameLabel = QtWidgets.QLabel(self.paramsSettingGroupBox)
        self.layerNameLabel.setObjectName("layerNameLabel")
        self.gridLayout.addWidget(self.layerNameLabel, 9, 0, 1, 1)
        self.newStyleNameLineEdit = QtWidgets.QLineEdit(self.paramsSettingGroupBox)
        self.newStyleNameLineEdit.setEnabled(False)
        self.newStyleNameLineEdit.setObjectName("newStyleNameLineEdit")
        self.gridLayout.addWidget(self.newStyleNameLineEdit, 6, 4, 1, 2)
        self.isCreateNewStyleCheckBox = QtWidgets.QCheckBox(self.paramsSettingGroupBox)
        self.isCreateNewStyleCheckBox.setObjectName("isCreateNewStyleCheckBox")
        self.gridLayout.addWidget(self.isCreateNewStyleCheckBox, 5, 0, 1, 1)
        self.styleNameLabel = QtWidgets.QLabel(self.paramsSettingGroupBox)
        self.styleNameLabel.setObjectName("styleNameLabel")
        self.gridLayout.addWidget(self.styleNameLabel, 6, 0, 1, 1)
        self.selectStyleFilePushButton = QtWidgets.QPushButton(self.paramsSettingGroupBox)
        self.selectStyleFilePushButton.setText("")
        self.selectStyleFilePushButton.setObjectName("selectStyleFilePushButton")
        self.gridLayout.addWidget(self.selectStyleFilePushButton, 8, 7, 1, 1)
        self.dataStoreLabel = QtWidgets.QLabel(self.paramsSettingGroupBox)
        self.dataStoreLabel.setEnabled(False)
        self.dataStoreLabel.setObjectName("dataStoreLabel")
        self.gridLayout.addWidget(self.dataStoreLabel, 4, 0, 1, 1)
        self.dataStoreNameComboBox = QtWidgets.QComboBox(self.paramsSettingGroupBox)
        self.dataStoreNameComboBox.setEnabled(False)
        self.dataStoreNameComboBox.setObjectName("dataStoreNameComboBox")
        self.gridLayout.addWidget(self.dataStoreNameComboBox, 4, 1, 1, 3)
        self.workspaceNameComboBox = QtWidgets.QComboBox(self.paramsSettingGroupBox)
        self.workspaceNameComboBox.setObjectName("workspaceNameComboBox")
        self.gridLayout.addWidget(self.workspaceNameComboBox, 2, 1, 1, 3)
        self.isCreateNewWorkspaceCheckBox = QtWidgets.QCheckBox(self.paramsSettingGroupBox)
        self.isCreateNewWorkspaceCheckBox.setChecked(False)
        self.isCreateNewWorkspaceCheckBox.setObjectName("isCreateNewWorkspaceCheckBox")
        self.gridLayout.addWidget(self.isCreateNewWorkspaceCheckBox, 1, 0, 1, 1)
        self.workspaceNameLabel = QtWidgets.QLabel(self.paramsSettingGroupBox)
        self.workspaceNameLabel.setObjectName("workspaceNameLabel")
        self.gridLayout.addWidget(self.workspaceNameLabel, 2, 0, 1, 1)
        self.selectDataFilePushButton = QtWidgets.QPushButton(self.paramsSettingGroupBox)
        self.selectDataFilePushButton.setText("")
        self.selectDataFilePushButton.setObjectName("selectDataFilePushButton")
        self.gridLayout.addWidget(self.selectDataFilePushButton, 7, 7, 1, 1)
        self.selectStyleFileLabel = QtWidgets.QLabel(self.paramsSettingGroupBox)
        self.selectStyleFileLabel.setObjectName("selectStyleFileLabel")
        self.gridLayout.addWidget(self.selectStyleFileLabel, 8, 0, 1, 1)
        self.selectDataFileLabel = QtWidgets.QLabel(self.paramsSettingGroupBox)
        self.selectDataFileLabel.setObjectName("selectDataFileLabel")
        self.gridLayout.addWidget(self.selectDataFileLabel, 7, 0, 1, 1)
        self.styleNameComboBox = QtWidgets.QComboBox(self.paramsSettingGroupBox)
        self.styleNameComboBox.setObjectName("styleNameComboBox")
        self.gridLayout.addWidget(self.styleNameComboBox, 6, 1, 1, 3)
        self.newWorkspaceNameLineEdit = QtWidgets.QLineEdit(self.paramsSettingGroupBox)
        self.newWorkspaceNameLineEdit.setEnabled(False)
        self.newWorkspaceNameLineEdit.setObjectName("newWorkspaceNameLineEdit")
        self.gridLayout.addWidget(self.newWorkspaceNameLineEdit, 2, 4, 1, 2)
        self.dataStoreNameLineEdit = QtWidgets.QLineEdit(self.paramsSettingGroupBox)
        self.dataStoreNameLineEdit.setEnabled(False)
        self.dataStoreNameLineEdit.setObjectName("dataStoreNameLineEdit")
        self.gridLayout.addWidget(self.dataStoreNameLineEdit, 4, 4, 1, 2)
        self.vectorFileRadioButton = QtWidgets.QRadioButton(self.paramsSettingGroupBox)
        self.vectorFileRadioButton.setObjectName("vectorFileRadioButton")
        self.gridLayout.addWidget(self.vectorFileRadioButton, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 6, 6, 1, 1)
        self.selectDataFileLineEdit = QtWidgets.QLineEdit(self.paramsSettingGroupBox)
        self.selectDataFileLineEdit.setObjectName("selectDataFileLineEdit")
        self.gridLayout.addWidget(self.selectDataFileLineEdit, 7, 1, 1, 6)
        self.selectStyleFileLineEdit = QtWidgets.QLineEdit(self.paramsSettingGroupBox)
        self.selectStyleFileLineEdit.setObjectName("selectStyleFileLineEdit")
        self.gridLayout.addWidget(self.selectStyleFileLineEdit, 8, 1, 1, 6)
        self.layerNameLineEdit = QtWidgets.QLineEdit(self.paramsSettingGroupBox)
        self.layerNameLineEdit.setObjectName("layerNameLineEdit")
        self.gridLayout.addWidget(self.layerNameLineEdit, 9, 1, 1, 6)
        self.horizontalLayout_2.addWidget(self.paramsSettingGroupBox)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.okPushButton = QtWidgets.QPushButton(GeoserverWMSPublisherDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(GeoserverWMSPublisherDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(GeoserverWMSPublisherDialog)
        QtCore.QMetaObject.connectSlotsByName(GeoserverWMSPublisherDialog)

    def retranslateUi(self, GeoserverWMSPublisherDialog):
        _translate = QtCore.QCoreApplication.translate
        GeoserverWMSPublisherDialog.setWindowTitle(_translate("GeoserverWMSPublisherDialog", "WMS服务发布"))
        self.userInfoGroupBox.setTitle(_translate("GeoserverWMSPublisherDialog", "用户信息"))
        self.loginPushButton.setText(_translate("GeoserverWMSPublisherDialog", "登录"))
        self.passwordLabel.setText(_translate("GeoserverWMSPublisherDialog", "密码："))
        self.logoutPushButton.setText(_translate("GeoserverWMSPublisherDialog", "注销"))
        self.usernameLabel.setText(_translate("GeoserverWMSPublisherDialog", "用户名："))
        self.portLabel.setText(_translate("GeoserverWMSPublisherDialog", "端口："))
        self.paramsSettingGroupBox.setTitle(_translate("GeoserverWMSPublisherDialog", "参数设置"))
        self.isCreateNewDataStoreCheckBox.setText(_translate("GeoserverWMSPublisherDialog", "创建新的数据存储"))
        self.dataTypeLabel.setText(_translate("GeoserverWMSPublisherDialog", "数据类型："))
        self.rasterFileRadioButton.setText(_translate("GeoserverWMSPublisherDialog", "栅格文件"))
        self.layerNameLabel.setText(_translate("GeoserverWMSPublisherDialog", "图层名称："))
        self.isCreateNewStyleCheckBox.setText(_translate("GeoserverWMSPublisherDialog", "创建新的样式"))
        self.styleNameLabel.setText(_translate("GeoserverWMSPublisherDialog", "样式名称："))
        self.dataStoreLabel.setText(_translate("GeoserverWMSPublisherDialog", "数据存储："))
        self.isCreateNewWorkspaceCheckBox.setText(_translate("GeoserverWMSPublisherDialog", "创建新的工作空间"))
        self.workspaceNameLabel.setText(_translate("GeoserverWMSPublisherDialog", "工作空间："))
        self.selectStyleFileLabel.setText(_translate("GeoserverWMSPublisherDialog", "样式文件："))
        self.selectDataFileLabel.setText(_translate("GeoserverWMSPublisherDialog", "数据文件："))
        self.vectorFileRadioButton.setText(_translate("GeoserverWMSPublisherDialog", "矢量文件"))
        self.okPushButton.setText(_translate("GeoserverWMSPublisherDialog", "确定"))
        self.cancelPushButton.setText(_translate("GeoserverWMSPublisherDialog", "取消"))

