# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindowDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBoxTreeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.toolBoxTreeWidget.setHeaderHidden(True)
        self.toolBoxTreeWidget.setObjectName("toolBoxTreeWidget")
        self.toolBoxTreeWidget.headerItem().setText(0, "1")
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBoxTreeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBoxTreeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBoxTreeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBoxTreeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBoxTreeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBoxTreeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBoxTreeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        self.horizontalLayout.addWidget(self.toolBoxTreeWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iPyGIRS V0.2.3"))
        __sortingEnabled = self.toolBoxTreeWidget.isSortingEnabled()
        self.toolBoxTreeWidget.setSortingEnabled(False)
        self.toolBoxTreeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "数据管理"))
        self.toolBoxTreeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "创建样本"))
        self.toolBoxTreeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "预处理"))
        self.toolBoxTreeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "归一化/标准化"))
        self.toolBoxTreeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "特征处理"))
        self.toolBoxTreeWidget.topLevelItem(0).child(2).child(0).setText(0, _translate("MainWindow", "特征构建"))
        self.toolBoxTreeWidget.topLevelItem(0).child(2).child(1).setText(0, _translate("MainWindow", "特征选择"))
        self.toolBoxTreeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "数理统计"))
        self.toolBoxTreeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "经验统计模型"))
        self.toolBoxTreeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "应用方程"))
        self.toolBoxTreeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "地理处理"))
        self.toolBoxTreeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "像元值提取"))
        self.toolBoxTreeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "栅格数据"))
        self.toolBoxTreeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "波段计算器"))
        self.toolBoxTreeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "波段分离（当前版本不可用）"))
        self.toolBoxTreeWidget.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "波段合并（当前版本不可用）"))
        self.toolBoxTreeWidget.topLevelItem(3).child(3).setText(0, _translate("MainWindow", "图像平滑（当前版本不可用）"))
        self.toolBoxTreeWidget.topLevelItem(3).child(3).child(0).setText(0, _translate("MainWindow", "移动平均平滑"))
        self.toolBoxTreeWidget.topLevelItem(3).child(4).setText(0, _translate("MainWindow", "图像融合（当前版本不可用）"))
        self.toolBoxTreeWidget.topLevelItem(3).child(4).child(0).setText(0, _translate("MainWindow", "STARFM融合"))
        self.toolBoxTreeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "机器学习"))
        self.toolBoxTreeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "scikit-learn机器学习"))
        self.toolBoxTreeWidget.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "TPOT机器学习（当前版本不可用）"))
        self.toolBoxTreeWidget.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "应用模型"))
        self.toolBoxTreeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "数据库"))
        self.toolBoxTreeWidget.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "MySQL数据库管理"))
        self.toolBoxTreeWidget.topLevelItem(6).setText(0, _translate("MainWindow", "地图服务"))
        self.toolBoxTreeWidget.topLevelItem(6).child(0).setText(0, _translate("MainWindow", "Geoserver工具"))
        self.toolBoxTreeWidget.topLevelItem(6).child(0).child(0).setText(0, _translate("MainWindow", "WMS服务发布"))
        self.toolBoxTreeWidget.setSortingEnabled(__sortingEnabled)
