# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MySQLDatabaseManagementDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MySQLDatabaseManagementDialog(object):
    def setupUi(self, MySQLDatabaseManagementDialog):
        MySQLDatabaseManagementDialog.setObjectName("MySQLDatabaseManagementDialog")
        MySQLDatabaseManagementDialog.resize(872, 810)
        self.verticalLayout = QtWidgets.QVBoxLayout(MySQLDatabaseManagementDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.databaseSettingGroupBox = QtWidgets.QGroupBox(MySQLDatabaseManagementDialog)
        self.databaseSettingGroupBox.setObjectName("databaseSettingGroupBox")
        self.databaseSettingGridLayout = QtWidgets.QGridLayout(self.databaseSettingGroupBox)
        self.databaseSettingGridLayout.setVerticalSpacing(10)
        self.databaseSettingGridLayout.setObjectName("databaseSettingGridLayout")
        self.databaseLoginPasswordLineEdit = QtWidgets.QLineEdit(self.databaseSettingGroupBox)
        self.databaseLoginPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.databaseLoginPasswordLineEdit.setObjectName("databaseLoginPasswordLineEdit")
        self.databaseSettingGridLayout.addWidget(self.databaseLoginPasswordLineEdit, 1, 1, 1, 6)
        self.dataTableLabelInfoLabel = QtWidgets.QLabel(self.databaseSettingGroupBox)
        self.dataTableLabelInfoLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dataTableLabelInfoLabel.setObjectName("dataTableLabelInfoLabel")
        self.databaseSettingGridLayout.addWidget(self.dataTableLabelInfoLabel, 5, 0, 1, 1)
        self.databaseUserNameLineEdit = QtWidgets.QLineEdit(self.databaseSettingGroupBox)
        self.databaseUserNameLineEdit.setObjectName("databaseUserNameLineEdit")
        self.databaseSettingGridLayout.addWidget(self.databaseUserNameLineEdit, 0, 1, 1, 6)
        self.databaseUserNameLabel = QtWidgets.QLabel(self.databaseSettingGroupBox)
        self.databaseUserNameLabel.setObjectName("databaseUserNameLabel")
        self.databaseSettingGridLayout.addWidget(self.databaseUserNameLabel, 0, 0, 1, 1)
        self.selectDataTableLabel = QtWidgets.QLabel(self.databaseSettingGroupBox)
        self.selectDataTableLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.selectDataTableLabel.setObjectName("selectDataTableLabel")
        self.databaseSettingGridLayout.addWidget(self.selectDataTableLabel, 4, 4, 1, 1)
        self.selectDatabaseComboBox = QtWidgets.QComboBox(self.databaseSettingGroupBox)
        self.selectDatabaseComboBox.setObjectName("selectDatabaseComboBox")
        self.databaseSettingGridLayout.addWidget(self.selectDatabaseComboBox, 4, 1, 1, 2)
        self.selectDatabaseLabel = QtWidgets.QLabel(self.databaseSettingGroupBox)
        self.selectDatabaseLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.selectDatabaseLabel.setObjectName("selectDatabaseLabel")
        self.databaseSettingGridLayout.addWidget(self.selectDatabaseLabel, 4, 0, 1, 1)
        self.databaseLoginPasswordLabel = QtWidgets.QLabel(self.databaseSettingGroupBox)
        self.databaseLoginPasswordLabel.setObjectName("databaseLoginPasswordLabel")
        self.databaseSettingGridLayout.addWidget(self.databaseLoginPasswordLabel, 1, 0, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(81, 123, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.databaseSettingGridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.selectDataTableLabelComboBox = QtWidgets.QComboBox(self.databaseSettingGroupBox)
        self.selectDataTableLabelComboBox.setObjectName("selectDataTableLabelComboBox")
        self.databaseSettingGridLayout.addWidget(self.selectDataTableLabelComboBox, 4, 5, 1, 2)
        self.connectDatabasePushButton = QtWidgets.QPushButton(self.databaseSettingGroupBox)
        self.connectDatabasePushButton.setMaximumSize(QtCore.QSize(80, 40))
        self.connectDatabasePushButton.setObjectName("connectDatabasePushButton")
        self.databaseSettingGridLayout.addWidget(self.connectDatabasePushButton, 0, 7, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.databaseSettingGridLayout.addItem(spacerItem1, 4, 3, 1, 1)
        self.dataTableInfoTreeWidget = QtWidgets.QTreeWidget(self.databaseSettingGroupBox)
        self.dataTableInfoTreeWidget.setObjectName("dataTableInfoTreeWidget")
        self.databaseSettingGridLayout.addWidget(self.dataTableInfoTreeWidget, 5, 1, 2, 6)
        self.verticalLayout.addWidget(self.databaseSettingGroupBox)
        self.geoserverSettingGroupBox = QtWidgets.QGroupBox(MySQLDatabaseManagementDialog)
        self.geoserverSettingGroupBox.setObjectName("geoserverSettingGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.geoserverSettingGroupBox)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 2, 1, 1)
        self.selectRenderLayerLabel = QtWidgets.QLabel(self.geoserverSettingGroupBox)
        self.selectRenderLayerLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.selectRenderLayerLabel.setObjectName("selectRenderLayerLabel")
        self.gridLayout_2.addWidget(self.selectRenderLayerLabel, 3, 6, 1, 1)
        self.selectWorkspaceComboBox = QtWidgets.QComboBox(self.geoserverSettingGroupBox)
        self.selectWorkspaceComboBox.setObjectName("selectWorkspaceComboBox")
        self.gridLayout_2.addWidget(self.selectWorkspaceComboBox, 3, 1, 1, 1)
        self.geoserverUserNameLabel = QtWidgets.QLabel(self.geoserverSettingGroupBox)
        self.geoserverUserNameLabel.setObjectName("geoserverUserNameLabel")
        self.gridLayout_2.addWidget(self.geoserverUserNameLabel, 0, 0, 1, 1)
        self.dataTypeLabel = QtWidgets.QLabel(self.geoserverSettingGroupBox)
        self.dataTypeLabel.setObjectName("dataTypeLabel")
        self.gridLayout_2.addWidget(self.dataTypeLabel, 2, 0, 1, 1)
        self.selectDatastoreLabel = QtWidgets.QLabel(self.geoserverSettingGroupBox)
        self.selectDatastoreLabel.setEnabled(False)
        self.selectDatastoreLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.selectDatastoreLabel.setObjectName("selectDatastoreLabel")
        self.gridLayout_2.addWidget(self.selectDatastoreLabel, 3, 3, 1, 1)
        self.selectDatastoreComboBox = QtWidgets.QComboBox(self.geoserverSettingGroupBox)
        self.selectDatastoreComboBox.setEnabled(False)
        self.selectDatastoreComboBox.setObjectName("selectDatastoreComboBox")
        self.gridLayout_2.addWidget(self.selectDatastoreComboBox, 3, 4, 1, 1)
        self.geoserverLoginPasswordLineEdit = QtWidgets.QLineEdit(self.geoserverSettingGroupBox)
        self.geoserverLoginPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.geoserverLoginPasswordLineEdit.setObjectName("geoserverLoginPasswordLineEdit")
        self.gridLayout_2.addWidget(self.geoserverLoginPasswordLineEdit, 1, 1, 1, 7)
        self.selectRenderLayerComboBox = QtWidgets.QComboBox(self.geoserverSettingGroupBox)
        self.selectRenderLayerComboBox.setObjectName("selectRenderLayerComboBox")
        self.gridLayout_2.addWidget(self.selectRenderLayerComboBox, 3, 7, 1, 1)
        self.geoserverLoginPasswordLabel = QtWidgets.QLabel(self.geoserverSettingGroupBox)
        self.geoserverLoginPasswordLabel.setObjectName("geoserverLoginPasswordLabel")
        self.gridLayout_2.addWidget(self.geoserverLoginPasswordLabel, 1, 0, 1, 1)
        self.isRasterDataRadioButton = QtWidgets.QRadioButton(self.geoserverSettingGroupBox)
        self.isRasterDataRadioButton.setChecked(True)
        self.isRasterDataRadioButton.setObjectName("isRasterDataRadioButton")
        self.gridLayout_2.addWidget(self.isRasterDataRadioButton, 2, 1, 1, 1)
        self.loginGeoserverPushButton = QtWidgets.QPushButton(self.geoserverSettingGroupBox)
        self.loginGeoserverPushButton.setMaximumSize(QtCore.QSize(80, 40))
        self.loginGeoserverPushButton.setObjectName("loginGeoserverPushButton")
        self.gridLayout_2.addWidget(self.loginGeoserverPushButton, 0, 8, 2, 1)
        self.geoserverUserNameLineEdit = QtWidgets.QLineEdit(self.geoserverSettingGroupBox)
        self.geoserverUserNameLineEdit.setObjectName("geoserverUserNameLineEdit")
        self.gridLayout_2.addWidget(self.geoserverUserNameLineEdit, 0, 1, 1, 7)
        self.selectWorkspaceLabel = QtWidgets.QLabel(self.geoserverSettingGroupBox)
        self.selectWorkspaceLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.selectWorkspaceLabel.setObjectName("selectWorkspaceLabel")
        self.gridLayout_2.addWidget(self.selectWorkspaceLabel, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 5, 1, 1)
        self.isVectorDataRadioButton = QtWidgets.QRadioButton(self.geoserverSettingGroupBox)
        self.isVectorDataRadioButton.setEnabled(False)
        self.isVectorDataRadioButton.setObjectName("isVectorDataRadioButton")
        self.gridLayout_2.addWidget(self.isVectorDataRadioButton, 2, 4, 1, 1)
        self.verticalLayout.addWidget(self.geoserverSettingGroupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dataInfoGroupBox = QtWidgets.QGroupBox(MySQLDatabaseManagementDialog)
        self.dataInfoGroupBox.setObjectName("dataInfoGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.dataInfoGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.clearFilePushButton = QtWidgets.QPushButton(self.dataInfoGroupBox)
        self.clearFilePushButton.setEnabled(False)
        self.clearFilePushButton.setText("")
        self.clearFilePushButton.setObjectName("clearFilePushButton")
        self.gridLayout.addWidget(self.clearFilePushButton, 4, 1, 1, 1)
        self.delFilePushButton = QtWidgets.QPushButton(self.dataInfoGroupBox)
        self.delFilePushButton.setEnabled(False)
        self.delFilePushButton.setText("")
        self.delFilePushButton.setObjectName("delFilePushButton")
        self.gridLayout.addWidget(self.delFilePushButton, 3, 1, 1, 1)
        self.fieldSettingTableWidget = QtWidgets.QTableWidget(self.dataInfoGroupBox)
        self.fieldSettingTableWidget.setRowCount(100)
        self.fieldSettingTableWidget.setColumnCount(50)
        self.fieldSettingTableWidget.setObjectName("fieldSettingTableWidget")
        self.gridLayout.addWidget(self.fieldSettingTableWidget, 8, 0, 1, 2)
        self.fieldSettingLabel = QtWidgets.QLabel(self.dataInfoGroupBox)
        self.fieldSettingLabel.setObjectName("fieldSettingLabel")
        self.gridLayout.addWidget(self.fieldSettingLabel, 7, 0, 1, 1)
        self.fileListWidget = QtWidgets.QListWidget(self.dataInfoGroupBox)
        self.fileListWidget.setObjectName("fileListWidget")
        self.gridLayout.addWidget(self.fileListWidget, 2, 0, 3, 1)
        self.fileListLabel = QtWidgets.QLabel(self.dataInfoGroupBox)
        self.fileListLabel.setObjectName("fileListLabel")
        self.gridLayout.addWidget(self.fileListLabel, 1, 0, 1, 1)
        self.updateDatabasePublisWMSPushButton = QtWidgets.QPushButton(self.dataInfoGroupBox)
        self.updateDatabasePublisWMSPushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.updateDatabasePublisWMSPushButton.setMaximumSize(QtCore.QSize(80, 40))
        self.updateDatabasePublisWMSPushButton.setObjectName("updateDatabasePublisWMSPushButton")
        self.gridLayout.addWidget(self.updateDatabasePublisWMSPushButton, 7, 2, 2, 1)
        self.selectFilePushButton = QtWidgets.QPushButton(self.dataInfoGroupBox)
        self.selectFilePushButton.setEnabled(False)
        self.selectFilePushButton.setText("")
        self.selectFilePushButton.setObjectName("selectFilePushButton")
        self.gridLayout.addWidget(self.selectFilePushButton, 2, 1, 1, 1)
        self.horizontalLayout.addWidget(self.dataInfoGroupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 2)

        self.retranslateUi(MySQLDatabaseManagementDialog)
        QtCore.QMetaObject.connectSlotsByName(MySQLDatabaseManagementDialog)

    def retranslateUi(self, MySQLDatabaseManagementDialog):
        _translate = QtCore.QCoreApplication.translate
        MySQLDatabaseManagementDialog.setWindowTitle(_translate("MySQLDatabaseManagementDialog", "MySQL数据库管理"))
        self.databaseSettingGroupBox.setTitle(_translate("MySQLDatabaseManagementDialog", "数据库设置"))
        self.dataTableLabelInfoLabel.setText(_translate("MySQLDatabaseManagementDialog", "数据表信息："))
        self.databaseUserNameLabel.setText(_translate("MySQLDatabaseManagementDialog", "用户名："))
        self.selectDataTableLabel.setText(_translate("MySQLDatabaseManagementDialog", "数据表："))
        self.selectDatabaseLabel.setText(_translate("MySQLDatabaseManagementDialog", "数据库："))
        self.databaseLoginPasswordLabel.setText(_translate("MySQLDatabaseManagementDialog", "密码："))
        self.connectDatabasePushButton.setText(_translate("MySQLDatabaseManagementDialog", "连接"))
        self.dataTableInfoTreeWidget.headerItem().setText(0, _translate("MySQLDatabaseManagementDialog", "字段名称"))
        self.dataTableInfoTreeWidget.headerItem().setText(1, _translate("MySQLDatabaseManagementDialog", "数据类型"))
        self.dataTableInfoTreeWidget.headerItem().setText(2, _translate("MySQLDatabaseManagementDialog", "记录数"))
        self.geoserverSettingGroupBox.setTitle(_translate("MySQLDatabaseManagementDialog", "Geoserver设置"))
        self.selectRenderLayerLabel.setText(_translate("MySQLDatabaseManagementDialog", "渲染图层："))
        self.geoserverUserNameLabel.setText(_translate("MySQLDatabaseManagementDialog", "用户名："))
        self.dataTypeLabel.setText(_translate("MySQLDatabaseManagementDialog", "数据类型："))
        self.selectDatastoreLabel.setText(_translate("MySQLDatabaseManagementDialog", "数据存储："))
        self.geoserverLoginPasswordLabel.setText(_translate("MySQLDatabaseManagementDialog", "密码："))
        self.isRasterDataRadioButton.setText(_translate("MySQLDatabaseManagementDialog", "栅格数据"))
        self.loginGeoserverPushButton.setText(_translate("MySQLDatabaseManagementDialog", "登录"))
        self.selectWorkspaceLabel.setText(_translate("MySQLDatabaseManagementDialog", "工作空间："))
        self.isVectorDataRadioButton.setText(_translate("MySQLDatabaseManagementDialog", "矢量数据"))
        self.dataInfoGroupBox.setTitle(_translate("MySQLDatabaseManagementDialog", "数据信息"))
        self.fieldSettingLabel.setText(_translate("MySQLDatabaseManagementDialog", "字段设置："))
        self.fileListLabel.setText(_translate("MySQLDatabaseManagementDialog", "文件列表："))
        self.updateDatabasePublisWMSPushButton.setText(_translate("MySQLDatabaseManagementDialog", "更新"))

