# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ScikitLearnMLDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScikitLearnMLDialog(object):
    def setupUi(self, ScikitLearnMLDialog):
        ScikitLearnMLDialog.setObjectName("ScikitLearnMLDialog")
        ScikitLearnMLDialog.resize(929, 617)
        ScikitLearnMLDialog.setStyleSheet("")
        self.topDialogVerticalLayout = QtWidgets.QVBoxLayout(ScikitLearnMLDialog)
        self.topDialogVerticalLayout.setContentsMargins(5, 10, 5, 10)
        self.topDialogVerticalLayout.setSpacing(5)
        self.topDialogVerticalLayout.setObjectName("topDialogVerticalLayout")
        self.topOperationWidgetGridLayout = QtWidgets.QGridLayout()
        self.topOperationWidgetGridLayout.setContentsMargins(-1, -1, -1, 10)
        self.topOperationWidgetGridLayout.setObjectName("topOperationWidgetGridLayout")
        self.operationTitleLabel = QtWidgets.QLabel(ScikitLearnMLDialog)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.operationTitleLabel.setFont(font)
        self.operationTitleLabel.setObjectName("operationTitleLabel")
        self.topOperationWidgetGridLayout.addWidget(self.operationTitleLabel, 0, 1, 1, 1)
        self.operationDescriptionLabel = QtWidgets.QLabel(ScikitLearnMLDialog)
        self.operationDescriptionLabel.setObjectName("operationDescriptionLabel")
        self.topOperationWidgetGridLayout.addWidget(self.operationDescriptionLabel, 1, 1, 1, 1)
        self.operationLogoLabel = QtWidgets.QLabel(ScikitLearnMLDialog)
        self.operationLogoLabel.setObjectName("operationLogoLabel")
        self.topOperationWidgetGridLayout.addWidget(self.operationLogoLabel, 0, 0, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topOperationWidgetGridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topOperationWidgetGridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.topDialogVerticalLayout.addLayout(self.topOperationWidgetGridLayout)
        self.scikitLearnSettingStackedWidget = QtWidgets.QStackedWidget(ScikitLearnMLDialog)
        self.scikitLearnSettingStackedWidget.setObjectName("scikitLearnSettingStackedWidget")
        self.selectSamplePage = QtWidgets.QWidget()
        self.selectSamplePage.setObjectName("selectSamplePage")
        self.selectSampleVerticalLayout = QtWidgets.QVBoxLayout(self.selectSamplePage)
        self.selectSampleVerticalLayout.setContentsMargins(0, 10, 0, 10)
        self.selectSampleVerticalLayout.setSpacing(5)
        self.selectSampleVerticalLayout.setObjectName("selectSampleVerticalLayout")
        self.sampleSettingGroupBox = QtWidgets.QGroupBox(self.selectSamplePage)
        self.sampleSettingGroupBox.setObjectName("sampleSettingGroupBox")
        self.sampleSettingGroupBoxGridLayout = QtWidgets.QGridLayout(self.sampleSettingGroupBox)
        self.sampleSettingGroupBoxGridLayout.setVerticalSpacing(15)
        self.sampleSettingGroupBoxGridLayout.setObjectName("sampleSettingGroupBoxGridLayout")
        self.isRowMajorRadioButton = QtWidgets.QRadioButton(self.sampleSettingGroupBox)
        self.isRowMajorRadioButton.setChecked(True)
        self.isRowMajorRadioButton.setObjectName("isRowMajorRadioButton")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.isRowMajorRadioButton, 0, 8, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sampleSettingGroupBoxGridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.isColMajorRadioButton = QtWidgets.QRadioButton(self.sampleSettingGroupBox)
        self.isColMajorRadioButton.setObjectName("isColMajorRadioButton")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.isColMajorRadioButton, 0, 10, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sampleSettingGroupBoxGridLayout.addItem(spacerItem3, 0, 7, 1, 1)
        self.selectTrainingValidationSamplePushButton = QtWidgets.QPushButton(self.sampleSettingGroupBox)
        self.selectTrainingValidationSamplePushButton.setText("")
        self.selectTrainingValidationSamplePushButton.setObjectName("selectTrainingValidationSamplePushButton")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.selectTrainingValidationSamplePushButton, 3, 12, 1, 1)
        self.selectTrainingValidationSampleLineEdit = QtWidgets.QLineEdit(self.sampleSettingGroupBox)
        self.selectTrainingValidationSampleLineEdit.setObjectName("selectTrainingValidationSampleLineEdit")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.selectTrainingValidationSampleLineEdit, 3, 1, 1, 11)
        self.isIncludeColTitleCheckBox = QtWidgets.QCheckBox(self.sampleSettingGroupBox)
        self.isIncludeColTitleCheckBox.setChecked(True)
        self.isIncludeColTitleCheckBox.setObjectName("isIncludeColTitleCheckBox")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.isIncludeColTitleCheckBox, 0, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sampleSettingGroupBoxGridLayout.addItem(spacerItem4, 0, 9, 1, 1)
        self.isIncludeRowTitleCheckBox = QtWidgets.QCheckBox(self.sampleSettingGroupBox)
        self.isIncludeRowTitleCheckBox.setChecked(True)
        self.isIncludeRowTitleCheckBox.setObjectName("isIncludeRowTitleCheckBox")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.isIncludeRowTitleCheckBox, 0, 1, 1, 1)
        self.sampleTypeLabel = QtWidgets.QLabel(self.sampleSettingGroupBox)
        self.sampleTypeLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sampleTypeLabel.setObjectName("sampleTypeLabel")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.sampleTypeLabel, 0, 0, 1, 1)
        self.selectTrainingValidationSampleLabel = QtWidgets.QLabel(self.sampleSettingGroupBox)
        self.selectTrainingValidationSampleLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.selectTrainingValidationSampleLabel.setObjectName("selectTrainingValidationSampleLabel")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.selectTrainingValidationSampleLabel, 3, 0, 1, 1)
        self.selectTestSamplePushButton = QtWidgets.QPushButton(self.sampleSettingGroupBox)
        self.selectTestSamplePushButton.setText("")
        self.selectTestSamplePushButton.setObjectName("selectTestSamplePushButton")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.selectTestSamplePushButton, 4, 12, 1, 1)
        self.selectTestSampleLabel = QtWidgets.QLabel(self.sampleSettingGroupBox)
        self.selectTestSampleLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.selectTestSampleLabel.setObjectName("selectTestSampleLabel")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.selectTestSampleLabel, 4, 0, 1, 1)
        self.selectTestSampleLineEdit = QtWidgets.QLineEdit(self.sampleSettingGroupBox)
        self.selectTestSampleLineEdit.setObjectName("selectTestSampleLineEdit")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.selectTestSampleLineEdit, 4, 1, 1, 11)
        self.isIncludeLabelCheckBox = QtWidgets.QCheckBox(self.sampleSettingGroupBox)
        self.isIncludeLabelCheckBox.setChecked(True)
        self.isIncludeLabelCheckBox.setObjectName("isIncludeLabelCheckBox")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.isIncludeLabelCheckBox, 0, 6, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sampleSettingGroupBoxGridLayout.addItem(spacerItem5, 0, 5, 1, 1)
        self.selectSampleVerticalLayout.addWidget(self.sampleSettingGroupBox)
        self.frame = QtWidgets.QFrame(self.selectSamplePage)
        self.frame.setStyleSheet("background-color:white")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sampleStatisticChartGridLayout = QtWidgets.QGridLayout()
        self.sampleStatisticChartGridLayout.setObjectName("sampleStatisticChartGridLayout")
        self.horizontalLayout.addLayout(self.sampleStatisticChartGridLayout)
        self.selectSampleVerticalLayout.addWidget(self.frame)
        self.selectSampleVerticalLayout.setStretch(1, 1)
        self.scikitLearnSettingStackedWidget.addWidget(self.selectSamplePage)
        self.setParameterPage = QtWidgets.QWidget()
        self.setParameterPage.setObjectName("setParameterPage")
        self.setParameterVerticalLayout = QtWidgets.QVBoxLayout(self.setParameterPage)
        self.setParameterVerticalLayout.setContentsMargins(0, 10, 0, 10)
        self.setParameterVerticalLayout.setSpacing(5)
        self.setParameterVerticalLayout.setObjectName("setParameterVerticalLayout")
        self.scikitLearnSettingGroupBox = QtWidgets.QGroupBox(self.setParameterPage)
        self.scikitLearnSettingGroupBox.setTitle("")
        self.scikitLearnSettingGroupBox.setObjectName("scikitLearnSettingGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.scikitLearnSettingGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.selectParameterTypeLabel = QtWidgets.QLabel(self.scikitLearnSettingGroupBox)
        self.selectParameterTypeLabel.setObjectName("selectParameterTypeLabel")
        self.gridLayout.addWidget(self.selectParameterTypeLabel, 0, 6, 1, 1)
        self.selectParameterTypeComboBox = QtWidgets.QComboBox(self.scikitLearnSettingGroupBox)
        self.selectParameterTypeComboBox.setMinimumSize(QtCore.QSize(85, 0))
        self.selectParameterTypeComboBox.setObjectName("selectParameterTypeComboBox")
        self.selectParameterTypeComboBox.addItem("")
        self.selectParameterTypeComboBox.addItem("")
        self.selectParameterTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.selectParameterTypeComboBox, 0, 7, 1, 1)
        self.selectEstimatorComboBox = QtWidgets.QComboBox(self.scikitLearnSettingGroupBox)
        self.selectEstimatorComboBox.setMinimumSize(QtCore.QSize(85, 0))
        self.selectEstimatorComboBox.setObjectName("selectEstimatorComboBox")
        self.selectEstimatorComboBox.addItem("")
        self.selectEstimatorComboBox.addItem("")
        self.selectEstimatorComboBox.addItem("")
        self.selectEstimatorComboBox.addItem("")
        self.selectEstimatorComboBox.addItem("")
        self.selectEstimatorComboBox.addItem("")
        self.selectEstimatorComboBox.addItem("")
        self.selectEstimatorComboBox.addItem("")
        self.gridLayout.addWidget(self.selectEstimatorComboBox, 0, 4, 1, 1)
        self.saveParameterToFilePushButton = QtWidgets.QPushButton(self.scikitLearnSettingGroupBox)
        self.saveParameterToFilePushButton.setText("")
        self.saveParameterToFilePushButton.setObjectName("saveParameterToFilePushButton")
        self.gridLayout.addWidget(self.saveParameterToFilePushButton, 0, 10, 1, 1)
        self.selectTaskTypeComboBox = QtWidgets.QComboBox(self.scikitLearnSettingGroupBox)
        self.selectTaskTypeComboBox.setMinimumSize(QtCore.QSize(85, 0))
        self.selectTaskTypeComboBox.setObjectName("selectTaskTypeComboBox")
        self.selectTaskTypeComboBox.addItem("")
        self.selectTaskTypeComboBox.addItem("")
        self.selectTaskTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.selectTaskTypeComboBox, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 2, 1, 1)
        self.selectEstimatorLabel = QtWidgets.QLabel(self.scikitLearnSettingGroupBox)
        self.selectEstimatorLabel.setMaximumSize(QtCore.QSize(60, 25))
        self.selectEstimatorLabel.setObjectName("selectEstimatorLabel")
        self.gridLayout.addWidget(self.selectEstimatorLabel, 0, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 8, 1, 1)
        self.importParameterFromFilePushButton = QtWidgets.QPushButton(self.scikitLearnSettingGroupBox)
        self.importParameterFromFilePushButton.setEnabled(False)
        self.importParameterFromFilePushButton.setText("")
        self.importParameterFromFilePushButton.setObjectName("importParameterFromFilePushButton")
        self.gridLayout.addWidget(self.importParameterFromFilePushButton, 0, 9, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 0, 5, 1, 1)
        self.selectTaskTypeLabel = QtWidgets.QLabel(self.scikitLearnSettingGroupBox)
        self.selectTaskTypeLabel.setObjectName("selectTaskTypeLabel")
        self.gridLayout.addWidget(self.selectTaskTypeLabel, 0, 0, 1, 1)
        self.setParameterVerticalLayout.addWidget(self.scikitLearnSettingGroupBox)
        self.basicParameterVerticalLayout = QtWidgets.QVBoxLayout()
        self.basicParameterVerticalLayout.setContentsMargins(-1, 5, -1, -1)
        self.basicParameterVerticalLayout.setObjectName("basicParameterVerticalLayout")
        self.basicParameterLabel = QtWidgets.QLabel(self.setParameterPage)
        self.basicParameterLabel.setObjectName("basicParameterLabel")
        self.basicParameterVerticalLayout.addWidget(self.basicParameterLabel)
        self.basicParameterTableWidget = QtWidgets.QTableWidget(self.setParameterPage)
        self.basicParameterTableWidget.setRowCount(50)
        self.basicParameterTableWidget.setObjectName("basicParameterTableWidget")
        self.basicParameterTableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.basicParameterTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.basicParameterTableWidget.setHorizontalHeaderItem(1, item)
        self.basicParameterTableWidget.horizontalHeader().setStretchLastSection(True)
        self.basicParameterTableWidget.verticalHeader().setVisible(False)
        self.basicParameterVerticalLayout.addWidget(self.basicParameterTableWidget)
        self.setParameterVerticalLayout.addLayout(self.basicParameterVerticalLayout)
        self.scikitLearnSettingStackedWidget.addWidget(self.setParameterPage)
        self.trainEstimatorPage = QtWidgets.QWidget()
        self.trainEstimatorPage.setObjectName("trainEstimatorPage")
        self.trainModelHorizontalLayout = QtWidgets.QHBoxLayout(self.trainEstimatorPage)
        self.trainModelHorizontalLayout.setContentsMargins(0, 10, 0, 10)
        self.trainModelHorizontalLayout.setSpacing(5)
        self.trainModelHorizontalLayout.setObjectName("trainModelHorizontalLayout")
        self.preTrainingEstimatorInfoGroupBox = QtWidgets.QGroupBox(self.trainEstimatorPage)
        self.preTrainingEstimatorInfoGroupBox.setObjectName("preTrainingEstimatorInfoGroupBox")
        self.initModelTrainingInfoHorizontalLayout = QtWidgets.QHBoxLayout(self.preTrainingEstimatorInfoGroupBox)
        self.initModelTrainingInfoHorizontalLayout.setObjectName("initModelTrainingInfoHorizontalLayout")
        self.preTrainingEstimatorInfoTextBrowser = QtWidgets.QTextBrowser(self.preTrainingEstimatorInfoGroupBox)
        self.preTrainingEstimatorInfoTextBrowser.setStyleSheet("background:rgb(240,240,240)")
        self.preTrainingEstimatorInfoTextBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.preTrainingEstimatorInfoTextBrowser.setObjectName("preTrainingEstimatorInfoTextBrowser")
        self.initModelTrainingInfoHorizontalLayout.addWidget(self.preTrainingEstimatorInfoTextBrowser)
        self.trainModelHorizontalLayout.addWidget(self.preTrainingEstimatorInfoGroupBox)
        self.trainEstimatorVerticalLayout = QtWidgets.QVBoxLayout()
        self.trainEstimatorVerticalLayout.setObjectName("trainEstimatorVerticalLayout")
        self.trainEstimatorGroupBox = QtWidgets.QGroupBox(self.trainEstimatorPage)
        self.trainEstimatorGroupBox.setObjectName("trainEstimatorGroupBox")
        self.trainEstimatorGridLayout = QtWidgets.QGridLayout(self.trainEstimatorGroupBox)
        self.trainEstimatorGridLayout.setObjectName("trainEstimatorGridLayout")
        self.trainEstimatorPushButton = QtWidgets.QPushButton(self.trainEstimatorGroupBox)
        self.trainEstimatorPushButton.setObjectName("trainEstimatorPushButton")
        self.trainEstimatorGridLayout.addWidget(self.trainEstimatorPushButton, 1, 3, 1, 1)
        self.kFoldCVLabel = QtWidgets.QLabel(self.trainEstimatorGroupBox)
        self.kFoldCVLabel.setObjectName("kFoldCVLabel")
        self.trainEstimatorGridLayout.addWidget(self.kFoldCVLabel, 0, 0, 1, 1)
        self.kFoldCVLineEdit = QtWidgets.QLineEdit(self.trainEstimatorGroupBox)
        self.kFoldCVLineEdit.setObjectName("kFoldCVLineEdit")
        self.trainEstimatorGridLayout.addWidget(self.kFoldCVLineEdit, 0, 1, 1, 1)
        self.nJobsComboBox = QtWidgets.QComboBox(self.trainEstimatorGroupBox)
        self.nJobsComboBox.setObjectName("nJobsComboBox")
        self.trainEstimatorGridLayout.addWidget(self.nJobsComboBox, 2, 1, 1, 1)
        self.nJobsLabel = QtWidgets.QLabel(self.trainEstimatorGroupBox)
        self.nJobsLabel.setObjectName("nJobsLabel")
        self.trainEstimatorGridLayout.addWidget(self.nJobsLabel, 2, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.trainEstimatorGridLayout.addItem(spacerItem9, 1, 2, 1, 1)
        self.trainEstimatorVerticalLayout.addWidget(self.trainEstimatorGroupBox)
        self.trainingCVTestResultGroupBox = QtWidgets.QGroupBox(self.trainEstimatorPage)
        self.trainingCVTestResultGroupBox.setObjectName("trainingCVTestResultGroupBox")
        self.trainingCVTestResultGroupBoxGridLayout = QtWidgets.QGridLayout(self.trainingCVTestResultGroupBox)
        self.trainingCVTestResultGroupBoxGridLayout.setObjectName("trainingCVTestResultGroupBoxGridLayout")
        self.trainingScore_1Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.trainingScore_1Label.setObjectName("trainingScore_1Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.trainingScore_1Label, 2, 2, 1, 1)
        self.testScore_1Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.testScore_1Label.setObjectName("testScore_1Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.testScore_1Label, 4, 2, 1, 1)
        self.cvScore_2Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.cvScore_2Label.setObjectName("cvScore_2Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.cvScore_2Label, 3, 3, 1, 1)
        self.testScore_2Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.testScore_2Label.setObjectName("testScore_2Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.testScore_2Label, 4, 3, 1, 1)
        self.sampleCountLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.sampleCountLabel.setObjectName("sampleCountLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.sampleCountLabel, 0, 1, 1, 1)
        self.testSampleCountLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.testSampleCountLabel.setObjectName("testSampleCountLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.testSampleCountLabel, 4, 1, 1, 1)
        self.cvResultLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.cvResultLabel.setObjectName("cvResultLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.cvResultLabel, 3, 0, 1, 1)
        self.estimatorEvaluationChartPushButton = QtWidgets.QPushButton(self.trainingCVTestResultGroupBox)
        self.estimatorEvaluationChartPushButton.setEnabled(False)
        self.estimatorEvaluationChartPushButton.setObjectName("estimatorEvaluationChartPushButton")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.estimatorEvaluationChartPushButton, 6, 3, 1, 1)
        self.trainingScore_2Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.trainingScore_2Label.setObjectName("trainingScore_2Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.trainingScore_2Label, 2, 3, 1, 1)
        self.trainingCrossValidationTestResultGroupBoxLine = QtWidgets.QFrame(self.trainingCVTestResultGroupBox)
        self.trainingCrossValidationTestResultGroupBoxLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.trainingCrossValidationTestResultGroupBoxLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.trainingCrossValidationTestResultGroupBoxLine.setObjectName("trainingCrossValidationTestResultGroupBoxLine")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.trainingCrossValidationTestResultGroupBoxLine, 5, 0, 1, 4)
        self.estimatorScore_1Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.estimatorScore_1Label.setObjectName("estimatorScore_1Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.estimatorScore_1Label, 0, 2, 1, 1)
        self.cvScore_1Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.cvScore_1Label.setObjectName("cvScore_1Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.cvScore_1Label, 3, 2, 1, 1)
        self.testResultLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.testResultLabel.setObjectName("testResultLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.testResultLabel, 4, 0, 1, 1)
        self.trainingResultLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.trainingResultLabel.setObjectName("trainingResultLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.trainingResultLabel, 2, 0, 1, 1)
        self.estimatorScore_2Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.estimatorScore_2Label.setObjectName("estimatorScore_2Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.estimatorScore_2Label, 0, 3, 1, 1)
        self.estimatorLearningCurveChartPushButton = QtWidgets.QPushButton(self.trainingCVTestResultGroupBox)
        self.estimatorLearningCurveChartPushButton.setEnabled(False)
        self.estimatorLearningCurveChartPushButton.setObjectName("estimatorLearningCurveChartPushButton")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.estimatorLearningCurveChartPushButton, 6, 2, 1, 1)
        self.trainingSampleCountLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.trainingSampleCountLabel.setObjectName("trainingSampleCountLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.trainingSampleCountLabel, 2, 1, 1, 1)
        self.cvSampleCountLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.cvSampleCountLabel.setObjectName("cvSampleCountLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.cvSampleCountLabel, 3, 1, 1, 1)
        self.trainEstimatorVerticalLayout.addWidget(self.trainingCVTestResultGroupBox)
        self.trainModelHorizontalLayout.addLayout(self.trainEstimatorVerticalLayout)
        self.scikitLearnSettingStackedWidget.addWidget(self.trainEstimatorPage)
        self.saveEstimatorDataPage = QtWidgets.QWidget()
        self.saveEstimatorDataPage.setObjectName("saveEstimatorDataPage")
        self.saveModelHorizontalLayout = QtWidgets.QHBoxLayout(self.saveEstimatorDataPage)
        self.saveModelHorizontalLayout.setContentsMargins(0, 10, 0, 10)
        self.saveModelHorizontalLayout.setSpacing(5)
        self.saveModelHorizontalLayout.setObjectName("saveModelHorizontalLayout")
        self.saveEstimatorDataGroupBox = QtWidgets.QGroupBox(self.saveEstimatorDataPage)
        self.saveEstimatorDataGroupBox.setTitle("")
        self.saveEstimatorDataGroupBox.setObjectName("saveEstimatorDataGroupBox")
        self.saveModelDataGroupBoxVerticalLayout = QtWidgets.QVBoxLayout(self.saveEstimatorDataGroupBox)
        self.saveModelDataGroupBoxVerticalLayout.setObjectName("saveModelDataGroupBoxVerticalLayout")
        self.saveEstimatorDataFormLayout = QtWidgets.QFormLayout()
        self.saveEstimatorDataFormLayout.setObjectName("saveEstimatorDataFormLayout")
        self.isSaveBestEstimatorToFileCheckBox = QtWidgets.QCheckBox(self.saveEstimatorDataGroupBox)
        self.isSaveBestEstimatorToFileCheckBox.setChecked(True)
        self.isSaveBestEstimatorToFileCheckBox.setObjectName("isSaveBestEstimatorToFileCheckBox")
        self.saveEstimatorDataFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.isSaveBestEstimatorToFileCheckBox)
        self.isSaveBestEstimatorToFileLineEdit = QtWidgets.QLineEdit(self.saveEstimatorDataGroupBox)
        self.isSaveBestEstimatorToFileLineEdit.setObjectName("isSaveBestEstimatorToFileLineEdit")
        self.saveEstimatorDataFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.isSaveBestEstimatorToFileLineEdit)
        self.isSaveEstimatorDataToExcelFileNameCheckBox = QtWidgets.QCheckBox(self.saveEstimatorDataGroupBox)
        self.isSaveEstimatorDataToExcelFileNameCheckBox.setChecked(True)
        self.isSaveEstimatorDataToExcelFileNameCheckBox.setObjectName("isSaveEstimatorDataToExcelFileNameCheckBox")
        self.saveEstimatorDataFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.isSaveEstimatorDataToExcelFileNameCheckBox)
        self.isSaveEstimatorDataToExcelFileNameLineEdit = QtWidgets.QLineEdit(self.saveEstimatorDataGroupBox)
        self.isSaveEstimatorDataToExcelFileNameLineEdit.setObjectName("isSaveEstimatorDataToExcelFileNameLineEdit")
        self.saveEstimatorDataFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.isSaveEstimatorDataToExcelFileNameLineEdit)
        self.isSaveTrainingDataToWorkingSheetNameCheckBox = QtWidgets.QCheckBox(self.saveEstimatorDataGroupBox)
        self.isSaveTrainingDataToWorkingSheetNameCheckBox.setChecked(True)
        self.isSaveTrainingDataToWorkingSheetNameCheckBox.setObjectName("isSaveTrainingDataToWorkingSheetNameCheckBox")
        self.saveEstimatorDataFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.isSaveTrainingDataToWorkingSheetNameCheckBox)
        self.isSaveTrainingDataToWorkingSheetNameLineEdit = QtWidgets.QLineEdit(self.saveEstimatorDataGroupBox)
        self.isSaveTrainingDataToWorkingSheetNameLineEdit.setObjectName("isSaveTrainingDataToWorkingSheetNameLineEdit")
        self.saveEstimatorDataFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.isSaveTrainingDataToWorkingSheetNameLineEdit)
        self.isSaveCVDataToWorkingSheetNameCheckBox = QtWidgets.QCheckBox(self.saveEstimatorDataGroupBox)
        self.isSaveCVDataToWorkingSheetNameCheckBox.setEnabled(False)
        self.isSaveCVDataToWorkingSheetNameCheckBox.setChecked(False)
        self.isSaveCVDataToWorkingSheetNameCheckBox.setObjectName("isSaveCVDataToWorkingSheetNameCheckBox")
        self.saveEstimatorDataFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.isSaveCVDataToWorkingSheetNameCheckBox)
        self.isSaveCVDataToWorkingSheetNameLineEdit = QtWidgets.QLineEdit(self.saveEstimatorDataGroupBox)
        self.isSaveCVDataToWorkingSheetNameLineEdit.setEnabled(False)
        self.isSaveCVDataToWorkingSheetNameLineEdit.setObjectName("isSaveCVDataToWorkingSheetNameLineEdit")
        self.saveEstimatorDataFormLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.isSaveCVDataToWorkingSheetNameLineEdit)
        self.isSaveTestDataToWorkingSheetNameCheckBox = QtWidgets.QCheckBox(self.saveEstimatorDataGroupBox)
        self.isSaveTestDataToWorkingSheetNameCheckBox.setEnabled(False)
        self.isSaveTestDataToWorkingSheetNameCheckBox.setChecked(False)
        self.isSaveTestDataToWorkingSheetNameCheckBox.setObjectName("isSaveTestDataToWorkingSheetNameCheckBox")
        self.saveEstimatorDataFormLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.isSaveTestDataToWorkingSheetNameCheckBox)
        self.isSaveTestDataToWorkingSheetNameLineEdit = QtWidgets.QLineEdit(self.saveEstimatorDataGroupBox)
        self.isSaveTestDataToWorkingSheetNameLineEdit.setEnabled(False)
        self.isSaveTestDataToWorkingSheetNameLineEdit.setObjectName("isSaveTestDataToWorkingSheetNameLineEdit")
        self.saveEstimatorDataFormLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.isSaveTestDataToWorkingSheetNameLineEdit)
        self.saveModelDataGroupBoxVerticalLayout.addLayout(self.saveEstimatorDataFormLayout)
        self.saveEstimatorDataGroupBoxVerticalLayoutLine = QtWidgets.QFrame(self.saveEstimatorDataGroupBox)
        self.saveEstimatorDataGroupBoxVerticalLayoutLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.saveEstimatorDataGroupBoxVerticalLayoutLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.saveEstimatorDataGroupBoxVerticalLayoutLine.setObjectName("saveEstimatorDataGroupBoxVerticalLayoutLine")
        self.saveModelDataGroupBoxVerticalLayout.addWidget(self.saveEstimatorDataGroupBoxVerticalLayoutLine)
        self.saveModelDataHorizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.saveModelDataHorizontalLayout_1.setObjectName("saveModelDataHorizontalLayout_1")
        self.selectEstimatorDataSaveDirectoryLabel = QtWidgets.QLabel(self.saveEstimatorDataGroupBox)
        self.selectEstimatorDataSaveDirectoryLabel.setObjectName("selectEstimatorDataSaveDirectoryLabel")
        self.saveModelDataHorizontalLayout_1.addWidget(self.selectEstimatorDataSaveDirectoryLabel)
        self.selectEstimatorDataSaveDirectoryLineEdit = QtWidgets.QLineEdit(self.saveEstimatorDataGroupBox)
        self.selectEstimatorDataSaveDirectoryLineEdit.setObjectName("selectEstimatorDataSaveDirectoryLineEdit")
        self.saveModelDataHorizontalLayout_1.addWidget(self.selectEstimatorDataSaveDirectoryLineEdit)
        self.selectEstimatorDataSaveDirectoryPushButton = QtWidgets.QPushButton(self.saveEstimatorDataGroupBox)
        self.selectEstimatorDataSaveDirectoryPushButton.setText("")
        self.selectEstimatorDataSaveDirectoryPushButton.setObjectName("selectEstimatorDataSaveDirectoryPushButton")
        self.saveModelDataHorizontalLayout_1.addWidget(self.selectEstimatorDataSaveDirectoryPushButton)
        self.saveModelDataGroupBoxVerticalLayout.addLayout(self.saveModelDataHorizontalLayout_1)
        self.saveEstimatorDataHorizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.saveEstimatorDataHorizontalLayout_2.setObjectName("saveEstimatorDataHorizontalLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.saveEstimatorDataHorizontalLayout_2.addItem(spacerItem10)
        self.resetSaveParameterPushButton = QtWidgets.QPushButton(self.saveEstimatorDataGroupBox)
        self.resetSaveParameterPushButton.setObjectName("resetSaveParameterPushButton")
        self.saveEstimatorDataHorizontalLayout_2.addWidget(self.resetSaveParameterPushButton)
        self.saveEstimatorDataPushButton = QtWidgets.QPushButton(self.saveEstimatorDataGroupBox)
        self.saveEstimatorDataPushButton.setObjectName("saveEstimatorDataPushButton")
        self.saveEstimatorDataHorizontalLayout_2.addWidget(self.saveEstimatorDataPushButton)
        self.saveModelDataGroupBoxVerticalLayout.addLayout(self.saveEstimatorDataHorizontalLayout_2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.saveModelDataGroupBoxVerticalLayout.addItem(spacerItem11)
        self.saveModelHorizontalLayout.addWidget(self.saveEstimatorDataGroupBox)
        self.scikitLearnSettingStackedWidget.addWidget(self.saveEstimatorDataPage)
        self.topDialogVerticalLayout.addWidget(self.scikitLearnSettingStackedWidget)
        self.bottomOperationWidgetHorizontalLayout = QtWidgets.QHBoxLayout()
        self.bottomOperationWidgetHorizontalLayout.setContentsMargins(-1, 15, -1, -1)
        self.bottomOperationWidgetHorizontalLayout.setObjectName("bottomOperationWidgetHorizontalLayout")
        self.stepLogoLabel = QtWidgets.QLabel(ScikitLearnMLDialog)
        self.stepLogoLabel.setObjectName("stepLogoLabel")
        self.bottomOperationWidgetHorizontalLayout.addWidget(self.stepLogoLabel)
        self.stepTipLabel = QtWidgets.QLabel(ScikitLearnMLDialog)
        self.stepTipLabel.setObjectName("stepTipLabel")
        self.bottomOperationWidgetHorizontalLayout.addWidget(self.stepTipLabel)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomOperationWidgetHorizontalLayout.addItem(spacerItem12)
        self.previousStepPushButton = QtWidgets.QPushButton(ScikitLearnMLDialog)
        self.previousStepPushButton.setEnabled(False)
        self.previousStepPushButton.setObjectName("previousStepPushButton")
        self.bottomOperationWidgetHorizontalLayout.addWidget(self.previousStepPushButton)
        self.nextStepPushButton = QtWidgets.QPushButton(ScikitLearnMLDialog)
        self.nextStepPushButton.setObjectName("nextStepPushButton")
        self.bottomOperationWidgetHorizontalLayout.addWidget(self.nextStepPushButton)
        self.cancelFinishPushButton = QtWidgets.QPushButton(ScikitLearnMLDialog)
        self.cancelFinishPushButton.setObjectName("cancelFinishPushButton")
        self.bottomOperationWidgetHorizontalLayout.addWidget(self.cancelFinishPushButton)
        self.topDialogVerticalLayout.addLayout(self.bottomOperationWidgetHorizontalLayout)

        self.retranslateUi(ScikitLearnMLDialog)
        self.scikitLearnSettingStackedWidget.setCurrentIndex(0)
        self.selectEstimatorComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ScikitLearnMLDialog)

    def retranslateUi(self, ScikitLearnMLDialog):
        _translate = QtCore.QCoreApplication.translate
        ScikitLearnMLDialog.setWindowTitle(_translate("ScikitLearnMLDialog", "scikit-learn机器学习"))
        self.operationTitleLabel.setText(_translate("ScikitLearnMLDialog", "选择样本"))
        self.operationDescriptionLabel.setText(_translate("ScikitLearnMLDialog", "选择训练模型所用的样本数据"))
        self.operationLogoLabel.setText(_translate("ScikitLearnMLDialog", "TextLabel"))
        self.sampleSettingGroupBox.setTitle(_translate("ScikitLearnMLDialog", "样本设置"))
        self.isRowMajorRadioButton.setText(_translate("ScikitLearnMLDialog", "行优先"))
        self.isColMajorRadioButton.setText(_translate("ScikitLearnMLDialog", "列优先"))
        self.isIncludeColTitleCheckBox.setText(_translate("ScikitLearnMLDialog", "包含列标题"))
        self.isIncludeRowTitleCheckBox.setText(_translate("ScikitLearnMLDialog", "包含行标题"))
        self.sampleTypeLabel.setText(_translate("ScikitLearnMLDialog", "样本文件类型："))
        self.selectTrainingValidationSampleLabel.setText(_translate("ScikitLearnMLDialog", "训练-验证样本："))
        self.selectTestSampleLabel.setText(_translate("ScikitLearnMLDialog", "测试样本（可选）："))
        self.isIncludeLabelCheckBox.setText(_translate("ScikitLearnMLDialog", "包含标签"))
        self.selectParameterTypeLabel.setText(_translate("ScikitLearnMLDialog", "参数类型："))
        self.selectParameterTypeComboBox.setItemText(0, _translate("ScikitLearnMLDialog", "默认参数"))
        self.selectParameterTypeComboBox.setItemText(1, _translate("ScikitLearnMLDialog", "调试参数"))
        self.selectParameterTypeComboBox.setItemText(2, _translate("ScikitLearnMLDialog", "本地文件"))
        self.selectEstimatorComboBox.setItemText(0, _translate("ScikitLearnMLDialog", "线性回归"))
        self.selectEstimatorComboBox.setItemText(1, _translate("ScikitLearnMLDialog", "岭回归"))
        self.selectEstimatorComboBox.setItemText(2, _translate("ScikitLearnMLDialog", "套索回归"))
        self.selectEstimatorComboBox.setItemText(3, _translate("ScikitLearnMLDialog", "支持向量机"))
        self.selectEstimatorComboBox.setItemText(4, _translate("ScikitLearnMLDialog", "神经网络"))
        self.selectEstimatorComboBox.setItemText(5, _translate("ScikitLearnMLDialog", "决策树"))
        self.selectEstimatorComboBox.setItemText(6, _translate("ScikitLearnMLDialog", "随机森林"))
        self.selectEstimatorComboBox.setItemText(7, _translate("ScikitLearnMLDialog", "提度提升树"))
        self.selectTaskTypeComboBox.setItemText(0, _translate("ScikitLearnMLDialog", "回归"))
        self.selectTaskTypeComboBox.setItemText(1, _translate("ScikitLearnMLDialog", "分类"))
        self.selectTaskTypeComboBox.setItemText(2, _translate("ScikitLearnMLDialog", "聚类"))
        self.selectEstimatorLabel.setText(_translate("ScikitLearnMLDialog", "学习器："))
        self.selectTaskTypeLabel.setText(_translate("ScikitLearnMLDialog", "任务类型："))
        self.basicParameterLabel.setText(_translate("ScikitLearnMLDialog", "基本参数："))
        item = self.basicParameterTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ScikitLearnMLDialog", "参数名称"))
        item = self.basicParameterTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ScikitLearnMLDialog", "参数取值"))
        self.preTrainingEstimatorInfoGroupBox.setTitle(_translate("ScikitLearnMLDialog", "预训练模型信息"))
        self.trainEstimatorGroupBox.setTitle(_translate("ScikitLearnMLDialog", "训练模型"))
        self.trainEstimatorPushButton.setText(_translate("ScikitLearnMLDialog", "训练"))
        self.kFoldCVLabel.setText(_translate("ScikitLearnMLDialog", "交叉验证（K）："))
        self.kFoldCVLineEdit.setText(_translate("ScikitLearnMLDialog", "5"))
        self.nJobsLabel.setText(_translate("ScikitLearnMLDialog", "工作核心数："))
        self.trainingCVTestResultGroupBox.setTitle(_translate("ScikitLearnMLDialog", "结果"))
        self.trainingScore_1Label.setText(_translate("ScikitLearnMLDialog", "-"))
        self.testScore_1Label.setText(_translate("ScikitLearnMLDialog", "-"))
        self.cvScore_2Label.setText(_translate("ScikitLearnMLDialog", "-"))
        self.testScore_2Label.setText(_translate("ScikitLearnMLDialog", "-"))
        self.sampleCountLabel.setText(_translate("ScikitLearnMLDialog", "样本数"))
        self.testSampleCountLabel.setText(_translate("ScikitLearnMLDialog", "-"))
        self.cvResultLabel.setText(_translate("ScikitLearnMLDialog", "验证："))
        self.estimatorEvaluationChartPushButton.setText(_translate("ScikitLearnMLDialog", "模型评估图表"))
        self.trainingScore_2Label.setText(_translate("ScikitLearnMLDialog", "-"))
        self.estimatorScore_1Label.setText(_translate("ScikitLearnMLDialog", "R2"))
        self.cvScore_1Label.setText(_translate("ScikitLearnMLDialog", "-"))
        self.testResultLabel.setText(_translate("ScikitLearnMLDialog", "测试："))
        self.trainingResultLabel.setText(_translate("ScikitLearnMLDialog", "训练："))
        self.estimatorScore_2Label.setText(_translate("ScikitLearnMLDialog", "MSE"))
        self.estimatorLearningCurveChartPushButton.setText(_translate("ScikitLearnMLDialog", "学习曲线图表"))
        self.trainingSampleCountLabel.setText(_translate("ScikitLearnMLDialog", "-"))
        self.cvSampleCountLabel.setText(_translate("ScikitLearnMLDialog", "-"))
        self.isSaveBestEstimatorToFileCheckBox.setText(_translate("ScikitLearnMLDialog", "保存最优模型到本地文件的文件名"))
        self.isSaveEstimatorDataToExcelFileNameCheckBox.setText(_translate("ScikitLearnMLDialog", "保存模型训练数据、验证数据及测试数据结果到本地文件（Excel）的文件名："))
        self.isSaveTrainingDataToWorkingSheetNameCheckBox.setText(_translate("ScikitLearnMLDialog", "保存模型训练数据结果到本地文件（Excel）中的工作表名称："))
        self.isSaveCVDataToWorkingSheetNameCheckBox.setText(_translate("ScikitLearnMLDialog", "保存模型验证数据结果到本地文件（Excel）中的工作表名称："))
        self.isSaveTestDataToWorkingSheetNameCheckBox.setText(_translate("ScikitLearnMLDialog", "保存模型测试数据结果到本地文件（Excel）中的工作表名称："))
        self.selectEstimatorDataSaveDirectoryLabel.setText(_translate("ScikitLearnMLDialog", "保存路径"))
        self.resetSaveParameterPushButton.setText(_translate("ScikitLearnMLDialog", "重置参数"))
        self.saveEstimatorDataPushButton.setText(_translate("ScikitLearnMLDialog", "保存结果"))
        self.stepLogoLabel.setText(_translate("ScikitLearnMLDialog", "TextLabel"))
        self.stepTipLabel.setText(_translate("ScikitLearnMLDialog", "选择本地样本文件后，点击“下一步”以继续操作！"))
        self.previousStepPushButton.setText(_translate("ScikitLearnMLDialog", "上一步"))
        self.nextStepPushButton.setText(_translate("ScikitLearnMLDialog", "下一步"))
        self.cancelFinishPushButton.setText(_translate("ScikitLearnMLDialog", "取消"))
