# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectMLTaskTypeDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selectMLTaskTypeDialog(object):
    def setupUi(self, selectMLTaskTypeDialog):
        selectMLTaskTypeDialog.setObjectName("selectMLTaskTypeDialog")
        selectMLTaskTypeDialog.resize(831, 585)
        self.gridLayout_2 = QtWidgets.QGridLayout(selectMLTaskTypeDialog)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.clustererGroupBox = QtWidgets.QGroupBox(selectMLTaskTypeDialog)
        self.clustererGroupBox.setTitle("")
        self.clustererGroupBox.setObjectName("clustererGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.clustererGroupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clustererIconLabel = QtWidgets.QLabel(self.clustererGroupBox)
        self.clustererIconLabel.setText("")
        self.clustererIconLabel.setObjectName("clustererIconLabel")
        self.horizontalLayout_3.addWidget(self.clustererIconLabel)
        self.clustererDesciptionLabel = QtWidgets.QLabel(self.clustererGroupBox)
        self.clustererDesciptionLabel.setWordWrap(True)
        self.clustererDesciptionLabel.setObjectName("clustererDesciptionLabel")
        self.horizontalLayout_3.addWidget(self.clustererDesciptionLabel)
        self.clustererLine = QtWidgets.QFrame(self.clustererGroupBox)
        self.clustererLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.clustererLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.clustererLine.setObjectName("clustererLine")
        self.horizontalLayout_3.addWidget(self.clustererLine)
        self.clustererTaskRadioButton = QtWidgets.QRadioButton(self.clustererGroupBox)
        self.clustererTaskRadioButton.setObjectName("clustererTaskRadioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(selectMLTaskTypeDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.clustererTaskRadioButton)
        self.horizontalLayout_3.addWidget(self.clustererTaskRadioButton)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.gridLayout_2.addWidget(self.clustererGroupBox, 2, 0, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.cancelPushButton = QtWidgets.QPushButton(selectMLTaskTypeDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.gridLayout_2.addWidget(self.cancelPushButton, 3, 3, 1, 1)
        self.classifierGroupBox = QtWidgets.QGroupBox(selectMLTaskTypeDialog)
        self.classifierGroupBox.setTitle("")
        self.classifierGroupBox.setObjectName("classifierGroupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.classifierGroupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.classifierIconLabel = QtWidgets.QLabel(self.classifierGroupBox)
        self.classifierIconLabel.setText("")
        self.classifierIconLabel.setObjectName("classifierIconLabel")
        self.horizontalLayout_5.addWidget(self.classifierIconLabel)
        self.classifierDesciptionLabel = QtWidgets.QLabel(self.classifierGroupBox)
        self.classifierDesciptionLabel.setWordWrap(True)
        self.classifierDesciptionLabel.setObjectName("classifierDesciptionLabel")
        self.horizontalLayout_5.addWidget(self.classifierDesciptionLabel)
        self.classifierLine = QtWidgets.QFrame(self.classifierGroupBox)
        self.classifierLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.classifierLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.classifierLine.setObjectName("classifierLine")
        self.horizontalLayout_5.addWidget(self.classifierLine)
        self.classifierTaskRadioButton = QtWidgets.QRadioButton(self.classifierGroupBox)
        self.classifierTaskRadioButton.setChecked(True)
        self.classifierTaskRadioButton.setObjectName("classifierTaskRadioButton")
        self.buttonGroup.addButton(self.classifierTaskRadioButton)
        self.horizontalLayout_5.addWidget(self.classifierTaskRadioButton)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.gridLayout_2.addWidget(self.classifierGroupBox, 0, 0, 1, 5)
        self.regressorGroupBox = QtWidgets.QGroupBox(selectMLTaskTypeDialog)
        self.regressorGroupBox.setTitle("")
        self.regressorGroupBox.setObjectName("regressorGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.regressorGroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.regressorIconLabel = QtWidgets.QLabel(self.regressorGroupBox)
        self.regressorIconLabel.setText("")
        self.regressorIconLabel.setObjectName("regressorIconLabel")
        self.horizontalLayout_4.addWidget(self.regressorIconLabel)
        self.regressorDesciptionLabel = QtWidgets.QLabel(self.regressorGroupBox)
        self.regressorDesciptionLabel.setWordWrap(True)
        self.regressorDesciptionLabel.setObjectName("regressorDesciptionLabel")
        self.horizontalLayout_4.addWidget(self.regressorDesciptionLabel)
        self.regressorLine = QtWidgets.QFrame(self.regressorGroupBox)
        self.regressorLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.regressorLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.regressorLine.setObjectName("regressorLine")
        self.horizontalLayout_4.addWidget(self.regressorLine)
        self.regressorTaskRadioButton = QtWidgets.QRadioButton(self.regressorGroupBox)
        self.regressorTaskRadioButton.setObjectName("regressorTaskRadioButton")
        self.buttonGroup.addButton(self.regressorTaskRadioButton)
        self.horizontalLayout_4.addWidget(self.regressorTaskRadioButton)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.gridLayout_2.addWidget(self.regressorGroupBox, 1, 0, 1, 5)
        self.okPushButton = QtWidgets.QPushButton(selectMLTaskTypeDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.gridLayout_2.addWidget(self.okPushButton, 3, 2, 1, 1)

        self.retranslateUi(selectMLTaskTypeDialog)
        QtCore.QMetaObject.connectSlotsByName(selectMLTaskTypeDialog)

    def retranslateUi(self, selectMLTaskTypeDialog):
        _translate = QtCore.QCoreApplication.translate
        selectMLTaskTypeDialog.setWindowTitle(_translate("selectMLTaskTypeDialog", "选择机器学习类型"))
        self.clustererDesciptionLabel.setText(_translate("selectMLTaskTypeDialog", "该分类特指监督学习分类，这是一种使用已标记（带有标签）的训练数据训练机器学习分类模型，从而达到推断未知标签的数据样本，属于特定类别中的哪一类的机器学习任务。"))
        self.clustererTaskRadioButton.setText(_translate("selectMLTaskTypeDialog", "聚类"))
        self.cancelPushButton.setText(_translate("selectMLTaskTypeDialog", "取消"))
        self.classifierDesciptionLabel.setText(_translate("selectMLTaskTypeDialog", "该分类特指监督学习分类，这是一种使用已标记（带有标签）的训练数据训练机器学习分类模型，从而达到推断未知标签的数据样本，属于特定类别中的哪一类的机器学习任务。"))
        self.classifierTaskRadioButton.setText(_translate("selectMLTaskTypeDialog", "分类"))
        self.regressorDesciptionLabel.setText(_translate("selectMLTaskTypeDialog", "该分类特指监督学习分类，这是一种使用已标记（带有标签）的训练数据训练机器学习分类模型，从而达到推断未知标签的数据样本，属于特定类别中的哪一类的机器学习任务。"))
        self.regressorTaskRadioButton.setText(_translate("selectMLTaskTypeDialog", "回归"))
        self.okPushButton.setText(_translate("selectMLTaskTypeDialog", "确定"))
