# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\BandCalculatorDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BandCalculatorDialog(object):
    def setupUi(self, BandCalculatorDialog):
        BandCalculatorDialog.setObjectName("BandCalculatorDialog")
        BandCalculatorDialog.resize(990, 513)
        self.verticalLayout = QtWidgets.QVBoxLayout(BandCalculatorDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.fileListLabel = QtWidgets.QLabel(BandCalculatorDialog)
        self.fileListLabel.setObjectName("fileListLabel")
        self.gridLayout.addWidget(self.fileListLabel, 0, 0, 1, 1)
        self.fileListTableWidget = QtWidgets.QTableWidget(BandCalculatorDialog)
        self.fileListTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.fileListTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.fileListTableWidget.setRowCount(49)
        self.fileListTableWidget.setColumnCount(2)
        self.fileListTableWidget.setObjectName("fileListTableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.fileListTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fileListTableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.fileListTableWidget, 1, 0, 3, 3)
        self.selectImageFilePushButton = QtWidgets.QPushButton(BandCalculatorDialog)
        self.selectImageFilePushButton.setText("")
        self.selectImageFilePushButton.setObjectName("selectImageFilePushButton")
        self.gridLayout.addWidget(self.selectImageFilePushButton, 1, 3, 1, 1)
        self.deleteImageFilePushButton = QtWidgets.QPushButton(BandCalculatorDialog)
        self.deleteImageFilePushButton.setText("")
        self.deleteImageFilePushButton.setObjectName("deleteImageFilePushButton")
        self.gridLayout.addWidget(self.deleteImageFilePushButton, 2, 3, 1, 1)
        self.clearImageFilePushButton = QtWidgets.QPushButton(BandCalculatorDialog)
        self.clearImageFilePushButton.setText("")
        self.clearImageFilePushButton.setObjectName("clearImageFilePushButton")
        self.gridLayout.addWidget(self.clearImageFilePushButton, 3, 3, 1, 1)
        self.validBandLabel = QtWidgets.QLabel(BandCalculatorDialog)
        self.validBandLabel.setObjectName("validBandLabel")
        self.gridLayout.addWidget(self.validBandLabel, 4, 0, 1, 1)
        self.bandCalculationFormulaLabel = QtWidgets.QLabel(BandCalculatorDialog)
        self.bandCalculationFormulaLabel.setObjectName("bandCalculationFormulaLabel")
        self.gridLayout.addWidget(self.bandCalculationFormulaLabel, 6, 0, 1, 1)
        self.addBandCalculationFormulaPushButton = QtWidgets.QPushButton(BandCalculatorDialog)
        self.addBandCalculationFormulaPushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.addBandCalculationFormulaPushButton.setObjectName("addBandCalculationFormulaPushButton")
        self.gridLayout.addWidget(self.addBandCalculationFormulaPushButton, 7, 3, 1, 1)
        self.validBandCalculationFormulaLabel = QtWidgets.QLabel(BandCalculatorDialog)
        self.validBandCalculationFormulaLabel.setObjectName("validBandCalculationFormulaLabel")
        self.gridLayout.addWidget(self.validBandCalculationFormulaLabel, 8, 0, 1, 1)
        self.saveBandOrderLabel = QtWidgets.QLabel(BandCalculatorDialog)
        self.saveBandOrderLabel.setObjectName("saveBandOrderLabel")
        self.gridLayout.addWidget(self.saveBandOrderLabel, 8, 2, 1, 1)
        self.validBandCalculationFormulaListWidget = QtWidgets.QListWidget(BandCalculatorDialog)
        self.validBandCalculationFormulaListWidget.setObjectName("validBandCalculationFormulaListWidget")
        self.gridLayout.addWidget(self.validBandCalculationFormulaListWidget, 9, 0, 4, 1)
        self.saveBandOrderListWidget = QtWidgets.QListWidget(BandCalculatorDialog)
        self.saveBandOrderListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.saveBandOrderListWidget.setObjectName("saveBandOrderListWidget")
        self.gridLayout.addWidget(self.saveBandOrderListWidget, 9, 2, 4, 1)
        self.moveUpBandPushButton = QtWidgets.QPushButton(BandCalculatorDialog)
        self.moveUpBandPushButton.setText("")
        self.moveUpBandPushButton.setObjectName("moveUpBandPushButton")
        self.gridLayout.addWidget(self.moveUpBandPushButton, 9, 3, 1, 1)
        self.deleteBandCalculationFormulaPushButton = QtWidgets.QPushButton(BandCalculatorDialog)
        self.deleteBandCalculationFormulaPushButton.setText("")
        self.deleteBandCalculationFormulaPushButton.setObjectName("deleteBandCalculationFormulaPushButton")
        self.gridLayout.addWidget(self.deleteBandCalculationFormulaPushButton, 10, 1, 1, 1)
        self.moveDownBandPushButton = QtWidgets.QPushButton(BandCalculatorDialog)
        self.moveDownBandPushButton.setText("")
        self.moveDownBandPushButton.setObjectName("moveDownBandPushButton")
        self.gridLayout.addWidget(self.moveDownBandPushButton, 10, 3, 1, 1)
        self.clearBandCalculationFormulaPushButton = QtWidgets.QPushButton(BandCalculatorDialog)
        self.clearBandCalculationFormulaPushButton.setText("")
        self.clearBandCalculationFormulaPushButton.setObjectName("clearBandCalculationFormulaPushButton")
        self.gridLayout.addWidget(self.clearBandCalculationFormulaPushButton, 11, 1, 1, 1)
        self.deleteBandPushButton = QtWidgets.QPushButton(BandCalculatorDialog)
        self.deleteBandPushButton.setText("")
        self.deleteBandPushButton.setObjectName("deleteBandPushButton")
        self.gridLayout.addWidget(self.deleteBandPushButton, 11, 3, 1, 1)
        self.resetBandPushButton = QtWidgets.QPushButton(BandCalculatorDialog)
        self.resetBandPushButton.setText("")
        self.resetBandPushButton.setObjectName("resetBandPushButton")
        self.gridLayout.addWidget(self.resetBandPushButton, 12, 3, 1, 1)
        self.selectSaveDirectoryLabel = QtWidgets.QLabel(BandCalculatorDialog)
        self.selectSaveDirectoryLabel.setObjectName("selectSaveDirectoryLabel")
        self.gridLayout.addWidget(self.selectSaveDirectoryLabel, 13, 0, 1, 1)
        self.selectSaveDirectoryPushButton = QtWidgets.QPushButton(BandCalculatorDialog)
        self.selectSaveDirectoryPushButton.setText("")
        self.selectSaveDirectoryPushButton.setObjectName("selectSaveDirectoryPushButton")
        self.gridLayout.addWidget(self.selectSaveDirectoryPushButton, 14, 3, 1, 1)
        self.validBandLineEdit = QtWidgets.QLineEdit(BandCalculatorDialog)
        self.validBandLineEdit.setObjectName("validBandLineEdit")
        self.gridLayout.addWidget(self.validBandLineEdit, 5, 0, 1, 3)
        self.bandCalculationFormulaLineEdit = QtWidgets.QLineEdit(BandCalculatorDialog)
        self.bandCalculationFormulaLineEdit.setObjectName("bandCalculationFormulaLineEdit")
        self.gridLayout.addWidget(self.bandCalculationFormulaLineEdit, 7, 0, 1, 3)
        self.selectSaveDirectoryLineEdit = QtWidgets.QLineEdit(BandCalculatorDialog)
        self.selectSaveDirectoryLineEdit.setObjectName("selectSaveDirectoryLineEdit")
        self.gridLayout.addWidget(self.selectSaveDirectoryLineEdit, 14, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(BandCalculatorDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okPushButton = QtWidgets.QPushButton(BandCalculatorDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(BandCalculatorDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(BandCalculatorDialog)
        QtCore.QMetaObject.connectSlotsByName(BandCalculatorDialog)

    def retranslateUi(self, BandCalculatorDialog):
        _translate = QtCore.QCoreApplication.translate
        BandCalculatorDialog.setWindowTitle(_translate("BandCalculatorDialog", "波段计算器"))
        self.fileListLabel.setText(_translate("BandCalculatorDialog", "文件列表："))
        item = self.fileListTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("BandCalculatorDialog", "输入影像"))
        item = self.fileListTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("BandCalculatorDialog", "输出影像"))
        self.validBandLabel.setText(_translate("BandCalculatorDialog", "有效波段："))
        self.bandCalculationFormulaLabel.setText(_translate("BandCalculatorDialog", "波段计算公式：e.g.(B5-B4)/(B5+B4)"))
        self.addBandCalculationFormulaPushButton.setText(_translate("BandCalculatorDialog", "添加"))
        self.validBandCalculationFormulaLabel.setText(_translate("BandCalculatorDialog", "有效波段计算公式："))
        self.saveBandOrderLabel.setText(_translate("BandCalculatorDialog", "波段保存顺序："))
        self.selectSaveDirectoryLabel.setText(_translate("BandCalculatorDialog", "保存位置："))
        self.okPushButton.setText(_translate("BandCalculatorDialog", "确定"))
        self.cancelPushButton.setText(_translate("BandCalculatorDialog", "取消"))
