# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageFusionSTARFMDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImageFusionSTARFMDialog(object):
    def setupUi(self, ImageFusionSTARFMDialog):
        ImageFusionSTARFMDialog.setObjectName("ImageFusionSTARFMDialog")
        ImageFusionSTARFMDialog.resize(880, 465)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ImageFusionSTARFMDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(ImageFusionSTARFMDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.openTkCoarseResolutionImageLabel = QtWidgets.QLabel(self.groupBox_2)
        self.openTkCoarseResolutionImageLabel.setObjectName("openTkCoarseResolutionImageLabel")
        self.gridLayout_3.addWidget(self.openTkCoarseResolutionImageLabel, 0, 0, 1, 1)
        self.openTkCoarseResolutionImageLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.openTkCoarseResolutionImageLineEdit.setObjectName("openTkCoarseResolutionImageLineEdit")
        self.gridLayout_3.addWidget(self.openTkCoarseResolutionImageLineEdit, 0, 1, 1, 1)
        self.openTkCoarseResolutionImagePushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.openTkCoarseResolutionImagePushButton.setText("")
        self.openTkCoarseResolutionImagePushButton.setObjectName("openTkCoarseResolutionImagePushButton")
        self.gridLayout_3.addWidget(self.openTkCoarseResolutionImagePushButton, 0, 2, 1, 1)
        self.openTkFineResolutionImageLabel = QtWidgets.QLabel(self.groupBox_2)
        self.openTkFineResolutionImageLabel.setObjectName("openTkFineResolutionImageLabel")
        self.gridLayout_3.addWidget(self.openTkFineResolutionImageLabel, 1, 0, 1, 1)
        self.openTkFineResolutionImageLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.openTkFineResolutionImageLineEdit.setObjectName("openTkFineResolutionImageLineEdit")
        self.gridLayout_3.addWidget(self.openTkFineResolutionImageLineEdit, 1, 1, 1, 1)
        self.openTkFineResolutionImagePushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.openTkFineResolutionImagePushButton.setText("")
        self.openTkFineResolutionImagePushButton.setObjectName("openTkFineResolutionImagePushButton")
        self.gridLayout_3.addWidget(self.openTkFineResolutionImagePushButton, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(ImageFusionSTARFMDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.openT0CoarseResolutionImageLabel = QtWidgets.QLabel(self.groupBox)
        self.openT0CoarseResolutionImageLabel.setObjectName("openT0CoarseResolutionImageLabel")
        self.gridLayout_2.addWidget(self.openT0CoarseResolutionImageLabel, 0, 0, 1, 1)
        self.openT0CoarseResolutionImageLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.openT0CoarseResolutionImageLineEdit.setObjectName("openT0CoarseResolutionImageLineEdit")
        self.gridLayout_2.addWidget(self.openT0CoarseResolutionImageLineEdit, 0, 1, 1, 1)
        self.openT0CoarseResolutionImagePushButton = QtWidgets.QPushButton(self.groupBox)
        self.openT0CoarseResolutionImagePushButton.setText("")
        self.openT0CoarseResolutionImagePushButton.setObjectName("openT0CoarseResolutionImagePushButton")
        self.gridLayout_2.addWidget(self.openT0CoarseResolutionImagePushButton, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.statusGroupBox = QtWidgets.QGroupBox(ImageFusionSTARFMDialog)
        self.statusGroupBox.setObjectName("statusGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.statusGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statusTextEdit = QtWidgets.QTextEdit(self.statusGroupBox)
        self.statusTextEdit.setObjectName("statusTextEdit")
        self.horizontalLayout.addWidget(self.statusTextEdit)
        self.parametersSettingsGroupBox = QtWidgets.QGroupBox(self.statusGroupBox)
        self.parametersSettingsGroupBox.setObjectName("parametersSettingsGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.parametersSettingsGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.selectT0FineResolutionImageSaveDirLabel = QtWidgets.QLabel(self.parametersSettingsGroupBox)
        self.selectT0FineResolutionImageSaveDirLabel.setObjectName("selectT0FineResolutionImageSaveDirLabel")
        self.gridLayout.addWidget(self.selectT0FineResolutionImageSaveDirLabel, 6, 0, 1, 2)
        self.windowSizeLabel = QtWidgets.QLabel(self.parametersSettingsGroupBox)
        self.windowSizeLabel.setObjectName("windowSizeLabel")
        self.gridLayout.addWidget(self.windowSizeLabel, 5, 0, 1, 1)
        self.constantSLabel = QtWidgets.QLabel(self.parametersSettingsGroupBox)
        self.constantSLabel.setObjectName("constantSLabel")
        self.gridLayout.addWidget(self.constantSLabel, 1, 0, 1, 1)
        self.selectT0FineResolutionImageSaveDirPushButton = QtWidgets.QPushButton(self.parametersSettingsGroupBox)
        self.selectT0FineResolutionImageSaveDirPushButton.setText("")
        self.selectT0FineResolutionImageSaveDirPushButton.setObjectName("selectT0FineResolutionImageSaveDirPushButton")
        self.gridLayout.addWidget(self.selectT0FineResolutionImageSaveDirPushButton, 7, 7, 1, 1)
        self.selectT0FineResolutionImageSaveDirLineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.selectT0FineResolutionImageSaveDirLineEdit.setObjectName("selectT0FineResolutionImageSaveDirLineEdit")
        self.gridLayout.addWidget(self.selectT0FineResolutionImageSaveDirLineEdit, 7, 0, 1, 7)
        self.stopConstantSLineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.stopConstantSLineEdit.setObjectName("stopConstantSLineEdit")
        self.gridLayout.addWidget(self.stopConstantSLineEdit, 1, 3, 1, 1)
        self.constantALabel = QtWidgets.QLabel(self.parametersSettingsGroupBox)
        self.constantALabel.setObjectName("constantALabel")
        self.gridLayout.addWidget(self.constantALabel, 4, 0, 1, 1)
        self.stopConstantDLineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.stopConstantDLineEdit.setObjectName("stopConstantDLineEdit")
        self.gridLayout.addWidget(self.stopConstantDLineEdit, 3, 3, 1, 1)
        self.startConstantSLineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.startConstantSLineEdit.setObjectName("startConstantSLineEdit")
        self.gridLayout.addWidget(self.startConstantSLineEdit, 1, 1, 1, 1)
        self.stopConstantALineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.stopConstantALineEdit.setObjectName("stopConstantALineEdit")
        self.gridLayout.addWidget(self.stopConstantALineEdit, 4, 3, 1, 1)
        self.startLabel = QtWidgets.QLabel(self.parametersSettingsGroupBox)
        self.startLabel.setObjectName("startLabel")
        self.gridLayout.addWidget(self.startLabel, 0, 1, 1, 1)
        self.stopWindowSizeLineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.stopWindowSizeLineEdit.setObjectName("stopWindowSizeLineEdit")
        self.gridLayout.addWidget(self.stopWindowSizeLineEdit, 5, 3, 1, 1)
        self.stepConstantSLineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.stepConstantSLineEdit.setObjectName("stepConstantSLineEdit")
        self.gridLayout.addWidget(self.stepConstantSLineEdit, 1, 5, 1, 2)
        self.stepConstantDLineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.stepConstantDLineEdit.setObjectName("stepConstantDLineEdit")
        self.gridLayout.addWidget(self.stepConstantDLineEdit, 3, 5, 1, 2)
        self.startWindowSizeLineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.startWindowSizeLineEdit.setObjectName("startWindowSizeLineEdit")
        self.gridLayout.addWidget(self.startWindowSizeLineEdit, 5, 1, 1, 1)
        self.constantTLabel = QtWidgets.QLabel(self.parametersSettingsGroupBox)
        self.constantTLabel.setObjectName("constantTLabel")
        self.gridLayout.addWidget(self.constantTLabel, 2, 0, 1, 1)
        self.startConstantALineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.startConstantALineEdit.setObjectName("startConstantALineEdit")
        self.gridLayout.addWidget(self.startConstantALineEdit, 4, 1, 1, 1)
        self.startConstantTLineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.startConstantTLineEdit.setObjectName("startConstantTLineEdit")
        self.gridLayout.addWidget(self.startConstantTLineEdit, 2, 1, 1, 1)
        self.stepConstantTLineEdit_2 = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.stepConstantTLineEdit_2.setObjectName("stepConstantTLineEdit_2")
        self.gridLayout.addWidget(self.stepConstantTLineEdit_2, 2, 3, 1, 1)
        self.stepConstantTLineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.stepConstantTLineEdit.setObjectName("stepConstantTLineEdit")
        self.gridLayout.addWidget(self.stepConstantTLineEdit, 2, 5, 1, 2)
        self.stepConstantALineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.stepConstantALineEdit.setObjectName("stepConstantALineEdit")
        self.gridLayout.addWidget(self.stepConstantALineEdit, 4, 5, 1, 2)
        self.constantDLabel = QtWidgets.QLabel(self.parametersSettingsGroupBox)
        self.constantDLabel.setObjectName("constantDLabel")
        self.gridLayout.addWidget(self.constantDLabel, 3, 0, 1, 1)
        self.startConstantDLineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.startConstantDLineEdit.setObjectName("startConstantDLineEdit")
        self.gridLayout.addWidget(self.startConstantDLineEdit, 3, 1, 1, 1)
        self.stopLabel = QtWidgets.QLabel(self.parametersSettingsGroupBox)
        self.stopLabel.setObjectName("stopLabel")
        self.gridLayout.addWidget(self.stopLabel, 0, 3, 1, 1)
        self.stepWindowSizeLineEdit = QtWidgets.QLineEdit(self.parametersSettingsGroupBox)
        self.stepWindowSizeLineEdit.setObjectName("stepWindowSizeLineEdit")
        self.gridLayout.addWidget(self.stepWindowSizeLineEdit, 5, 5, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.stepLabel = QtWidgets.QLabel(self.parametersSettingsGroupBox)
        self.stepLabel.setObjectName("stepLabel")
        self.gridLayout.addWidget(self.stepLabel, 0, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.horizontalLayout.addWidget(self.parametersSettingsGroupBox)
        self.horizontalLayout_2.addWidget(self.statusGroupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.okPushButton = QtWidgets.QPushButton(ImageFusionSTARFMDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout_3.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(ImageFusionSTARFMDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_3.addWidget(self.cancelPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(ImageFusionSTARFMDialog)
        QtCore.QMetaObject.connectSlotsByName(ImageFusionSTARFMDialog)

    def retranslateUi(self, ImageFusionSTARFMDialog):
        _translate = QtCore.QCoreApplication.translate
        ImageFusionSTARFMDialog.setWindowTitle(_translate("ImageFusionSTARFMDialog", "STARFM图像融合"))
        self.groupBox_2.setTitle(_translate("ImageFusionSTARFMDialog", "Tk时刻影像对"))
        self.openTkCoarseResolutionImageLabel.setText(_translate("ImageFusionSTARFMDialog", "Tk输入低分影像："))
        self.openTkFineResolutionImageLabel.setText(_translate("ImageFusionSTARFMDialog", "Tk输入高分影像："))
        self.groupBox.setTitle(_translate("ImageFusionSTARFMDialog", "T0时刻影像对"))
        self.openT0CoarseResolutionImageLabel.setText(_translate("ImageFusionSTARFMDialog", "T0输入低分影像："))
        self.statusGroupBox.setTitle(_translate("ImageFusionSTARFMDialog", "参数得分图表"))
        self.parametersSettingsGroupBox.setTitle(_translate("ImageFusionSTARFMDialog", "参数设置"))
        self.selectT0FineResolutionImageSaveDirLabel.setText(_translate("ImageFusionSTARFMDialog", "T0拟合高分影像保存路径："))
        self.windowSizeLabel.setText(_translate("ImageFusionSTARFMDialog", "窗口尺寸："))
        self.constantSLabel.setText(_translate("ImageFusionSTARFMDialog", "系数S："))
        self.stopConstantSLineEdit.setText(_translate("ImageFusionSTARFMDialog", "1.0"))
        self.constantALabel.setText(_translate("ImageFusionSTARFMDialog", "系数A："))
        self.stopConstantDLineEdit.setText(_translate("ImageFusionSTARFMDialog", "1.0"))
        self.startConstantSLineEdit.setText(_translate("ImageFusionSTARFMDialog", "1.0"))
        self.stopConstantALineEdit.setText(_translate("ImageFusionSTARFMDialog", "1.0"))
        self.startLabel.setText(_translate("ImageFusionSTARFMDialog", "起始值"))
        self.stopWindowSizeLineEdit.setText(_translate("ImageFusionSTARFMDialog", "19"))
        self.stepConstantSLineEdit.setText(_translate("ImageFusionSTARFMDialog", "1.0"))
        self.stepConstantDLineEdit.setText(_translate("ImageFusionSTARFMDialog", "1.0"))
        self.startWindowSizeLineEdit.setText(_translate("ImageFusionSTARFMDialog", "15"))
        self.constantTLabel.setText(_translate("ImageFusionSTARFMDialog", "系数T："))
        self.startConstantALineEdit.setText(_translate("ImageFusionSTARFMDialog", "1.0"))
        self.startConstantTLineEdit.setText(_translate("ImageFusionSTARFMDialog", "1.0"))
        self.stepConstantTLineEdit_2.setText(_translate("ImageFusionSTARFMDialog", "1.0"))
        self.stepConstantTLineEdit.setText(_translate("ImageFusionSTARFMDialog", "1.0"))
        self.stepConstantALineEdit.setText(_translate("ImageFusionSTARFMDialog", "1.0"))
        self.constantDLabel.setText(_translate("ImageFusionSTARFMDialog", "系数D："))
        self.startConstantDLineEdit.setText(_translate("ImageFusionSTARFMDialog", "1.0"))
        self.stopLabel.setText(_translate("ImageFusionSTARFMDialog", "终止值"))
        self.stepWindowSizeLineEdit.setText(_translate("ImageFusionSTARFMDialog", "2"))
        self.stepLabel.setText(_translate("ImageFusionSTARFMDialog", "取值间隔"))
        self.okPushButton.setText(_translate("ImageFusionSTARFMDialog", "确定"))
        self.cancelPushButton.setText(_translate("ImageFusionSTARFMDialog", "取消"))

