# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ScikitLearnMLDialogDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScikitLearnMLDialog(object):
    def setupUi(self, ScikitLearnMLDialog):
        ScikitLearnMLDialog.setObjectName("ScikitLearnMLDialog")
        ScikitLearnMLDialog.resize(1006, 620)
        ScikitLearnMLDialog.setStyleSheet("")
        self.topDialogVerticalLayout = QtWidgets.QVBoxLayout(ScikitLearnMLDialog)
        self.topDialogVerticalLayout.setContentsMargins(5, 10, 5, 10)
        self.topDialogVerticalLayout.setSpacing(5)
        self.topDialogVerticalLayout.setObjectName("topDialogVerticalLayout")
        self.topOperationWidgetGridLayout = QtWidgets.QGridLayout()
        self.topOperationWidgetGridLayout.setContentsMargins(-1, -1, -1, 10)
        self.topOperationWidgetGridLayout.setObjectName("topOperationWidgetGridLayout")
        self.operationTitleLabel = QtWidgets.QLabel(ScikitLearnMLDialog)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.operationTitleLabel.setFont(font)
        self.operationTitleLabel.setObjectName("operationTitleLabel")
        self.topOperationWidgetGridLayout.addWidget(self.operationTitleLabel, 0, 1, 1, 1)
        self.operationDescriptionLabel = QtWidgets.QLabel(ScikitLearnMLDialog)
        self.operationDescriptionLabel.setObjectName("operationDescriptionLabel")
        self.topOperationWidgetGridLayout.addWidget(self.operationDescriptionLabel, 1, 1, 1, 1)
        self.operationLogoLabel = QtWidgets.QLabel(ScikitLearnMLDialog)
        self.operationLogoLabel.setObjectName("operationLogoLabel")
        self.topOperationWidgetGridLayout.addWidget(self.operationLogoLabel, 0, 0, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topOperationWidgetGridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topOperationWidgetGridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.topDialogVerticalLayout.addLayout(self.topOperationWidgetGridLayout)
        self.scikitLearnSettingStackedWidget = QtWidgets.QStackedWidget(ScikitLearnMLDialog)
        self.scikitLearnSettingStackedWidget.setObjectName("scikitLearnSettingStackedWidget")
        self.selectTaskTypePage = QtWidgets.QWidget()
        self.selectTaskTypePage.setObjectName("selectTaskTypePage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.selectTaskTypePage)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.classifierGroupBox = QtWidgets.QGroupBox(self.selectTaskTypePage)
        self.classifierGroupBox.setTitle("")
        self.classifierGroupBox.setObjectName("classifierGroupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.classifierGroupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.classificationIconLabel = QtWidgets.QLabel(self.classifierGroupBox)
        self.classificationIconLabel.setText("")
        self.classificationIconLabel.setObjectName("classificationIconLabel")
        self.horizontalLayout_5.addWidget(self.classificationIconLabel)
        self.classificationDesciptionLabel = QtWidgets.QLabel(self.classifierGroupBox)
        self.classificationDesciptionLabel.setWordWrap(True)
        self.classificationDesciptionLabel.setObjectName("classificationDesciptionLabel")
        self.horizontalLayout_5.addWidget(self.classificationDesciptionLabel)
        self.classifierLine = QtWidgets.QFrame(self.classifierGroupBox)
        self.classifierLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.classifierLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.classifierLine.setObjectName("classifierLine")
        self.horizontalLayout_5.addWidget(self.classifierLine)
        self.classificationTaskRadioButton = QtWidgets.QRadioButton(self.classifierGroupBox)
        self.classificationTaskRadioButton.setChecked(True)
        self.classificationTaskRadioButton.setObjectName("classificationTaskRadioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(ScikitLearnMLDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.classificationTaskRadioButton)
        self.horizontalLayout_5.addWidget(self.classificationTaskRadioButton)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.gridLayout_2.addWidget(self.classifierGroupBox, 0, 0, 1, 1)
        self.regressorGroupBox = QtWidgets.QGroupBox(self.selectTaskTypePage)
        self.regressorGroupBox.setTitle("")
        self.regressorGroupBox.setObjectName("regressorGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.regressorGroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.regressionIconLabel = QtWidgets.QLabel(self.regressorGroupBox)
        self.regressionIconLabel.setText("")
        self.regressionIconLabel.setObjectName("regressionIconLabel")
        self.horizontalLayout_4.addWidget(self.regressionIconLabel)
        self.regressionDesciptionLabel = QtWidgets.QLabel(self.regressorGroupBox)
        self.regressionDesciptionLabel.setWordWrap(True)
        self.regressionDesciptionLabel.setObjectName("regressionDesciptionLabel")
        self.horizontalLayout_4.addWidget(self.regressionDesciptionLabel)
        self.regressorLine = QtWidgets.QFrame(self.regressorGroupBox)
        self.regressorLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.regressorLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.regressorLine.setObjectName("regressorLine")
        self.horizontalLayout_4.addWidget(self.regressorLine)
        self.regressionTaskRadioButton = QtWidgets.QRadioButton(self.regressorGroupBox)
        self.regressionTaskRadioButton.setObjectName("regressionTaskRadioButton")
        self.buttonGroup.addButton(self.regressionTaskRadioButton)
        self.horizontalLayout_4.addWidget(self.regressionTaskRadioButton)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.gridLayout_2.addWidget(self.regressorGroupBox, 1, 0, 1, 1)
        self.clustererGroupBox = QtWidgets.QGroupBox(self.selectTaskTypePage)
        self.clustererGroupBox.setTitle("")
        self.clustererGroupBox.setObjectName("clustererGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.clustererGroupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clusterIconLabel = QtWidgets.QLabel(self.clustererGroupBox)
        self.clusterIconLabel.setText("")
        self.clusterIconLabel.setObjectName("clusterIconLabel")
        self.horizontalLayout_3.addWidget(self.clusterIconLabel)
        self.clusterDesciptionLabel = QtWidgets.QLabel(self.clustererGroupBox)
        self.clusterDesciptionLabel.setWordWrap(True)
        self.clusterDesciptionLabel.setObjectName("clusterDesciptionLabel")
        self.horizontalLayout_3.addWidget(self.clusterDesciptionLabel)
        self.clustererLine = QtWidgets.QFrame(self.clustererGroupBox)
        self.clustererLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.clustererLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.clustererLine.setObjectName("clustererLine")
        self.horizontalLayout_3.addWidget(self.clustererLine)
        self.clusterTaskRadioButton = QtWidgets.QRadioButton(self.clustererGroupBox)
        self.clusterTaskRadioButton.setObjectName("clusterTaskRadioButton")
        self.buttonGroup.addButton(self.clusterTaskRadioButton)
        self.horizontalLayout_3.addWidget(self.clusterTaskRadioButton)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.gridLayout_2.addWidget(self.clustererGroupBox, 2, 0, 1, 1)
        self.scikitLearnSettingStackedWidget.addWidget(self.selectTaskTypePage)
        self.selectSamplePage = QtWidgets.QWidget()
        self.selectSamplePage.setObjectName("selectSamplePage")
        self.selectSampleVerticalLayout = QtWidgets.QVBoxLayout(self.selectSamplePage)
        self.selectSampleVerticalLayout.setContentsMargins(0, 10, 0, 10)
        self.selectSampleVerticalLayout.setSpacing(5)
        self.selectSampleVerticalLayout.setObjectName("selectSampleVerticalLayout")
        self.sampleSettingGroupBox = QtWidgets.QGroupBox(self.selectSamplePage)
        self.sampleSettingGroupBox.setObjectName("sampleSettingGroupBox")
        self.sampleSettingGroupBoxGridLayout = QtWidgets.QGridLayout(self.sampleSettingGroupBox)
        self.sampleSettingGroupBoxGridLayout.setContentsMargins(5, 5, 5, 5)
        self.sampleSettingGroupBoxGridLayout.setVerticalSpacing(15)
        self.sampleSettingGroupBoxGridLayout.setObjectName("sampleSettingGroupBoxGridLayout")
        self.isIncludeColTitleCheckBox = QtWidgets.QCheckBox(self.sampleSettingGroupBox)
        self.isIncludeColTitleCheckBox.setChecked(True)
        self.isIncludeColTitleCheckBox.setObjectName("isIncludeColTitleCheckBox")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.isIncludeColTitleCheckBox, 1, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sampleSettingGroupBoxGridLayout.addItem(spacerItem2, 1, 7, 1, 1)
        self.selectTrainingValidationSampleLabel = QtWidgets.QLabel(self.sampleSettingGroupBox)
        self.selectTrainingValidationSampleLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.selectTrainingValidationSampleLabel.setObjectName("selectTrainingValidationSampleLabel")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.selectTrainingValidationSampleLabel, 4, 0, 1, 1)
        self.selectTrainingValidationSamplePushButton = QtWidgets.QPushButton(self.sampleSettingGroupBox)
        self.selectTrainingValidationSamplePushButton.setText("")
        self.selectTrainingValidationSamplePushButton.setObjectName("selectTrainingValidationSamplePushButton")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.selectTrainingValidationSamplePushButton, 4, 12, 1, 1)
        self.selectTrainingValidationSampleLineEdit = QtWidgets.QLineEdit(self.sampleSettingGroupBox)
        self.selectTrainingValidationSampleLineEdit.setObjectName("selectTrainingValidationSampleLineEdit")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.selectTrainingValidationSampleLineEdit, 4, 1, 1, 11)
        self.sampleTypeLabel = QtWidgets.QLabel(self.sampleSettingGroupBox)
        self.sampleTypeLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sampleTypeLabel.setObjectName("sampleTypeLabel")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.sampleTypeLabel, 1, 0, 1, 1)
        self.selectTestSamplePushButton = QtWidgets.QPushButton(self.sampleSettingGroupBox)
        self.selectTestSamplePushButton.setText("")
        self.selectTestSamplePushButton.setObjectName("selectTestSamplePushButton")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.selectTestSamplePushButton, 5, 12, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sampleSettingGroupBoxGridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sampleSettingGroupBoxGridLayout.addItem(spacerItem4, 1, 9, 1, 1)
        self.selectTestSampleLabel = QtWidgets.QLabel(self.sampleSettingGroupBox)
        self.selectTestSampleLabel.setEnabled(True)
        self.selectTestSampleLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.selectTestSampleLabel.setObjectName("selectTestSampleLabel")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.selectTestSampleLabel, 5, 0, 1, 1)
        self.selectTestSampleLineEdit = QtWidgets.QLineEdit(self.sampleSettingGroupBox)
        self.selectTestSampleLineEdit.setObjectName("selectTestSampleLineEdit")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.selectTestSampleLineEdit, 5, 1, 1, 11)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sampleSettingGroupBoxGridLayout.addItem(spacerItem5, 1, 5, 1, 1)
        self.isIncludeRowTitleCheckBox = QtWidgets.QCheckBox(self.sampleSettingGroupBox)
        self.isIncludeRowTitleCheckBox.setChecked(True)
        self.isIncludeRowTitleCheckBox.setObjectName("isIncludeRowTitleCheckBox")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.isIncludeRowTitleCheckBox, 1, 1, 1, 1)
        self.isRowMajorRadioButton = QtWidgets.QRadioButton(self.sampleSettingGroupBox)
        self.isRowMajorRadioButton.setChecked(True)
        self.isRowMajorRadioButton.setObjectName("isRowMajorRadioButton")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.isRowMajorRadioButton, 1, 6, 1, 1)
        self.isColMajorRadioButton = QtWidgets.QRadioButton(self.sampleSettingGroupBox)
        self.isColMajorRadioButton.setObjectName("isColMajorRadioButton")
        self.sampleSettingGroupBoxGridLayout.addWidget(self.isColMajorRadioButton, 1, 8, 1, 1)
        self.selectSampleVerticalLayout.addWidget(self.sampleSettingGroupBox)
        self.frame = QtWidgets.QFrame(self.selectSamplePage)
        self.frame.setStyleSheet("background-color:white")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sampleStatisticChartGridLayout = QtWidgets.QGridLayout()
        self.sampleStatisticChartGridLayout.setObjectName("sampleStatisticChartGridLayout")
        self.horizontalLayout.addLayout(self.sampleStatisticChartGridLayout)
        self.selectSampleVerticalLayout.addWidget(self.frame)
        self.selectSampleVerticalLayout.setStretch(1, 1)
        self.scikitLearnSettingStackedWidget.addWidget(self.selectSamplePage)
        self.setParameterPage = QtWidgets.QWidget()
        self.setParameterPage.setObjectName("setParameterPage")
        self.setParameterVerticalLayout = QtWidgets.QVBoxLayout(self.setParameterPage)
        self.setParameterVerticalLayout.setContentsMargins(0, 10, 0, 10)
        self.setParameterVerticalLayout.setSpacing(5)
        self.setParameterVerticalLayout.setObjectName("setParameterVerticalLayout")
        self.scikitLearnSettingGroupBox = QtWidgets.QGroupBox(self.setParameterPage)
        self.scikitLearnSettingGroupBox.setTitle("")
        self.scikitLearnSettingGroupBox.setObjectName("scikitLearnSettingGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.scikitLearnSettingGroupBox)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 5, 1, 1)
        self.selectParameterTypeLabel = QtWidgets.QLabel(self.scikitLearnSettingGroupBox)
        self.selectParameterTypeLabel.setObjectName("selectParameterTypeLabel")
        self.gridLayout.addWidget(self.selectParameterTypeLabel, 0, 3, 1, 1)
        self.selectParameterTypeComboBox = QtWidgets.QComboBox(self.scikitLearnSettingGroupBox)
        self.selectParameterTypeComboBox.setMinimumSize(QtCore.QSize(85, 0))
        self.selectParameterTypeComboBox.setObjectName("selectParameterTypeComboBox")
        self.selectParameterTypeComboBox.addItem("")
        self.selectParameterTypeComboBox.addItem("")
        self.selectParameterTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.selectParameterTypeComboBox, 0, 4, 1, 1)
        self.selectParameterTunerLabel = QtWidgets.QLabel(self.scikitLearnSettingGroupBox)
        self.selectParameterTunerLabel.setObjectName("selectParameterTunerLabel")
        self.gridLayout.addWidget(self.selectParameterTunerLabel, 0, 6, 1, 1)
        self.saveParameterToFilePushButton = QtWidgets.QPushButton(self.scikitLearnSettingGroupBox)
        self.saveParameterToFilePushButton.setText("")
        self.saveParameterToFilePushButton.setObjectName("saveParameterToFilePushButton")
        self.gridLayout.addWidget(self.saveParameterToFilePushButton, 0, 11, 1, 1)
        self.selectEstimatorLabel = QtWidgets.QLabel(self.scikitLearnSettingGroupBox)
        self.selectEstimatorLabel.setMaximumSize(QtCore.QSize(60, 25))
        self.selectEstimatorLabel.setObjectName("selectEstimatorLabel")
        self.gridLayout.addWidget(self.selectEstimatorLabel, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 2, 1, 1)
        self.resetParameterPushButton = QtWidgets.QPushButton(self.scikitLearnSettingGroupBox)
        self.resetParameterPushButton.setEnabled(True)
        self.resetParameterPushButton.setText("")
        self.resetParameterPushButton.setObjectName("resetParameterPushButton")
        self.gridLayout.addWidget(self.resetParameterPushButton, 0, 10, 1, 1)
        self.selectEstimatorComboBox = QtWidgets.QComboBox(self.scikitLearnSettingGroupBox)
        self.selectEstimatorComboBox.setMinimumSize(QtCore.QSize(85, 0))
        self.selectEstimatorComboBox.setObjectName("selectEstimatorComboBox")
        self.gridLayout.addWidget(self.selectEstimatorComboBox, 0, 1, 1, 1)
        self.importParameterFromFilePushButton = QtWidgets.QPushButton(self.scikitLearnSettingGroupBox)
        self.importParameterFromFilePushButton.setEnabled(False)
        self.importParameterFromFilePushButton.setText("")
        self.importParameterFromFilePushButton.setObjectName("importParameterFromFilePushButton")
        self.gridLayout.addWidget(self.importParameterFromFilePushButton, 0, 9, 1, 1)
        self.estimatorParameterFileLabel = QtWidgets.QLabel(self.scikitLearnSettingGroupBox)
        self.estimatorParameterFileLabel.setEnabled(False)
        self.estimatorParameterFileLabel.setObjectName("estimatorParameterFileLabel")
        self.gridLayout.addWidget(self.estimatorParameterFileLabel, 1, 0, 1, 1)
        self.estimatorParameterFileLineEdit = QtWidgets.QLineEdit(self.scikitLearnSettingGroupBox)
        self.estimatorParameterFileLineEdit.setEnabled(False)
        self.estimatorParameterFileLineEdit.setObjectName("estimatorParameterFileLineEdit")
        self.gridLayout.addWidget(self.estimatorParameterFileLineEdit, 1, 1, 1, 11)
        self.selectParameterTunerComboBox = QtWidgets.QComboBox(self.scikitLearnSettingGroupBox)
        self.selectParameterTunerComboBox.setObjectName("selectParameterTunerComboBox")
        self.selectParameterTunerComboBox.addItem("")
        self.selectParameterTunerComboBox.addItem("")
        self.gridLayout.addWidget(self.selectParameterTunerComboBox, 0, 7, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 0, 8, 1, 1)
        self.setParameterVerticalLayout.addWidget(self.scikitLearnSettingGroupBox)
        self.basicParameterVerticalLayout = QtWidgets.QVBoxLayout()
        self.basicParameterVerticalLayout.setContentsMargins(-1, 5, -1, -1)
        self.basicParameterVerticalLayout.setObjectName("basicParameterVerticalLayout")
        self.basicParameterLabel = QtWidgets.QLabel(self.setParameterPage)
        self.basicParameterLabel.setObjectName("basicParameterLabel")
        self.basicParameterVerticalLayout.addWidget(self.basicParameterLabel)
        self.basicParameterTableWidget = QtWidgets.QTableWidget(self.setParameterPage)
        self.basicParameterTableWidget.setRowCount(50)
        self.basicParameterTableWidget.setObjectName("basicParameterTableWidget")
        self.basicParameterTableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.basicParameterTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.basicParameterTableWidget.setHorizontalHeaderItem(1, item)
        self.basicParameterTableWidget.horizontalHeader().setStretchLastSection(True)
        self.basicParameterTableWidget.verticalHeader().setVisible(False)
        self.basicParameterVerticalLayout.addWidget(self.basicParameterTableWidget)
        self.setParameterVerticalLayout.addLayout(self.basicParameterVerticalLayout)
        self.scikitLearnSettingStackedWidget.addWidget(self.setParameterPage)
        self.trainEstimatorPage = QtWidgets.QWidget()
        self.trainEstimatorPage.setObjectName("trainEstimatorPage")
        self.trainModelHorizontalLayout = QtWidgets.QHBoxLayout(self.trainEstimatorPage)
        self.trainModelHorizontalLayout.setContentsMargins(0, 10, 0, 10)
        self.trainModelHorizontalLayout.setSpacing(5)
        self.trainModelHorizontalLayout.setObjectName("trainModelHorizontalLayout")
        self.preTrainingEstimatorInfoGroupBox = QtWidgets.QGroupBox(self.trainEstimatorPage)
        self.preTrainingEstimatorInfoGroupBox.setObjectName("preTrainingEstimatorInfoGroupBox")
        self.initModelTrainingInfoHorizontalLayout = QtWidgets.QHBoxLayout(self.preTrainingEstimatorInfoGroupBox)
        self.initModelTrainingInfoHorizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.initModelTrainingInfoHorizontalLayout.setObjectName("initModelTrainingInfoHorizontalLayout")
        self.preTrainingEstimatorInfoTextBrowser = QtWidgets.QTextBrowser(self.preTrainingEstimatorInfoGroupBox)
        self.preTrainingEstimatorInfoTextBrowser.setStyleSheet("background:rgb(240,240,240)")
        self.preTrainingEstimatorInfoTextBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.preTrainingEstimatorInfoTextBrowser.setObjectName("preTrainingEstimatorInfoTextBrowser")
        self.initModelTrainingInfoHorizontalLayout.addWidget(self.preTrainingEstimatorInfoTextBrowser)
        self.trainModelHorizontalLayout.addWidget(self.preTrainingEstimatorInfoGroupBox)
        self.trainEstimatorVerticalLayout = QtWidgets.QVBoxLayout()
        self.trainEstimatorVerticalLayout.setObjectName("trainEstimatorVerticalLayout")
        self.trainSettingGroupBox = QtWidgets.QGroupBox(self.trainEstimatorPage)
        self.trainSettingGroupBox.setObjectName("trainSettingGroupBox")
        self.trainEstimatorGridLayout = QtWidgets.QGridLayout(self.trainSettingGroupBox)
        self.trainEstimatorGridLayout.setContentsMargins(5, 5, 5, 5)
        self.trainEstimatorGridLayout.setObjectName("trainEstimatorGridLayout")
        self.nJobsComboBox = QtWidgets.QComboBox(self.trainSettingGroupBox)
        self.nJobsComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.nJobsComboBox.setObjectName("nJobsComboBox")
        self.trainEstimatorGridLayout.addWidget(self.nJobsComboBox, 2, 1, 1, 1)
        self.nJobsLabel = QtWidgets.QLabel(self.trainSettingGroupBox)
        self.nJobsLabel.setObjectName("nJobsLabel")
        self.trainEstimatorGridLayout.addWidget(self.nJobsLabel, 2, 0, 1, 1)
        self.kFoldCVLineEdit = QtWidgets.QLineEdit(self.trainSettingGroupBox)
        self.kFoldCVLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.kFoldCVLineEdit.setObjectName("kFoldCVLineEdit")
        self.trainEstimatorGridLayout.addWidget(self.kFoldCVLineEdit, 0, 1, 1, 1)
        self.kFoldCVLabel = QtWidgets.QLabel(self.trainSettingGroupBox)
        self.kFoldCVLabel.setObjectName("kFoldCVLabel")
        self.trainEstimatorGridLayout.addWidget(self.kFoldCVLabel, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.trainEstimatorGridLayout.addItem(spacerItem9, 1, 2, 1, 1)
        self.trainEstimatorPushButton = QtWidgets.QPushButton(self.trainSettingGroupBox)
        self.trainEstimatorPushButton.setObjectName("trainEstimatorPushButton")
        self.trainEstimatorGridLayout.addWidget(self.trainEstimatorPushButton, 1, 3, 1, 1)
        self.trainEstimatorVerticalLayout.addWidget(self.trainSettingGroupBox)
        self.trainingCVTestResultGroupBox = QtWidgets.QGroupBox(self.trainEstimatorPage)
        self.trainingCVTestResultGroupBox.setObjectName("trainingCVTestResultGroupBox")
        self.trainingCVTestResultGroupBoxGridLayout = QtWidgets.QGridLayout(self.trainingCVTestResultGroupBox)
        self.trainingCVTestResultGroupBoxGridLayout.setContentsMargins(5, 10, 5, 5)
        self.trainingCVTestResultGroupBoxGridLayout.setObjectName("trainingCVTestResultGroupBoxGridLayout")
        self.estimatorScore_1Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.estimatorScore_1Label.setText("")
        self.estimatorScore_1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.estimatorScore_1Label.setObjectName("estimatorScore_1Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.estimatorScore_1Label, 2, 2, 1, 1)
        self.estimatorEvaluationChartPushButton = QtWidgets.QPushButton(self.trainingCVTestResultGroupBox)
        self.estimatorEvaluationChartPushButton.setEnabled(False)
        self.estimatorEvaluationChartPushButton.setObjectName("estimatorEvaluationChartPushButton")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.estimatorEvaluationChartPushButton, 10, 3, 1, 1)
        self.trainingCrossValidationTestResultGroupBoxLine = QtWidgets.QFrame(self.trainingCVTestResultGroupBox)
        self.trainingCrossValidationTestResultGroupBoxLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.trainingCrossValidationTestResultGroupBoxLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.trainingCrossValidationTestResultGroupBoxLine.setObjectName("trainingCrossValidationTestResultGroupBoxLine")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.trainingCrossValidationTestResultGroupBoxLine, 9, 0, 1, 4)
        self.cvSampleCountLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.cvSampleCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cvSampleCountLabel.setObjectName("cvSampleCountLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.cvSampleCountLabel, 5, 1, 1, 1)
        self.sampleCountLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.sampleCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sampleCountLabel.setObjectName("sampleCountLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.sampleCountLabel, 2, 1, 1, 1)
        self.trainingScore_2Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.trainingScore_2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.trainingScore_2Label.setObjectName("trainingScore_2Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.trainingScore_2Label, 4, 3, 1, 1)
        self.estimatorLearningCurveChartPushButton = QtWidgets.QPushButton(self.trainingCVTestResultGroupBox)
        self.estimatorLearningCurveChartPushButton.setEnabled(False)
        self.estimatorLearningCurveChartPushButton.setObjectName("estimatorLearningCurveChartPushButton")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.estimatorLearningCurveChartPushButton, 10, 2, 1, 1)
        self.trainingSampleCountLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.trainingSampleCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trainingSampleCountLabel.setObjectName("trainingSampleCountLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.trainingSampleCountLabel, 4, 1, 1, 1)
        self.cvScore_1Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.cvScore_1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.cvScore_1Label.setObjectName("cvScore_1Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.cvScore_1Label, 5, 2, 1, 1)
        self.cvResultLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.cvResultLabel.setObjectName("cvResultLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.cvResultLabel, 5, 0, 1, 1)
        self.testScore_2Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.testScore_2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.testScore_2Label.setObjectName("testScore_2Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.testScore_2Label, 6, 3, 1, 1)
        self.trainingResultLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.trainingResultLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.trainingResultLabel.setObjectName("trainingResultLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.trainingResultLabel, 4, 0, 1, 1)
        self.testSampleCountLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.testSampleCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.testSampleCountLabel.setObjectName("testSampleCountLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.testSampleCountLabel, 6, 1, 1, 1)
        self.testResultLabel = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.testResultLabel.setObjectName("testResultLabel")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.testResultLabel, 6, 0, 1, 1)
        self.trainingScore_1Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.trainingScore_1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.trainingScore_1Label.setObjectName("trainingScore_1Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.trainingScore_1Label, 4, 2, 1, 1)
        self.estimatorScore_2Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.estimatorScore_2Label.setText("")
        self.estimatorScore_2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.estimatorScore_2Label.setObjectName("estimatorScore_2Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.estimatorScore_2Label, 2, 3, 1, 1)
        self.cvScore_2Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.cvScore_2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.cvScore_2Label.setObjectName("cvScore_2Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.cvScore_2Label, 5, 3, 1, 1)
        self.testScore_1Label = QtWidgets.QLabel(self.trainingCVTestResultGroupBox)
        self.testScore_1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.testScore_1Label.setObjectName("testScore_1Label")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.testScore_1Label, 6, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.trainingCVTestResultGroupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.line, 7, 0, 1, 4)
        self.bestEstimatorInfoTextBrowser = QtWidgets.QTextBrowser(self.trainingCVTestResultGroupBox)
        self.bestEstimatorInfoTextBrowser.setMaximumSize(QtCore.QSize(16777215, 125))
        self.bestEstimatorInfoTextBrowser.setStyleSheet("background:rgb(240,240,240)")
        self.bestEstimatorInfoTextBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bestEstimatorInfoTextBrowser.setObjectName("bestEstimatorInfoTextBrowser")
        self.trainingCVTestResultGroupBoxGridLayout.addWidget(self.bestEstimatorInfoTextBrowser, 8, 0, 1, 4)
        self.trainEstimatorVerticalLayout.addWidget(self.trainingCVTestResultGroupBox)
        self.trainModelHorizontalLayout.addLayout(self.trainEstimatorVerticalLayout)
        self.scikitLearnSettingStackedWidget.addWidget(self.trainEstimatorPage)
        self.saveEstimatorDataPage = QtWidgets.QWidget()
        self.saveEstimatorDataPage.setObjectName("saveEstimatorDataPage")
        self.saveModelHorizontalLayout = QtWidgets.QHBoxLayout(self.saveEstimatorDataPage)
        self.saveModelHorizontalLayout.setContentsMargins(0, 10, 0, 10)
        self.saveModelHorizontalLayout.setSpacing(5)
        self.saveModelHorizontalLayout.setObjectName("saveModelHorizontalLayout")
        self.saveEstimatorDataGroupBox = QtWidgets.QGroupBox(self.saveEstimatorDataPage)
        self.saveEstimatorDataGroupBox.setObjectName("saveEstimatorDataGroupBox")
        self.saveModelDataGroupBoxVerticalLayout = QtWidgets.QVBoxLayout(self.saveEstimatorDataGroupBox)
        self.saveModelDataGroupBoxVerticalLayout.setObjectName("saveModelDataGroupBoxVerticalLayout")
        self.saveEstimatorDataFormLayout = QtWidgets.QFormLayout()
        self.saveEstimatorDataFormLayout.setObjectName("saveEstimatorDataFormLayout")
        self.isSaveBestEstimatorToFileCheckBox = QtWidgets.QCheckBox(self.saveEstimatorDataGroupBox)
        self.isSaveBestEstimatorToFileCheckBox.setChecked(True)
        self.isSaveBestEstimatorToFileCheckBox.setObjectName("isSaveBestEstimatorToFileCheckBox")
        self.saveEstimatorDataFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.isSaveBestEstimatorToFileCheckBox)
        self.isSaveBestEstimatorToFileLineEdit = QtWidgets.QLineEdit(self.saveEstimatorDataGroupBox)
        self.isSaveBestEstimatorToFileLineEdit.setObjectName("isSaveBestEstimatorToFileLineEdit")
        self.saveEstimatorDataFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.isSaveBestEstimatorToFileLineEdit)
        self.isSaveEstimatorDataToExcelFileNameCheckBox = QtWidgets.QCheckBox(self.saveEstimatorDataGroupBox)
        self.isSaveEstimatorDataToExcelFileNameCheckBox.setChecked(True)
        self.isSaveEstimatorDataToExcelFileNameCheckBox.setObjectName("isSaveEstimatorDataToExcelFileNameCheckBox")
        self.saveEstimatorDataFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.isSaveEstimatorDataToExcelFileNameCheckBox)
        self.isSaveEstimatorDataToExcelFileNameLineEdit = QtWidgets.QLineEdit(self.saveEstimatorDataGroupBox)
        self.isSaveEstimatorDataToExcelFileNameLineEdit.setObjectName("isSaveEstimatorDataToExcelFileNameLineEdit")
        self.saveEstimatorDataFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.isSaveEstimatorDataToExcelFileNameLineEdit)
        self.isSaveTrainingDataToWorkingSheetNameCheckBox = QtWidgets.QCheckBox(self.saveEstimatorDataGroupBox)
        self.isSaveTrainingDataToWorkingSheetNameCheckBox.setChecked(True)
        self.isSaveTrainingDataToWorkingSheetNameCheckBox.setObjectName("isSaveTrainingDataToWorkingSheetNameCheckBox")
        self.saveEstimatorDataFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.isSaveTrainingDataToWorkingSheetNameCheckBox)
        self.isSaveTrainingDataToWorkingSheetNameLineEdit = QtWidgets.QLineEdit(self.saveEstimatorDataGroupBox)
        self.isSaveTrainingDataToWorkingSheetNameLineEdit.setObjectName("isSaveTrainingDataToWorkingSheetNameLineEdit")
        self.saveEstimatorDataFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.isSaveTrainingDataToWorkingSheetNameLineEdit)
        self.isSaveCVDataToWorkingSheetNameCheckBox = QtWidgets.QCheckBox(self.saveEstimatorDataGroupBox)
        self.isSaveCVDataToWorkingSheetNameCheckBox.setEnabled(True)
        self.isSaveCVDataToWorkingSheetNameCheckBox.setChecked(False)
        self.isSaveCVDataToWorkingSheetNameCheckBox.setObjectName("isSaveCVDataToWorkingSheetNameCheckBox")
        self.saveEstimatorDataFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.isSaveCVDataToWorkingSheetNameCheckBox)
        self.isSaveCVDataToWorkingSheetNameLineEdit = QtWidgets.QLineEdit(self.saveEstimatorDataGroupBox)
        self.isSaveCVDataToWorkingSheetNameLineEdit.setEnabled(True)
        self.isSaveCVDataToWorkingSheetNameLineEdit.setObjectName("isSaveCVDataToWorkingSheetNameLineEdit")
        self.saveEstimatorDataFormLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.isSaveCVDataToWorkingSheetNameLineEdit)
        self.isSaveTestDataToWorkingSheetNameCheckBox = QtWidgets.QCheckBox(self.saveEstimatorDataGroupBox)
        self.isSaveTestDataToWorkingSheetNameCheckBox.setEnabled(True)
        self.isSaveTestDataToWorkingSheetNameCheckBox.setChecked(False)
        self.isSaveTestDataToWorkingSheetNameCheckBox.setObjectName("isSaveTestDataToWorkingSheetNameCheckBox")
        self.saveEstimatorDataFormLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.isSaveTestDataToWorkingSheetNameCheckBox)
        self.isSaveTestDataToWorkingSheetNameLineEdit = QtWidgets.QLineEdit(self.saveEstimatorDataGroupBox)
        self.isSaveTestDataToWorkingSheetNameLineEdit.setEnabled(True)
        self.isSaveTestDataToWorkingSheetNameLineEdit.setObjectName("isSaveTestDataToWorkingSheetNameLineEdit")
        self.saveEstimatorDataFormLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.isSaveTestDataToWorkingSheetNameLineEdit)
        self.saveModelDataGroupBoxVerticalLayout.addLayout(self.saveEstimatorDataFormLayout)
        self.saveEstimatorDataGroupBoxVerticalLayoutLine = QtWidgets.QFrame(self.saveEstimatorDataGroupBox)
        self.saveEstimatorDataGroupBoxVerticalLayoutLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.saveEstimatorDataGroupBoxVerticalLayoutLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.saveEstimatorDataGroupBoxVerticalLayoutLine.setObjectName("saveEstimatorDataGroupBoxVerticalLayoutLine")
        self.saveModelDataGroupBoxVerticalLayout.addWidget(self.saveEstimatorDataGroupBoxVerticalLayoutLine)
        self.saveModelDataHorizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.saveModelDataHorizontalLayout_1.setObjectName("saveModelDataHorizontalLayout_1")
        self.selectEstimatorDataSaveDirectoryLabel = QtWidgets.QLabel(self.saveEstimatorDataGroupBox)
        self.selectEstimatorDataSaveDirectoryLabel.setObjectName("selectEstimatorDataSaveDirectoryLabel")
        self.saveModelDataHorizontalLayout_1.addWidget(self.selectEstimatorDataSaveDirectoryLabel)
        self.selectEstimatorDataSaveDirectoryLineEdit = QtWidgets.QLineEdit(self.saveEstimatorDataGroupBox)
        self.selectEstimatorDataSaveDirectoryLineEdit.setObjectName("selectEstimatorDataSaveDirectoryLineEdit")
        self.saveModelDataHorizontalLayout_1.addWidget(self.selectEstimatorDataSaveDirectoryLineEdit)
        self.selectEstimatorDataSaveDirectoryPushButton = QtWidgets.QPushButton(self.saveEstimatorDataGroupBox)
        self.selectEstimatorDataSaveDirectoryPushButton.setText("")
        self.selectEstimatorDataSaveDirectoryPushButton.setObjectName("selectEstimatorDataSaveDirectoryPushButton")
        self.saveModelDataHorizontalLayout_1.addWidget(self.selectEstimatorDataSaveDirectoryPushButton)
        self.saveModelDataGroupBoxVerticalLayout.addLayout(self.saveModelDataHorizontalLayout_1)
        self.saveEstimatorDataHorizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.saveEstimatorDataHorizontalLayout_2.setObjectName("saveEstimatorDataHorizontalLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.saveEstimatorDataHorizontalLayout_2.addItem(spacerItem10)
        self.resetSaveParameterPushButton = QtWidgets.QPushButton(self.saveEstimatorDataGroupBox)
        self.resetSaveParameterPushButton.setObjectName("resetSaveParameterPushButton")
        self.saveEstimatorDataHorizontalLayout_2.addWidget(self.resetSaveParameterPushButton)
        self.saveEstimatorDataPushButton = QtWidgets.QPushButton(self.saveEstimatorDataGroupBox)
        self.saveEstimatorDataPushButton.setObjectName("saveEstimatorDataPushButton")
        self.saveEstimatorDataHorizontalLayout_2.addWidget(self.saveEstimatorDataPushButton)
        self.saveModelDataGroupBoxVerticalLayout.addLayout(self.saveEstimatorDataHorizontalLayout_2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.saveModelDataGroupBoxVerticalLayout.addItem(spacerItem11)
        self.saveModelHorizontalLayout.addWidget(self.saveEstimatorDataGroupBox)
        self.scikitLearnSettingStackedWidget.addWidget(self.saveEstimatorDataPage)
        self.topDialogVerticalLayout.addWidget(self.scikitLearnSettingStackedWidget)
        self.bottomOperationWidgetHorizontalLayout = QtWidgets.QHBoxLayout()
        self.bottomOperationWidgetHorizontalLayout.setContentsMargins(-1, 5, -1, -1)
        self.bottomOperationWidgetHorizontalLayout.setObjectName("bottomOperationWidgetHorizontalLayout")
        self.stepLogoLabel = QtWidgets.QLabel(ScikitLearnMLDialog)
        self.stepLogoLabel.setObjectName("stepLogoLabel")
        self.bottomOperationWidgetHorizontalLayout.addWidget(self.stepLogoLabel)
        self.stepTipLabel = QtWidgets.QLabel(ScikitLearnMLDialog)
        self.stepTipLabel.setObjectName("stepTipLabel")
        self.bottomOperationWidgetHorizontalLayout.addWidget(self.stepTipLabel)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomOperationWidgetHorizontalLayout.addItem(spacerItem12)
        self.previousStepPushButton = QtWidgets.QPushButton(ScikitLearnMLDialog)
        self.previousStepPushButton.setEnabled(False)
        self.previousStepPushButton.setObjectName("previousStepPushButton")
        self.bottomOperationWidgetHorizontalLayout.addWidget(self.previousStepPushButton)
        self.nextStepPushButton = QtWidgets.QPushButton(ScikitLearnMLDialog)
        self.nextStepPushButton.setObjectName("nextStepPushButton")
        self.bottomOperationWidgetHorizontalLayout.addWidget(self.nextStepPushButton)
        self.cancelFinishPushButton = QtWidgets.QPushButton(ScikitLearnMLDialog)
        self.cancelFinishPushButton.setObjectName("cancelFinishPushButton")
        self.bottomOperationWidgetHorizontalLayout.addWidget(self.cancelFinishPushButton)
        self.topDialogVerticalLayout.addLayout(self.bottomOperationWidgetHorizontalLayout)

        self.retranslateUi(ScikitLearnMLDialog)
        self.scikitLearnSettingStackedWidget.setCurrentIndex(0)
        self.selectEstimatorComboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(ScikitLearnMLDialog)

    def retranslateUi(self, ScikitLearnMLDialog):
        _translate = QtCore.QCoreApplication.translate
        ScikitLearnMLDialog.setWindowTitle(_translate("ScikitLearnMLDialog", "scikit-learn机器学习"))
        self.operationTitleLabel.setText(_translate("ScikitLearnMLDialog", "选择样本"))
        self.operationDescriptionLabel.setText(_translate("ScikitLearnMLDialog", "选择训练模型所用的样本数据"))
        self.operationLogoLabel.setText(_translate("ScikitLearnMLDialog", "TextLabel"))
        self.classificationDesciptionLabel.setText(_translate("ScikitLearnMLDialog", "该分类特指监督学习分类，这是一种使用已标记，即带有离散数值特征标签的训练数据，训练机器学习分类模型，从而达到推断未知标签的数据样本，属于特定类别中的哪一类的机器学习任务。"))
        self.classificationTaskRadioButton.setText(_translate("ScikitLearnMLDialog", "分类"))
        self.regressionDesciptionLabel.setText(_translate("ScikitLearnMLDialog", "该回归特指监督学习回归，回归也可交数据拟合、预测，这是一种使用已标记，即带有数值连续特性特点标签的训练数据，训练机器学习回归模型，从而达到预测出未知标签的数据样本值的任务。"))
        self.regressionTaskRadioButton.setText(_translate("ScikitLearnMLDialog", "回归"))
        self.clusterDesciptionLabel.setText(_translate("ScikitLearnMLDialog", "聚类属于非监督学习算法，使用未知分类标签（通常也需要标签用以调试模型参数或评估模型训练精度）的训练数据训练机器学习聚类模型，从而达到推断应用场景中未知标签的数据，属于特定类别中的哪一类的机器学习任务。"))
        self.clusterTaskRadioButton.setText(_translate("ScikitLearnMLDialog", "聚类"))
        self.sampleSettingGroupBox.setTitle(_translate("ScikitLearnMLDialog", "样本设置"))
        self.isIncludeColTitleCheckBox.setText(_translate("ScikitLearnMLDialog", "包含列标题"))
        self.selectTrainingValidationSampleLabel.setText(_translate("ScikitLearnMLDialog", "训练-验证样本："))
        self.sampleTypeLabel.setText(_translate("ScikitLearnMLDialog", "样本文件类型："))
        self.selectTestSampleLabel.setText(_translate("ScikitLearnMLDialog", "测试样本（可选）："))
        self.isIncludeRowTitleCheckBox.setText(_translate("ScikitLearnMLDialog", "包含行标题"))
        self.isRowMajorRadioButton.setText(_translate("ScikitLearnMLDialog", "行优先"))
        self.isColMajorRadioButton.setText(_translate("ScikitLearnMLDialog", "列优先"))
        self.selectParameterTypeLabel.setText(_translate("ScikitLearnMLDialog", "参数类型："))
        self.selectParameterTypeComboBox.setItemText(0, _translate("ScikitLearnMLDialog", "默认参数"))
        self.selectParameterTypeComboBox.setItemText(1, _translate("ScikitLearnMLDialog", "调试参数"))
        self.selectParameterTypeComboBox.setItemText(2, _translate("ScikitLearnMLDialog", "本地文件"))
        self.selectParameterTunerLabel.setText(_translate("ScikitLearnMLDialog", "参数调试器："))
        self.selectEstimatorLabel.setText(_translate("ScikitLearnMLDialog", "学习器："))
        self.estimatorParameterFileLabel.setText(_translate("ScikitLearnMLDialog", "参数文件："))
        self.selectParameterTunerComboBox.setItemText(0, _translate("ScikitLearnMLDialog", "格网搜索"))
        self.selectParameterTunerComboBox.setItemText(1, _translate("ScikitLearnMLDialog", "随机搜索"))
        self.basicParameterLabel.setText(_translate("ScikitLearnMLDialog", "基本参数："))
        item = self.basicParameterTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ScikitLearnMLDialog", "参数名称"))
        item = self.basicParameterTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ScikitLearnMLDialog", "参数取值"))
        self.preTrainingEstimatorInfoGroupBox.setTitle(_translate("ScikitLearnMLDialog", "预训练模型信息"))
        self.trainSettingGroupBox.setTitle(_translate("ScikitLearnMLDialog", "训练设置"))
        self.nJobsLabel.setText(_translate("ScikitLearnMLDialog", "工作核心数："))
        self.kFoldCVLineEdit.setText(_translate("ScikitLearnMLDialog", "5"))
        self.kFoldCVLabel.setText(_translate("ScikitLearnMLDialog", "交叉验证（K）："))
        self.trainEstimatorPushButton.setText(_translate("ScikitLearnMLDialog", "训练"))
        self.trainingCVTestResultGroupBox.setTitle(_translate("ScikitLearnMLDialog", "训练结果"))
        self.estimatorEvaluationChartPushButton.setText(_translate("ScikitLearnMLDialog", "模型评估图表"))
        self.cvSampleCountLabel.setText(_translate("ScikitLearnMLDialog", "-"))
        self.sampleCountLabel.setText(_translate("ScikitLearnMLDialog", "样本数"))
        self.trainingScore_2Label.setText(_translate("ScikitLearnMLDialog", "-"))
        self.estimatorLearningCurveChartPushButton.setText(_translate("ScikitLearnMLDialog", "学习曲线图表"))
        self.trainingSampleCountLabel.setText(_translate("ScikitLearnMLDialog", "-"))
        self.cvScore_1Label.setText(_translate("ScikitLearnMLDialog", "-"))
        self.cvResultLabel.setText(_translate("ScikitLearnMLDialog", "验证："))
        self.testScore_2Label.setText(_translate("ScikitLearnMLDialog", "-"))
        self.trainingResultLabel.setText(_translate("ScikitLearnMLDialog", "训练："))
        self.testSampleCountLabel.setText(_translate("ScikitLearnMLDialog", "-"))
        self.testResultLabel.setText(_translate("ScikitLearnMLDialog", "测试："))
        self.trainingScore_1Label.setText(_translate("ScikitLearnMLDialog", "-"))
        self.cvScore_2Label.setText(_translate("ScikitLearnMLDialog", "-"))
        self.testScore_1Label.setText(_translate("ScikitLearnMLDialog", "-"))
        self.bestEstimatorInfoTextBrowser.setHtml(_translate("ScikitLearnMLDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Null</p></body></html>"))
        self.saveEstimatorDataGroupBox.setTitle(_translate("ScikitLearnMLDialog", "保存设置"))
        self.isSaveBestEstimatorToFileCheckBox.setText(_translate("ScikitLearnMLDialog", "保存最优模型到本地文件的文件名"))
        self.isSaveEstimatorDataToExcelFileNameCheckBox.setText(_translate("ScikitLearnMLDialog", "保存模型训练数据、验证数据及测试数据结果到本地文件（Excel）的文件名："))
        self.isSaveTrainingDataToWorkingSheetNameCheckBox.setText(_translate("ScikitLearnMLDialog", "保存模型训练数据结果到本地文件（Excel）中的工作表名称："))
        self.isSaveCVDataToWorkingSheetNameCheckBox.setText(_translate("ScikitLearnMLDialog", "保存模型验证数据结果到本地文件（Excel）中的工作表名称："))
        self.isSaveTestDataToWorkingSheetNameCheckBox.setText(_translate("ScikitLearnMLDialog", "保存模型测试数据结果到本地文件（Excel）中的工作表名称："))
        self.selectEstimatorDataSaveDirectoryLabel.setText(_translate("ScikitLearnMLDialog", "保存路径："))
        self.resetSaveParameterPushButton.setText(_translate("ScikitLearnMLDialog", "重置参数"))
        self.saveEstimatorDataPushButton.setText(_translate("ScikitLearnMLDialog", "保存结果"))
        self.stepLogoLabel.setText(_translate("ScikitLearnMLDialog", "TextLabel"))
        self.stepTipLabel.setText(_translate("ScikitLearnMLDialog", "选择本地样本文件后，点击“下一步”以继续操作！"))
        self.previousStepPushButton.setText(_translate("ScikitLearnMLDialog", "上一步"))
        self.nextStepPushButton.setText(_translate("ScikitLearnMLDialog", "下一步"))
        self.cancelFinishPushButton.setText(_translate("ScikitLearnMLDialog", "取消"))
